- internal/cli/cmd/cli.go
the usage like kubectl, see https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-cli-plugin/README.md#shell-completion
the `kbcli_complete-ns` : 
```sh
#!/usr/bin/env bash
args=("$@")
lastArg=${args[((${#args[@]}-1))]}
if [[ "$lastArg" == -* ]]; then
if [[ "$lastArg" != *=* ]]; then
kbcli ns __complete "$@"
fi
else
kubectl get namespaces --output go-template='{{ range .items }}{{ .metadata.name }}{{"\n"}}{{ end }}'
echo :4
fi
```
> feat: cli plugin support auto completion like kubectl

- controllers/apps/systemaccount_controller_test.go
- fix #3624  
The intention is to delete 1-st job, not 0-th job. updated
> fix: job not found

- .github/workflows/release-publish.yml
- To meet the requirements for `krew`.
- Add the kbcli `license` and `README.md` in .tar.gz
> chore: zip license and readme.md with kbcli for krew

- internal/cli/cloudprovider/k3d.go
- internal/cli/cmd/kubeblocks/install.go
- internal/cli/cmd/playground/init.go
fix #3649 
cli playground should NOT continue to install KubeBlocks when KubeBlocks already exists
> fix: cli playground error when repeatedly init 

- internal/cli/cloudprovider/k3d.go
- internal/cli/cmd/kubeblocks/install.go
- internal/cli/cmd/playground/init.go
fix https://github.com/apecloud/kubeblocks/issues/3649
cli playground should NOT continue to install KubeBlocks when KubeBlocks already exists
> fix: cli playground error when repeatedly init

- deploy/apecloud-mysql-scale/templates/backuptool.yaml
- deploy/apecloud-mysql/templates/backuptool.yaml
support arm64 xtrabackup for apecloud mysql backup tool.
fix: #3576
> feat: support arm64 xtrabackup for apecloud mysql backup tool.

- internal/cli/cmd/fault/fault.go
- internal/cli/cmd/fault/fault_http_test.go
* resolve: #3552
After installing chaos-mesh in the cluster for the first time, regardless of whether chaos-mesh is uninstalled or not, k8s can detect related CRDs, so even if chaos-mesh is not installed, it is possible to create crd resources such as podchaos and netwokchaos. This will make the user feel that the fault has been successfully injected. So here is a hint if chaos-mesh is not installed. The effect is as follows:
```
./bin/kbcli fault network partition mysql-cluster-mysql-0
error: chaos-mesh is not enabled, use `kbcli addon enable chaos-mesh` to  enable chaos-mesh first
```
> feat: check chaos-mesh if enable before injecting faults

- docs/user_docs/installation/uninstall-kbcli-and-kubeblocks.md
- fix https://kubeblocks.io/docs/release-0.5/user_docs/installation/uninstall-kbcli-and-kubeblocks
`~./kbcli` to `~/.kbcli`
> fix: fix the file name error in kubeblocks.io

- internal/cli/testing/testdata/hostpreflight.yaml
- internal/cli/testing/testdata/hostpreflight_nil.yaml
This pr will fix test fail when KB is installed in a low-spec machine, such as just 2 core cpu in ecs.
> fix: change preflight checks rule for low spec machine in test case

- controllers/apps/systemaccount_controller.go
- controllers/apps/systemaccount_controller_test.go
- controllers/apps/systemaccount_util_test.go
- fix #3739 
This path updates the code in : 
1. add a job failed event to cluster 
2. update testcase, there is no need to delete jobs explicitly, all jobs will be delete in `cleanUp` stage.  
The root cause of this unstable case is:  we are racing others to remove finalizer.  
1. a object under deletion has an `orphan` fianlizer, added by apiserver, and will later be removed by GC (Garbage Collector)
2. the testcase explicitly removes the finalizer, racing against the GC module in the envtest.   
But if this `oprhan` finalizer is deleted by that GC module,  we will get an Object Not Found error.  The testcase should leave the work to `cleanUp` function and leave jobs as they are.
> chore: update unstable testcases and add events for failed jobs

- .github/workflows/cicd-push.yml
1. loss of test coverage
Test coverage needs to be submitted when push code.
Loss of coverage of failed UT tests after running in parallel.
2. usgae limits
reference: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
> chore: push test rollback to runs on gke

- internal/cli/cmd/cli.go
- internal/cli/cmd/cli_test.go
- internal/cli/cmd/playground/init.go
* fix #3759
Reproduce:
1. create a k3d cluster
2. edit the metrics-server, use a wrong image, the metrics-server will disabled
3. install KubeBlocks
```bash
kubectl get pods -A
NAMESPACE     NAME                                                     READY   STATUS             RESTARTS   AGE
kube-system   local-path-provisioner-76d776f6f9-bsh6v                  1/1     Running            0          60m
kube-system   coredns-59b4f5bbd5-m6sz4                                 1/1     Running            0          60m
kube-system   helm-install-traefik-crd-fxc9j                           0/1     Completed          0          60m
kube-system   helm-install-traefik-29g6d                               0/1     Completed          1          60m
kube-system   svclb-traefik-a782e64e-5wtc6 …
```
> fix: cli  not logged as error in memcache discovery client

- internal/constant/const.go
- internal/controller/builder/builder.go
- internal/controller/builder/builder_test.go
https://github.com/apecloud/kubeblocks/issues/3795
when users create a cluster, they can customize the environment variables through annotation: "kubeblocks.io/extra-env", and finally these environment variables will be applied to all containers under the cluster.
> feat: support User-defined environment variables

- .github/utils/utils.sh
- .github/workflows/pull-request-check.yml
- .github/workflows/pull-request-label-size.yaml
1. not check fork PR branch name
2. fix fork PR label error : GraphQL: Resource not accessible by integration (addLabelsToLabelable)
> chore: not check fork PR branch name

- internal/cli/cmd/version/version.go
> feat: support warning version difference between kbcli and kubeblocks

- deploy/postgresql-cluster/Chart.yaml
- deploy/postgresql/templates/clusterversion.yaml
fix pgvector `Illegal instruction`
> chore: support postgresql 12.15.0 and 14.8.0

- deploy/postgresql/templates/clusterversion.yaml
Add image registry for pgbouncer.
Result:
```
- name: pgbouncer
image: registry.cn-hangzhou.aliyuncs.com/apecloud/pgbouncer:1.19.0
- name: pgbouncer
image: registry.cn-hangzhou.aliyuncs.com/apecloud/pgbouncer:1.19.0
- name: pgbouncer
image: registry.cn-hangzhou.aliyuncs.com/apecloud/pgbouncer:1.19.0
- name: pgbouncer
image: registry.cn-hangzhou.aliyuncs.com/apecloud/pgbouncer:1.19.0
```
> chore: add image registry for pgbouncer image

- internal/cli/cmd/cluster/operations.go
- internal/cli/cmd/cluster/operations_test.go
- fix: #3859 
What i do:
1. use `recover()` to fix panic and throw an error in a friendly output
2. add UTs
Example:
> fix: output more friendly  when run `kbcli cluster vscale` with invalid input 

- apis/dataprotection/v1alpha1/backup_types.go
- config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
- controllers/apps/cluster_controller_test.go
- controllers/dataprotection/backup_controller.go
- controllers/dataprotection/backup_controller_test.go
- controllers/dataprotection/backuppolicy_controller.go
- controllers/dataprotection/backuppolicy_controller_test.go
- deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
- internal/cli/cmd/cluster/dataprotection.go
- internal/cli/cmd/cluster/dataprotection_test.go
- internal/controllerutil/errors.go
add legitimacy validation and dispaly availablePods for running backup:
1. only can create logfile backup by enabling logfile schedule in backupPolicy.
2. display the availablePods for running backup.
> chore: support legitimacy validation for logfile backup and display availablePods for running backup

- .github/workflows/cicd-push.yml
1. The workflow without make test will cancel the workflow of make test,causing the main coverage not upload.
> chore: not cancel push main workflow

- deploy/helm/dashboards/container-log.json
- deploy/helm/dashboards/kubernetes-log.json
- deploy/helm/templates/grafana/configmaps-datasources.yaml
- internal/cli/cmd/dashboard/dashboard.go
- internal/cli/cmd/dashboard/grafana_direct.go
This pr has two functions:
1. add loki dashboard for kubernetes pods log
2. add `kbcli dashboard open kubeblocks-loki` to rediect http://127.0.0.1:13100/d/kubernetes-logs/kubernetes-logs?orgId=1
> feat: add loki dashboard for kubernetes pods log

- deploy/nebula-cluster/Chart.yaml
- deploy/nebula-cluster/templates/NOTES.txt
- deploy/nebula-cluster/templates/_helpers.tpl
- deploy/nebula-cluster/templates/cluster.yaml
- deploy/nebula-cluster/values.yaml
- deploy/nebula/Chart.yaml
- deploy/nebula/configs/nebula-graphd.conf.tpl
- deploy/nebula/configs/nebula-metad.conf.tpl
- deploy/nebula/configs/nebula-storaged.conf.tpl
- deploy/nebula/scripts/nebula-graphd-start.sh.tpl
- deploy/nebula/scripts/nebula-metad-start.sh.tpl
- deploy/nebula/scripts/nebula-storaged-start.sh.tpl
- deploy/nebula/templates/NOTES.txt
- deploy/nebula/templates/_helpers.tpl
- deploy/nebula/templates/clusterdefinition.yaml
- deploy/nebula/templates/clusterversion.yaml
- deploy/nebula/templates/configmap.yaml
- deploy/nebula/templates/scripts.yaml
- deploy/nebula/values.yaml
close #3835 
- Added `deploy/nebula` & `deploy/nebula-cluster` containing necessary cluster definitions, configs, scripts for Nebula Graph.
- Able to create NebulaGraph clusters with the following steps:
1. install nebula and nebula-cluster
```bash
helm install nebula ./deploy/nebula
helm install nebula-cluster ./deploy/nebula-cluster
```
2. port-forward svc to localhost
```
kubectl port-forward svc/nebula-cluster-nebula-graphd 9669:9669
```
3. connect to graphd using nebula-console
```
./nebula-console --addr 127.0.0.1 --port 9669 -u root -p nebula
```
and add storaged hosts 
```
ADD HOSTS "nebula-cluster-nebula-storaged-0.nebula-cluster-nebula-storaged-headless.default.svc.cluster.local":9779
ADD HOSTS "nebula-cluster-nebula-storaged-1.nebula-cluster-nebula-storaged-headless.default.svc. …
```
> feat: support nebulagraph

- controllers/extensions/addon_controller_stages.go
- deploy/helm/templates/addons/alertmanager-webhook-adaptor-addon.yaml
- deploy/helm/templates/addons/apecloud-mysql-addon.yaml
- deploy/helm/templates/addons/aws-loadbalancer-controller-addon.yaml
- deploy/helm/templates/addons/csi-driver-addon.yaml
- deploy/helm/templates/addons/csi-hostpath-driver-addon.yaml
- deploy/helm/templates/addons/csi-s3-addon.yaml
- deploy/helm/templates/addons/grafana-addon.yaml
- deploy/helm/templates/addons/migration-addon.yaml
- deploy/helm/templates/addons/milvus-addon.yaml
- deploy/helm/templates/addons/mongodb-addon.yaml
- deploy/helm/templates/addons/nyancat-addon.yaml
- deploy/helm/templates/addons/postgresql-addon.yaml
- deploy/helm/templates/addons/prometheus-addon.yaml
- deploy/helm/templates/addons/qdrant-addon.yaml
- deploy/helm/templates/addons/redis-addon.yaml
- deploy/helm/templates/addons/snapshot-controller-addon.yaml
- deploy/helm/templates/addons/weaviate-addon.yaml
- deploy/helm/templates/deployment.yaml
- deploy/helm/values.yaml
If addonChartLocationURL has prefix "oci://", use the oci url as chart location, and add `version` to addon installOptions.
> chore: addon support to set private helm registry

- docs/user_docs/cli/cli.md
- docs/user_docs/cli/kbcli_cluster.md
- docs/user_docs/cli/kbcli_cluster_promote.md
- docs/user_docs/cli/kbcli_kubeblocks.md
- docs/user_docs/cli/kbcli_kubeblocks_describe-config.md
- internal/cli/cmd/kubeblocks/config.go
- internal/cli/cmd/kubeblocks/config_test.go
This pr has following changes:
1: add examples and test cases for `kubeblocks describe-config` cmd
2: sync cli-doc
3: refactor code
> chore: add examples and test cases for kubeblocks describe-config

- docs/user_docs/cli/cli.md
- docs/user_docs/cli/kbcli_bench_sysbench.md
- docs/user_docs/cli/kbcli_bench_sysbench_cleanup.md
- docs/user_docs/cli/kbcli_bench_sysbench_prepare.md
- docs/user_docs/cli/kbcli_cluster.md
- docs/user_docs/cli/kbcli_cluster_cancel-ops.md
- docs/user_docs/cli/kbcli_cluster_promote.md
- go.mod
- internal/cli/cmd/bench/bench.go
- internal/cli/cmd/bench/bench_test.go
- internal/cli/cmd/bench/sysbench.go
```sh
run a SysBench benchmark
Examples:
kbcli bench sysbench mycluster --user xxx --password xxx --database mydb
kbcli bench sysbench mycluster --user xxx --password xxx --database mydb --threads 4,8
kbcli bench sysbench mycluster --user xxx --password xxx --database mydb --type oltp_read_only,oltp_read_write
kbcli bench sysbench mycluster --user xxx --password xxx  --database mydb --type oltp_read_write_pct --read-percent 80
--write-percent 80
kbcli bench sysbench mycluster --user xxx --password xxx --database mydb --tables 10 --size 25000
Available Commands:
cleanup       Cleanup the data of SysBench for cluster
prepare       Prepare the data of SysBench for a cluster
run           Run  SysBench on cluster
Usage:
kbcli bench sysbench [flags] [options]
Use "kbcli <command> --help" for …
```
> feat: kbcli bench need more clear tips

- deploy/nebula-cluster/templates/cluster.yaml
- deploy/nebula/scripts/nebula-console-start.sh.tpl
- deploy/nebula/templates/clusterdefinition.yaml
- deploy/nebula/templates/clusterversion.yaml
- deploy/nebula/templates/scripts.yaml
- deploy/nebula/values.yaml
- fix #3980  
In this commit, we introduced a new component `nebula-console` to Nebula ClusterDefinition. It plays the role of nebula client, and helps regists `storaged`  to `metad` to setup the cluster.
> feat: support nebula-console in nebula-cluster

- controllers/apps/components/replication/replication_utils.go
- deploy/postgresql/templates/scripts.yaml
- deploy/redis/templates/scripts.yaml
> fix: replicationSet parallel update strategy restart failed

- deploy/apecloud-mysql-cluster/templates/cluster.yaml
- deploy/apecloud-mysql/templates/clusterdefinition.yaml
- deploy/apecloud-mysql/templates/scripts.yaml
* fix #4036
add annotation to set container environment:
```
kubeblocks.io/extra-env: '{"KB_PROXY_ENABLED":"on"}'
```
Now, support to enable or disable proxy dynamicly.
create cluster without proxy:
enable the proxy:
```
helm upgrade my ./deploy/apecloud-mysql-cluster --set mode=raftGroup,proxyEnabled=true
```
When disable proxy, the extra proxy components existing again, maybe a bug, delete them manually and enable again.
> fix: miss vttablet container for mysql

- apis/apps/v1alpha1/backuppolicytemplate_types.go
- apis/apps/v1alpha1/cluster_types.go
- config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
- config/crd/bases/apps.kubeblocks.io_clusters.yaml
- controllers/apps/cluster_status_conditions.go
- deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
- deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
- internal/controller/builder/builder.go
clusterDefinitionRef in clusterSpec and BackupPolicyTemplateSpec is immutable, add validation rule to avoid being modified.
For example:
```
$ kubectl edit cluster rose55
#
#
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
annotations:
kubeblocks.io/reconcile: "2023-07-02T16:44:33.011949+08:00"
creationTimestamp: "2023-07-02T06:07:12Z"
finalizers:
- cluster.kubeblocks.io/finalizer
generation: 3
```
> chore: add validation rule for immutable fields

- Makefile
- internal/cli/cmd/kubeblocks/install.go
- internal/cli/cmd/kubeblocks/install_test.go
fix https://github.com/apecloud/kubeblocks/issues/4001
now run 'make vet' in mac is ok 
~/work/kubeblocks  ‹bugfix/installation-with-kb-controller-toleration-issue4001› $ make vet                                                                                                                                                                           2 ↵
GOOS=darwin go vet -mod=mod ./...
~/work/kubeblocks  ‹bugfix/installation-with-kb-controller-toleration-issue4001› $
> fix: add kb-controller toleration as default for kubeblock installation

- apis/apps/v1alpha1/backuppolicytemplate_types.go
- apis/dataprotection/v1alpha1/backuppolicy_types.go
- config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
- config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
- controllers/apps/transformer_backup_policy_tpl.go
- controllers/dataprotection/backuppolicy_controller.go
- controllers/dataprotection/backuppolicy_controller_test.go
- deploy/apecloud-mysql/templates/backuppolicytemplate.yaml
- deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
- deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
- deploy/mongodb/templates/backuppolicytemplate.yaml
- deploy/postgresql/templates/backuppolicytemplate.yaml
- deploy/redis/templates/backuppolicytemplate.yaml
- internal/testutil/apps/backuppolicy_factory.go
`startWindowMinutes` defines the time window for starting the job if it misses scheduled time for any reason. the unit of time is minute.
> fea: support startWindowMinutes for cron backup

- deploy/apecloud-mysql/config/mysql-scale-config.tpl
- deploy/apecloud-mysql/config/mysql-scale-vtconsensus-config-constraint.cue
- deploy/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
- deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
- deploy/apecloud-mysql/templates/clusterdefinition.yaml
- deploy/apecloud-mysql/templates/configconstraint.yaml
- deploy/apecloud-mysql/templates/configmap.yaml
- deploy/apecloud-mysql/templates/scripts.yaml
* move the wesql scale component's startup scripts to scripts.yaml.
* add `initContainers` in `vtgate`,`vtconsensus` and `vtctld` components to avoid Failed status during the cluster startup.
* add mysql scale configuration.
Reconfigure command example:
```
kbcli cluster configure vt --set=healthcheck_timeout=10s --component=vtgate
kbcli cluster configure vt --set=health_check_interval=4s --component=mysql --config-spec=mysql-scale-config
```
all mysql scale related configurations are treated as static parameters.
!!! **Please note** that this change will impact the MySQL configuration. This means that after installing the cluster using `helm install mysql-cluster deploy/apecloud-mysql-cluster --set mode=raftGroup`，when reconfiguring MySQL, you must include `--config-spec`, for example: …
> chore: add mysql scale configuration

- docs/user_docs/cli/cli.md
- docs/user_docs/cli/kbcli_cluster.md
- docs/user_docs/cli/kbcli_cluster_describe-backup.md
- docs/user_docs/cli/kbcli_kubeblocks_compare.md
- internal/cli/cmd/cluster/cluster.go
- internal/cli/cmd/cluster/dataprotection.go
- internal/cli/cmd/cluster/dataprotection_test.go
- add `describe-backup` sub command with following output:
```
kbcli cluster describe-backup backup-default-pg-20230705174337
Name: backup-default-pg-20230705174337	Cluster: pg	Namespace: default
Spec:
Type:               datafile
Policy Name:        pg-postgresql-backup-policy
Status:
Phase:              Completed
Backup Tool:        postgres-basebackup
PVC Name:           kb-backup-data
Duration:           93s
Expiration Time:    Jul 12,2023 17:43 UTC+0800
Start Time:         Jul 05,2023 17:43 UTC+0800
Completion Time:    Jul 05,2023 17:45 UTC+0800
Manifests:
Log Start Time:     Jul 05,2023 17:33 UTC+0800
Log Stop Time:      Jul 05,2023 17:33 UTC+0800
File Path:          /default/pg-696cc9d9-d488-4e88-a933-2ab91478d301/postgresql/backup-default-pg-20230705174337
Volume Name: …
```
> feat: add kbcli cluster describe-backup command

- apis/dataprotection/v1alpha1/backuppolicy_types.go
- apis/dataprotection/v1alpha1/backuprepo_types.go
- config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
- controllers/dataprotection/backup_controller.go
- controllers/dataprotection/backup_controller_test.go
- controllers/dataprotection/backuppolicy_controller.go
- controllers/dataprotection/backuppolicy_controller_test.go
- controllers/dataprotection/backuprepo_controller.go
- controllers/dataprotection/backuprepo_controller_test.go
- controllers/dataprotection/type.go
- controllers/dataprotection/utils.go
- deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
- internal/cli/cmd/cluster/dataprotection.go
- internal/cli/testing/fake.go
- internal/testutil/apps/backuppolicy_factory.go
- internal/testutil/apps/backuprepo_factory.go
- internal/testutil/apps/base_factory.go
- test/testdata/backup/backuprepo.yaml
- test/testdata/backup/storageprovider.yaml
This PR integrates BackupRepo with the backup controller.
To be compatible with the old backup behavior, it will only use the PVC created by BackupRepo if `CommonBackupPolicy.PersistentVolumeClaim.Name` is empty.
The backup object searches for an available backup repo in the following order:
* Use the repo specified by the `dataprotection.kubeblocks.io/backup-repo-name` label in the backup object.
* Use the repo specified in the backup policy.
* Use the global default repo.
If there are multiple default repos in the system, the backup will fail because it cannot select a repo. This behavior follows the k8s StorageClass.
to #3407.
> feat: integrate BackupRepo to backup controller

- .goreleaser.yaml
* resolve  #4161
The bug of the cotainers package requires the cgo option to be enabled for compilation. If you do not want to enable cgo, you can add tags `containers_image_openpgp`. 
For details, see:
https://github.com/containers/image/pull/1638
> fix: fix goreleaser build

- internal/cli/cmd/cluster/create.go
- internal/cli/cmd/cluster/create_test.go
- internal/cli/cmd/cluster/dataprotection.go
- PITR limit 1 replica for apecloud mysql in kbcli.(mysql kernel will support multi replicas in the next few days.)
- fix kbcli doesn't work when created from backup config via `--set`
> fix: limit 1 replica at mysql point-in-time recovery

- .github/workflows/cicd-pull-request.yml
- deploy/apecloud-mysql-cluster/values.yaml
- deploy/kblib/templates/_schedule.tpl
- deploy/kblib/values.schema.json
- deploy/kblib/values.yaml
fix #3020 
- make `node` as the default topologyKey
- make `podAntiAffinity: Required` for ApeCloud-MySQL
> fix: change `ApeCloud-MySQL` affinity template

- deploy/kblib/templates/_helper.tpl
- docs/DEVELOPING.md
- docs/user_docs/cli/kbcli_cluster_create_kafka.md
- docs/user_docs/cli/kbcli_cluster_create_mongodb.md
- docs/user_docs/cli/kbcli_cluster_create_mysql.md
- docs/user_docs/cli/kbcli_cluster_create_postgresql.md
- docs/user_docs/cli/kbcli_cluster_create_redis.md
- internal/cli/cluster/cluster_chart.go
- internal/cli/cluster/cluster_chart_test.go
- internal/cli/cmd/cluster/create_subcmds.go
- internal/cli/cmd/cluster/create_subcmds_test.go
* fix #4199
```shell
$ kb cluster create mysql --publicly-accessible=true --dry-run
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
labels:
app.kubernetes.io/instance: tea51
app.kubernetes.io/version: 8.0.30
helm.sh/chart: apecloud-mysql-cluster-0.5.0-alpha.0
name: tea51
namespace: default
spec:
affinity:
podAntiAffinity: Required
tenancy: SharedNode
topologyKeys:
- kubernetes.io/hostname
clusterDefinitionRef: apecloud-mysql
clusterVersionRef: ac-mysql-8.0.30
componentSpecs:
- componentDefRef: mysql
enabledLogs:
- slow
- error
monitor: false
name: mysql
replicas: 1
resources:
limits:
cpu: "1"
memory: 1Gi
requests:
cpu: "1"
memory: 1Gi
serviceAccountName: kb-sa-tea51
services:
- annotations:
service.beta.kubernetes.io/aws-load-balancer-internal: "false" …
```
> fix: cli created cluster without expected public service

- deploy/helm/templates/addons/migration-addon.yaml
- deploy/kafka-cluster/templates/cluster.yaml
- deploy/kafka-cluster/values.schema.json
- deploy/kafka-cluster/values.yaml
- deploy/kafka/scripts/kafka-server-setup.sh.tpl
- deploy/kafka/templates/clusterdefinition.yaml
1. add: support kafka jvm heap setting
2. fix: kafka data storage is not work
3. change some storage setting with kafka
4. change kbcli kafka resource setting default value
`kbt cluster create kafka -h
Create a kafka cluster.
Examples:
\# Create a cluster with the default values
kbcli cluster create kafka
\# Create a cluster with the specified cpu, memory and storage
kbcli cluster create kafka --cpu 1 --memory 2 --storage 10
Options:
--availability-policy='none':
The availability policy of cluster. Legal values [none, node, zone].
--broker-heap='-XshowSettings:vm -XX:MaxRAMPercentage=100 -Ddepth=64':
Kafka broker's jvm heap setting.
--broker-replicas=1:
The number of Kafka broker replicas for separated mode.
--controller-heap='-XshowSettings:vm -XX:MaxRAMPercentage=100 -Ddepth=64':
Kafka …
> chore: kafka bugfix & support jvm setting

- deploy/helm/dashboards/container-log.json
- deploy/helm/dashboards/loki.json
- deploy/helm/values.yaml
This pr has following changes:
1: add dashboard for loki instance
2: data retention is 72h for loki
3: refine container logs dashboard
> feat: add metrics dashboard for loki instance

- apis/apps/v1alpha1/cluster_types.go
- apis/apps/v1alpha1/cluster_types_test.go
- deploy/helm/templates/_helpers.tpl
- deploy/helm/templates/configmap.yaml
- deploy/helm/templates/deployment.yaml
- deploy/helm/templates/storageclass.yaml
- deploy/helm/values.yaml
- internal/constant/const.go
* https://github.com/apecloud/kubeblocks/issues/4212
kbcli does not support to set storageClass when create cluster again, it should use the specified storage class in KubeBlocks's config. 
So, we should support a method let user to set the default storage class. 
This PR make KubeBlocks helm chart supports to set default storage class name and `create` storage class or not. 
If `storageClass.name` is specified, created cluster will use this storage class. If `storageClass.create` is true and KubeBlocks is deployed in cloud, a storage class will be created.
> feat: support to create default storage class and use it

- apis/dataprotection/v1alpha1/backuprepo_types.go
- config/crd/bases/dataprotection.kubeblocks.io_backuprepos.yaml
- config/crd/kustomization.yaml
- config/crd/patches/cainjection_in_dataprotection_backuprepos.yaml
- config/crd/patches/webhook_in_dataprotection_backuprepos.yaml
- config/rbac/dataprotection_backuprepo_editor_role.yaml
- config/rbac/dataprotection_backuprepo_viewer_role.yaml
- config/rbac/role.yaml
- controllers/dataprotection/backuprepo_controller.go
- deploy/helm/config/rbac/role.yaml
- deploy/helm/crds/dataprotection.kubeblocks.io_backuprepos.yaml
- docs/user_docs/api-reference/backup.md
For the BackupRepo resource, the plural names generated by kubebuilder and client-gen are inconsistent: kubebuilder uses “backuprepoes”, while client-gen uses “backuprepos”, which causes the generated client to fail to operate the BackupRepo resource (such as FakeDynamicClient). Since no convenient method was found to control the generation of client-gen, the plural name in the CRD was manually modified to use “backuprepos” uniformly.
fix #4251
> fix: inconsistent generated plural

- controllers/dataprotection/backuprepo_controller.go
- deploy/csi-s3/Chart.yaml
- deploy/csi-s3/templates/driver.yaml
- deploy/csi-s3/values.yaml
- deploy/helm/templates/storageprovider/minio.yaml
- deploy/helm/templates/storageprovider/oss.yaml
- deploy/helm/templates/storageprovider/s3.yaml
- docs/user_docs/cli/cli.md
- docs/user_docs/cli/kbcli.md
- go.mod
- internal/cli/cmd/backuprepo/backuprepo.go
- internal/cli/cmd/backuprepo/backuprepo_test.go
- internal/cli/cmd/backuprepo/create.go
- internal/cli/cmd/backuprepo/create_test.go
- internal/cli/cmd/backuprepo/suite_test.go
- internal/cli/cmd/cli.go
- internal/cli/testing/fake.go
- internal/cli/types/types.go
- internal/cli/util/flags/flags.go
This PR implements the `kbcli backuprepo create` command, which is used to create BackupRepo resources, with the following behavior:
* The user needs to specify the --provider parameter, indicating which storage backend the repo uses;
* kbcli gets the spec of that StorageProvider from the API server, then dynamically builds command flags, and parses the command line parameters passed by the user;
* Then create the BackupRepo resource.
Examples:
```bash
kbcli backuprepo create \
--provider s3 \
--region cn-northwest-1 \
--bucket test-kb-backup \
--access-key-id <ACCESS KEY> \
--secret-access-key <SECRET KEY>
kbcli backuprepo create my-repo \
--provider oss \
--region cn-hangzhou \
--bucket test-kb-backup \
--access-key-id <ACCESS KEY> \
--secret-access-key <SECRET KEY> \
--default
```
This …
> feat: kbcli backuprepo create

- internal/controller/builder/cue/rbac_template.cue
* fix https://github.com/apecloud/kubeblocks/issues/4260
> fix: rbac_templdate use wrong namespace

- internal/cli/util/util.go
- internal/cli/util/util_test.go
I encountered a `nil pointer dereference` panic after add another configSpec in apecloud-mysql cd and reconfiguration with `kbcli cluster configure vt --set=max_connections=200`. That is because `cfgcore.GenerateOpenAPISchema` returned `nil,nil` when configurationSchema has empty CUE field and `CfgSchemaTopLevelName`. 
I have added a check and now return `true, nil` directly to prevent this panic.
> fix: nil pointer dereference when configurationSchema has empty CUE field

- deploy/apecloud-mysql/templates/_helpers.tpl
- deploy/apecloud-mysql/templates/agamotto-configmap.yaml
- deploy/apecloud-mysql/templates/clusterdefinition.yaml
- deploy/apecloud-mysql/templates/scripts.yaml
- deploy/helm/dashboards/mysql-proxy.json
I have moved the agamotto configurations from `agamotto-configmap.yaml` to `_helpers.tpl`. The `agamotto-config.yaml` is same as before, while the new `agamotto-config-with-proxy.yaml` merged the configurations used by monitoring vttablet sidecar when proxy is enabled.
> chore: add wesql-scale monitor configuration

- docs/user_docs/installation/install-kbcli.md
as titled
The correct way to write the name of Apple's operating system for Mac computers is "macOS", with a lowercase "m" and an uppercase "C".
> doc: fix  the capitalization issue

- deploy/apecloud-mysql-cluster/templates/_helpers.tpl
- deploy/apecloud-mysql/config/mysql-scale-vtconsensus-config.tpl
- deploy/apecloud-mysql/config/mysql-scale-vtgate-config.tpl
- deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
- deploy/apecloud-mysql/config/mysql-scale-vttablet-config.tpl
- deploy/apecloud-mysql/templates/clusterdefinition.yaml
- deploy/apecloud-mysql/templates/configmap.yaml
- deploy/apecloud-mysql/templates/scripts.yaml
- deploy/apecloud-mysql/values.yaml
* We found that the default configuration of table_acl_config_mode is set to "mysqlbased," which can cause issue #4289. Added a configurable item `table_acl_config_mode` and setting it to "simple" can address this problem temporarily.
* To avoid confusion when users use configuration and execute `kbcli cluster describe-config --show-detail`, the configuration tpl files of the wesql-scale related components are split.
* Add some missing logConfigs.
> fix: split the wesql-scale configuration to avoid confusion and add table_acl_config_mode config item

- internal/controller/component/component.go
- #4290
What i do:
- ~~do a `workloadtype` check before `overrideSwitchoverSpecAttr()`~~
- validate `switchoverSpec` during `overrideSwitchoverSpecAttr()`
> fix: fix the mismatched clusterdefiniton with cv cause buildcomponent panic 

- docs/user_docs/cli/kbcli_cluster_edit-backup-policy.md
- internal/cli/cmd/cluster/dataprotection.go
- internal/cli/cmd/cluster/dataprotection_test.go
See https://github.com/apecloud/kubeblocks/issues/4329 for details.
Usage:
```bash
kbcli cluster edit-backup-policy wesql2-mysql-backup-policy --set="datafile.backupRepoName=myrepo"
kbcli cluster edit-backup-policy wesql2-mysql-backup-policy --set="datafile.backupRepoName="
```
fix #4329
> chore: "kbcli cluster edit-backup-policy" supports updating backup repo

- deploy/pulsar/templates/configconstraints.yaml
- internal/configuration/config_manager/builder.go
- internal/controller/builder/builder.go
- internal/controller/builder/builder_test.go
- internal/controller/plan/prepare.go
- internal/controller/plan/tool_image_builder.go
configconstraint dependence on configspec.name:
old:
```
toolsImageSpec:
mountPoint: /kb/tools
toolConfigs:
- name: init-pulsar-client-config
command:
- "/opt/kb-tools/reload/broker-config/install-pulsar-client-config.sh"
```
new:
```
toolsImageSpec:
mountPoint: /kb/tools
toolConfigs:
- name: init-pulsar-client-config
command:
- "$(TOOLS_SCRIPTS_PATH)/install-pulsar-client-config.sh"
```
> chore: removed configconstraint dependence on configspec.name, using env TOOLS_SCRIPTS_PATH

- apis/dataprotection/v1alpha1/backuprepo_types.go
- config/crd/bases/dataprotection.kubeblocks.io_backuprepos.yaml
- controllers/dataprotection/backuprepo_controller.go
- controllers/dataprotection/backuprepo_controller_test.go
- deploy/helm/crds/dataprotection.kubeblocks.io_backuprepos.yaml
`kubectl get backuprepo` will print out more information.
```bash
% kg backuprepo
NAME                    STATUS   STORAGEPROVIDER   DEFAULT   AGE
backuprepo-jg2mb        Ready    oss                         21s
kubeblocks-backuprepo   Ready    s3                true      3d
```
> chore: add printcolumn annotations to BackupRepo CRD

- internal/cli/cmd/cluster/create.go
- fix:#4412
What i do:
fix the check default **storageclass** logic: when we check if there are already default **storageclass** in `k8s`, we will not check the `kubeblocks` **configmap**.
> fix: fix kbcli create cluster when test kb locally

- internal/cli/cmd/addon/addon.go
- fix: #4422
What i do:
1. reuse the `list` options to specify the `Names`
> chore: kbcli addon list support specified name

- internal/cli/cluster/cluster_chart.go
- fix: #4465
What i do:
- fix the invalid path of cluster charts in windows
> fix: fix the `kbcli` basic command failed in windows

- docs/user_docs/cli/kbcli_cluster_connect.md
- internal/cli/cmd/cluster/connect.go
- internal/cli/cmd/cluster/connect_test.go
- fix: #4455 
What i do:
1. add the `--show-password` flag for `getConnectionInfo`. If `--show-password` is false, the info.password will be replaced by a password mask "******"
2. fix the UTs
Example:
> feat: add the --show-password flag to control the display of passwords.

- deploy/apecloud-mysql-cluster/templates/_helpers.tpl
- deploy/apecloud-mysql/config/mysql-scale-vtconsensus-config-constraint.cue
- deploy/apecloud-mysql/config/mysql-scale-vtconsensus-config.tpl
- deploy/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
- deploy/apecloud-mysql/config/mysql-scale-vtgate-config.tpl
- deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
- deploy/apecloud-mysql/config/mysql-scale-vttablet-config.tpl
- deploy/apecloud-mysql/templates/clusterdefinition.yaml
- deploy/apecloud-mysql/templates/scripts.yaml
- deploy/apecloud-mysql/values.yaml
- internal/cli/cmd/cluster/update.go
* fix #4398 
Add two configuration items: `enable_logs` and `enable_query_log`, to the 'logsBlocks' for wesql-scale related components.
Reset buffer before tpl.Execute in the reconfigureLogVariables function to avoid confusion when dealing with multiple components.
* replace etcd with vtconsensus as the default container for vtcontroller.
* persistent wesql-scale related components' log files in pv except vtgate, as it's a stateless component. Ignore vtgate temporary until the newest log collection workaround is available
> fix: make mysql-scale cluster 'enabled-all-logs' work properly

- controllers/apps/configuration/config_reconcile_wrapper.go
- controllers/apps/configuration/config_related_helper.go
- controllers/apps/configuration/config_util.go
- controllers/apps/configuration/reconfigurerequest_controller.go
reconfiguring operator:
1. reconfiguring operator depends on many resources (cluster, configmap, configstraint, clusterdefinition, clusterversion, statefulset, deployment....) , which leads to two problems:
* resource access logic is coupled with the main reconcile logic
* resource access exception checking is coupled with reconcile logic detection
2. lots of check functions return error, making the code difficult to understand
refator code:
1. Split the access to the dependent resources into separate module;
2. [Fluent style sdk](https://en.wikipedia.org/wiki/Fluent_interface) is used to access different resources, which reduces to check the function retuned error;
3. Use Named return values to eliminate nil and useless err variables;
> chore: refine reconfigure reconcile code

- deploy/redis/templates/clusterdefinition.yaml
- deploy/redis/templates/scripts.yaml
- fix : #3798 
Accounts are not flushed to config files as expected. So we add a `pre-Stop` hook to make sure accounts will be written back to config file.
> fix: redis account not save to file as expected

- .github/workflows/release-sync.yml
- fix: https://github.com/apecloud/kubeblocks/issues/2293
What i do:
Add the chocolatey CI workflows
> feat: support kbcli auto-publish for chocolatey

- deploy/risingwave-cluster/.helmignore
- deploy/risingwave-cluster/Chart.yaml
- deploy/risingwave-cluster/templates/_helpers.tpl
- deploy/risingwave-cluster/templates/cluster.yaml
- deploy/risingwave-cluster/values.yaml
- deploy/risingwave/.helmignore
- deploy/risingwave/Chart.yaml
- deploy/risingwave/config/risingwave-compute-envs.tpl
- deploy/risingwave/config/risingwave-connector-envs.tpl
- deploy/risingwave/templates/_helpers.tpl
- deploy/risingwave/templates/clusterdefinition.yaml
- deploy/risingwave/templates/clusterversion.yaml
- deploy/risingwave/templates/risingwave-compute-envs-configmap.yaml
- deploy/risingwave/templates/risingwave-config-configmap.yaml
- deploy/risingwave/templates/risingwave-connector-envs-configmap.yaml
- deploy/risingwave/values.yaml
Hi, it's been nice to see such an effort on bringing DBaaS onto Kubernetes. It's not easy. The PR here tries to implement the [RisingWave](https://github.com/risingwavelabs/risingwave) deployment with CRs provided in kubeblocks. Basically, it works now. However, there're also things not going well and need hacks. 
RisingWave's a bit special compared to other DBs. It relies on S3 or other object stores to work. It requires an additional etcd service to store its metadata. That means it's purely stateless itself. So to make it work, one should be required to provide such two services beforehand. 
In my own attempt, I used [bitnami/etcd](https://github.com/bitnami/charts/tree/main/bitnami/etcd) to start an etcd instance. Here's an example of the values and command:
```yaml
auth:
rbac: …
```
> feat(deploy): add ClusterDefinition and Cluster example for RisingWave

- internal/cli/cmd/bench/bench.go
> fix: kbcli bench return proper message when kubebench is not enabled

- deploy/postgresql/config/pg12-config.tpl
- deploy/postgresql/config/pg14-config.tpl
- internal/cli/cmd/builder/template/util.go
- internal/controller/plan/builtin_functions.go
- internal/controller/plan/config_template.go
- internal/controller/plan/config_template_test.go
- internal/controllerutil/pod_utils.go
- internal/controllerutil/pod_utils_test.go
sealos data disk is very small(e.g: 1Gi), but wal log takes up 800MB+, causing the disk to be full! 
new rule：
When the disk size is below 5G, the wal log limit is set to 256MB.
> chore: Optimizing wal log parameters for small-size instances, e.g: Sealos instances

- controllers/apps/cluster_plan_builder.go
- controllers/apps/components/base.go
- internal/controller/graph/dag.go
- internal/controller/graph/dag_test.go
- internal/controller/rsm/plan_builder.go
now, updating CR uses the `client.Update` interface, and there may be errors when the CR version number is not the latest. When performing an hscale, the workload object will be updated very early. If the update of other objects fails, then entering the coordination again will not lead to the logic of compPhase to `Updating`, but rather to the logic of `upRunning`, changing the cluster status to Abnormal/Failed
> fix: postgresql/redis cluster hscale ops status is incorrect

- .github/workflows/release-sync.yml
1. sync [apecloud/helm-charts](https://github.com/apecloud/helm-charts/releases/tag/kubeblocks-0.5.3) release latest version is consistent with kubeblocks
> chore: sync helm charts release latest

- internal/cli/cmd/cluster/create.go
* fix https://github.com/apecloud/kubeblocks/issues/4610
> fix: get cd and cv from backup if creating cluster by backup

- docs/user_docs/cli/kbcli_bench_pgbench.md
- docs/user_docs/cli/kbcli_bench_sysbench.md
- docs/user_docs/cli/kbcli_bench_tpcc.md
- docs/user_docs/cli/kbcli_bench_ycsb.md
- go.mod
- go.sum
- internal/cli/cmd/bench/bench.go
- internal/cli/cmd/bench/pgbench.go
- internal/cli/cmd/bench/sysbench.go
- internal/cli/cmd/bench/tpcc.go
- internal/cli/cmd/bench/ycsb.go
just run the sysbench benchmark
just prepare the sysbench testdata
just cleanup the sysbench testdata
just run the tpcc benchmark
> feat: kbcli bench support only cleanup, prepare or run

- internal/cli/cmd/cluster/update.go
- internal/cli/cmd/cluster/update_test.go
Should not fail if there is no logBlock in the component configuration，e.g: vttablet
> fix: failed to update with --enable-all-logs (#4672)

- internal/cli/cmd/accounts/delete.go
- internal/cli/cmd/cluster/operations.go
- internal/cli/delete/delete.go
- internal/cli/util/prompt/prompt.go
- fix: https://github.com/apecloud/kubeblocks/issues/4665
What i do:
distinguish ops for kbcli confirm between `cluster delete` by labelSelector and other ops that use `Confirm()`
Example:
> fix: distinguish ops for kbcli confirm

- deploy/kafka-cluster/templates/cluster.yaml
- deploy/kafka/templates/clusterdefinition.yaml
for https://github.com/apecloud/kubeblocks/issues/4573:
- make sure the content in the connection credential secret is correct
- adjust the order of the controller and broker components in the definition in the separated mode to ensure that the component that needs to expose the service is at the first
for https://github.com/apecloud/kubeblocks/issues/4436: 
- remove useless volumeClaimTemplates configuration in kafka cluster definition
> fix: kafka definition bugfix about conn credential and volume expand

- internal/cli/cmd/cluster/create.go
error: The Cluster "redis-cluster" is invalid: spec.componentSpecs[1]: Duplicate value: map[string]interface {}{"name":"redis-sentinel"}
> fix: failed to create cluster with --set-file

- controllers/apps/cluster_controller_test.go
- controllers/apps/components/base_stateful_hscale.go
This PR will try to resolve 3 problems about scale-out:
1.  w/o h-scale policy, after a volume expansion operation, the scaled-out replicas volume size are different with old ones
2. w/ h-scale policy configured, if there are more than one volumes claimed for a component, the scale-out operation will block
3. w/ h-scale policy configured, if there are more than one volumes claimed for a component, the size of some volumes will be inconsistent
> fix: keep volumes size consistent after scale-out

- deploy/kafka-cluster/templates/cluster.yaml
- deploy/kafka/configs/kafka-server-constraint.cue
- deploy/kafka/scripts/kafka-server-setup.sh.tpl
- deploy/kafka/templates/clusterdefinition.yaml
- deploy/kafka/templates/configconstraint.yaml
1. https://github.com/apecloud/kubeblocks/issues/4705 
fix Kafka ConfigConstraint
3. https://github.com/apecloud/kubeblocks/issues/4708 
for client broker interaction, use pod ip in non-public network environment and headless service dns in public network environment
> fix: Kafka access control under different networks & ConfigConstraint fix

- controllers/dataprotection/backuppolicy_controller.go
- controllers/dataprotection/utils.go
- deploy/mongodb/dataprotection/pitr-backup.sh
- deploy/postgresql/dataprotection/pitr-backup.sh
- deploy/postgresql/templates/backuptool-pitr.yaml
Currently, PGSQL and Apecloud mysql use cronjob to regularly archive logs, which may pose the following risks:
1. If there are a large number of clusters and job scheduling is carried out simultaneously, it may cause significant pressure on the API server.
2. the minimum timing unit for cronjob is at the minute level, which poses a high risk of data loss
> feat: replace to stateful deploy kind for pgsql wal archive

- controllers/apps/components/base_stateful_hscale.go
- deploy/helm/templates/addons/snapshot-controller-addon.yaml
- deploy/redis/templates/backuptool.yaml
Ack has a built-in snapshot controller. If there are multiple snapshot controllers, it will cause the volume snapshot to not be deleted
> fix: sometimes hscale mysql failed in ack

- deploy/greptimedb-cluster/.helmignore
- deploy/greptimedb-cluster/Chart.yaml
- deploy/greptimedb-cluster/templates/NOTES.txt
- deploy/greptimedb-cluster/templates/_helpers.tpl
- deploy/greptimedb-cluster/templates/cluster.yaml
- deploy/greptimedb-cluster/values.yaml
- deploy/greptimedb/.helmignore
- deploy/greptimedb/Chart.yaml
- deploy/greptimedb/templates/NOTES.txt
- deploy/greptimedb/templates/_helpers.tpl
- deploy/greptimedb/templates/clusterdefinition.yaml
- deploy/greptimedb/templates/clusterversion.yaml
- deploy/greptimedb/templates/configmap.yaml
- deploy/greptimedb/templates/serviceaccount.yaml
- deploy/greptimedb/values.yaml
- deploy/helm/templates/addons/greptimedb-addon.yaml
> feat: add GreptimeDB support

- deploy/bytebase/Chart.yaml
- deploy/bytebase/templates/auto-plugin.yaml
- deploy/bytebase/templates/script.yaml
- deploy/helm/templates/addons/bytebase-addon.yaml
- do more to fix : https://github.com/apecloud/kubeblocks/issues/4636
The more integrated Bytebase we can use now! When we enable bytebase addon, we can use the email `admin@example.com` and password `admin` to login and all the clusters created by Kubeblocks will already added into Bytebase in the `kubeblocks` enviroment.
What i do:
Add a k8s `job` when bytebase start up and it will perform a series of actions, including user registration, environment creation, and instance creation by invoking the Bytebase API.
And it's easy to reach auto injection for new clusters in KB after Bytebase addon enabled. Just change the `job` to a `CronJob`.
usage:
1.  `kbcli addon enble bytebase`
2.  `kbcli dashboard open bytebase`
3. login by email: `admin@example.com` and  password: `admin`
> feat: add auto signup and KB clusters auto injection to Bytebase

- .github/workflows/cherry-pick.yml
resolve #3758 
cherry-pick preconditions:
1. PR is merged.
2. The target branch exists and has no conflict.
3. The target branch is not a protected branch.
```
Usage:
/cherry-pick release-0.6
```
cherry-pick success
cherry-pick error
> chore: auto cherry-pick workflow

- internal/cli/cmd/cluster/config_edit.go
- internal/cli/cmd/cluster/config_ops.go
- internal/cli/util/util.go
- internal/configuration/reconfigure_util.go
Some parameters, such as datadir, that are not allowed to be modified, which may cause the engine to fail to restart.
This feature depends on configconstraints.spec.**_immutableParameters_**.
> feat: verify the parameters are allowed to be modified (#4804)

- deploy/greptimedb-cluster/Chart.yaml
- deploy/greptimedb/Chart.yaml
- deploy/greptimedb/templates/clusterdefinition.yaml
- deploy/greptimedb/values.yaml
Fixes #4827 
- add a env for meta to fix the inner bug for greptimedb
- add init containers for components to refine startup order
- using `configSpec` to mount configmap
> fix: improve frontend and configmap for greptimedb

- cmd/probe/internal/component/mongodb/manager.go
- cmd/probe/internal/component/mongodb/types.go
- deploy/mongodb/Chart.yaml
- deploy/mongodb/dataprotection/backup-info-collector.sh
- deploy/mongodb/dataprotection/pitr-backup.sh
- deploy/mongodb/scripts/replicaset-restore.tpl
- deploy/mongodb/scripts/replicaset-setup.tpl
- deploy/mongodb/templates/clusterversion.yaml
- deploy/mongodb/templates/scriptstemplate.yaml
- docker/Dockerfile-tools.bk
- internal/controller/builder/builder.go
- internal/sqlchannel/engine/mongodb.go
1. add multiple versions support for mongodb, including 4.0 4.2, 4.4, 5.0, and 6.0.
2. support mongodb scale-out and scale-in, the number of replica set members can range from 0 to 7.
> feat: mongodb multi version support

- controllers/apps/configuration/config_util.go
- controllers/apps/configuration/reconfigure_policy.go
- controllers/apps/configuration/reconfigurerequest_controller.go
- controllers/apps/operations/pipeline.go
- controllers/apps/operations/reconfigure.go
- controllers/apps/operations/reconfigure_util.go
- internal/cli/cmd/cluster/config_edit.go
- internal/cli/cmd/cluster/config_ops_test.go
- internal/cli/cmd/cluster/errors.go
- internal/cli/cmd/cluster/operations.go
- internal/cli/create/template/cluster_operations_template.cue
- internal/cli/util/util.go
1. fix kbcli edit-config prompt typo;
2. fix a bug in the validation of file changes;
3. refine reconfiguring operation, stream programming mode to eliminate a lot of conditional judgments, and make code clearer;
```go
result := pipeline.ValidateParameters().
ConfigMap().
ConfigConstraints().
Merge().
Sync().
Complete()
```
4. Second confirmation when the configuration file changes:
> chore: fix some bug and refine reconfiguring operator

- .github/workflows/cicd-pull-request.yml
- .github/workflows/cicd-push.yml
- .github/workflows/release-image.yml
> chore: release image kubeblocks-dataprotection

- docs/user_docs/cli/kbcli_kubeblocks_upgrade.md
- internal/cli/cmd/accounts/delete.go
- internal/cli/cmd/cluster/operations.go
- internal/cli/cmd/kubeblocks/install.go
- internal/cli/cmd/kubeblocks/list_versions_test.go
- internal/cli/cmd/kubeblocks/upgrade.go
- internal/cli/cmd/kubeblocks/upgrade_test.go
- internal/cli/delete/delete.go
- internal/cli/util/helm/helm.go
- internal/cli/util/prompt/prompt.go
- fix #4860 
What i do:
1. reuse `Confirm` to double-check for KB upgrade and add the custom prompt for `Confirm`
2. add related `auto-approve` flag
3. fix some Unit tests
Example:
> fix: double check for kb upgrade

- deploy/helm/templates/addons/jupyterhub-addon.yaml
- fix: #4932
Jupyter-hub officail helm chart url https://jupyterhub.github.io/helm-chart/jupyterhub-3.0.2.tgz is not attachable in GKE.
So we use our mirror url for jupyter-hub.
Jupyter-notebooks seems already running in my test and not need to fix.
> fix: fix jupyter-hub enable fail in GKE

- controllers/apps/configuration/config_reconcile_wrapper.go
- controllers/apps/configuration/reconfigurerequest_controller.go
1. fix update bug;
2. the rsm related logic is in the configReconcileContext.rsm, Configuration reconcile does not depend on rsm.
> fix: failed to update statefulSet for rsm component when reconfiguring

- .github/utils/release_gitlab.sh
fix upload gitlab asset  {"message":"500 Internal Server Error"} retry
> chore: upload gitlab asset error retry

- controllers/apps/configuration/config_related_helper.go
- controllers/apps/configuration/config_util.go
- internal/configuration/core/type.go
- internal/controller/plan/envfrom_utils.go
- internal/controller/plan/envfrom_utils_test.go
- internal/controller/plan/prepare_test.go
- internal/controllerutil/pod_utils.go
- internal/controllerutil/pod_utils_test.go
- internal/controllerutil/volume_util.go
The current configuration operator assumes that the configmap is mounted, and the configmap associated with envFrom will not be reconcile.
> chore: check containers.volumeMounts and containers.envFrom (#4421)

- deploy/risingwave-cluster/values.schema.json
- deploy/risingwave-cluster/values.yaml
- fix #5085  
Risingwave depends on an exisited ETCD Cluster, and S3 credentials. So we add some constraints in its `values.schema.json`.
> chore: update rw values

- controllers/apps/components/utils.go
My K8S cluster and image repository deploy in private network enviroment. K8S cluster can not pull image from public network. I need to parse image named as xxx.xxx.xxx:port/imagename:tag in a private image repo.When I vertically scale the redis/mysql cluster, the image is replaced by "KUBEBLOCKS_TOOLS_IMAGE".
> fix: solving the problem of private image

- deploy/oceanbase-cluster/.helmignore
- deploy/oceanbase-cluster/Chart.yaml
- deploy/oceanbase-cluster/templates/NOTES.txt
- deploy/oceanbase-cluster/templates/_helpers.tpl
- deploy/oceanbase-cluster/templates/cluster.yaml
- deploy/oceanbase-cluster/templates/role.yaml
- deploy/oceanbase-cluster/templates/rolebinding.yaml
- deploy/oceanbase-cluster/templates/serviceaccount.yaml
- deploy/oceanbase-cluster/values.yaml
- deploy/oceanbase/.helmignore
- deploy/oceanbase/Chart.yaml
- deploy/oceanbase/templates/NOTES.txt
- deploy/oceanbase/templates/_helpers.tpl
- deploy/oceanbase/templates/clusterdefinition.yaml
- deploy/oceanbase/templates/clusterversion.yaml
- deploy/oceanbase/values.yaml
- internal/cli/create/template/cluster_template.cue
- lorry/engine/oceanbase.go
- fix #5122 
Support Oceanbase Cluster
Features:
1. Ad-hoc cluster bootstrap 
2. Dynamically scale in and out
3. Instance crash recovery
DO NOT SUPPORT:
1. Modify zone count when cluster is running
2. Upgrade OB image version on the fly
3. Monitor system running status
> feat: Support Oceanbase Cluster

- go.mod
- internal/cli/cluster/builtin_charts.go
- internal/cli/cluster/cluster_chart.go
- internal/cli/cluster/external_charts.go
- internal/cli/cluster/register.go
- internal/cli/cluster/register_test.go
- internal/cli/cmd/cluster/register.go
- internal/cli/cmd/cluster/register_test.go
- fix #5158
- fix #5159 
- fix #5154 
In this PR, we have optimized the 'cluster register' command, primarily addressing the following points:
**Usage**:
> fix: fix cluster register the same command, absolute path error and pre-check

- docs/user_docs/cli/kbcli_cluster_create.md
- internal/cli/cmd/cluster/create.go
- internal/cli/cmd/cluster/create_test.go
- fix https://github.com/apecloud/kubeblocks/issues/4367
- fix https://github.com/apecloud/kubeblocks/issues/3589
Now we support to create multiple `ClusterComponentVolumeClaimTemplate` in one cluster `Component`. In order to achieve idempotent behavior, we introduced a "pvc" flag. On top of the existing build component logic, we separately added the build process for "volumeClaimTemplates," and the value of "--pvc" will override the value of "--set" for storage.
Usage:
**What's more:**
Now we also support to use `kbcli cluster register [cluster-type] --source [cluster-chart-url]` to register the cluster-type as the kbcli cluster create sub-command. In this way, the multiple volumeClaimTemplates could be set in `values.yaml` and validated in `values.schema.json`. However, it rely on a …
> feat: kbcli cluster create for multiple volumeClaimTemplates

- apis/storage/v1alpha1/storageprovider_types.go
- config/crd/bases/storage.kubeblocks.io_storageproviders.yaml
- controllers/dataprotection/backuprepo_controller.go
- controllers/dataprotection/backuprepo_controller_test.go
- controllers/dataprotection/type.go
- deploy/helm/crds/storage.kubeblocks.io_storageproviders.yaml
- deploy/helm/templates/storageprovider/pvc.yaml
This PR adds an optional field `persistentVolumeClaimTemplate` to the StorageProvider spec, which is a Go Template for rendering the backup PVC spec. Based on this capability, we can use the existing (or default) StorageClass in the K8s cluster to provision PVs for storing backup data. This is useful in some scenarios, for example, users can use the default StorageClass to create backup PVCs without preparing an object storage when experiencing the playground.
The PR also adds a storageProvider named `pvc`, which is used to create a backupRepo based on PVC, for example:
```bash
kbcli backuprepo create --provider pvc \
--storage-class-name "standard" \
--access-mode "ReadWriteOnce" \
--volume-capacity "50Gi"
```
```bash
kubectl apply -f - <<-EOF
apiVersion: …
```
> feat: support PVC based backup repo

- controllers/apps/configuration/parallel_upgrade_policy.go
- controllers/apps/configuration/parallel_upgrade_policy_test.go
- controllers/apps/configuration/policy_util.go
- controllers/apps/configuration/rolling_upgrade_policy.go
- controllers/apps/configuration/simple_policy.go
- controllers/apps/configuration/sync_upgrade_policy.go
- controllers/apps/configuration/types.go
- internal/common/stateful_set_utils.go
Fix: [Reconfiguring processing progress status invalidation after after rsm integrated](https://github.com/apecloud/kubeblocks/issues/5141)
After rsm integrated, statefulset no longer has **_KBAppComponentLabelKey_** and **_AppInstanceLabelKey_** labels, and obtaining pods through **_commonent.GetPodListByStatefulSet_** will fail.
It may also affect other operator using this interface.
> fix: failed to get pods (#5141)

- internal/cli/cmd/kubeblocks/data/eks_hostpreflight.yaml
Preflight only supports aws China region (e.g. cn-northwest-1) now. Actually, it's fine to migrate kubeblocks to aws us region,
such as us-east-1.
> chore: preflight support aws us region

- deploy/openldap-cluster/templates/cluster.yaml
- deploy/openldap-cluster/values.yaml
- deploy/openldap/templates/clusterdefinition.yaml
Fix openldap VolumeExpansion ops failed
Modify the volumeClaimTemplates.name field of the cluster to be consistent with the volumeMounts[].name in ClusterDefinition
Close #5228
> fix: fix openldap VolumeExpansion ops failed

- deploy/polardbx-cluster/.helmignore
- deploy/polardbx-cluster/Chart.yaml
- deploy/polardbx-cluster/templates/NOTES.txt
- deploy/polardbx-cluster/templates/_helpers.tpl
- deploy/polardbx-cluster/templates/cluster.yaml
- deploy/polardbx-cluster/values.yaml
- deploy/polardbx/.helmignore
- deploy/polardbx/Chart.yaml
- deploy/polardbx/dashboards/polardbx-overview.json
- deploy/polardbx/scripts/gms-init.sql
- deploy/polardbx/scripts/gms-metadata.tpl
- deploy/polardbx/scripts/metadb-setup.tpl
- deploy/polardbx/scripts/xstore-post-start.tpl
- deploy/polardbx/scripts/xstore-setup.tpl
- deploy/polardbx/templates/NOTES.txt
- deploy/polardbx/templates/_helpers.tpl
- deploy/polardbx/templates/clusterDefintion.yaml
- deploy/polardbx/templates/clusterVersion.yaml
- deploy/polardbx/templates/configmap-dashboards.yaml
- deploy/polardbx/templates/scriptstemplate.yaml
- deploy/polardbx/values.yaml
- to #5244 
KubeBlocks is an interesting project that helps developers and platform engineers manage database workloads on K8s. [PolarDB-X](https://github.com/polardb/polardbx-sql) is an open-source, cloud native, distributed Database. In this PR, I have made the efforts to integrate PolarDB-X into KubeBlocks.
Functions implemented now:
* Create PolarDB-X cluster.
* Scale Up/Down of CN or CDC.
* Scale In/Out of CN or CDC.
* Stop or Restart PolarDB-X cluster.
* Metrics Export and Grafana/Prometheus Integration.
1. Install PolarDB-X cluster defination.
```
helm install polardbx ./deploy/polardbx
```
2. Create PolarDB-X Cluster. There are two options:
Opt1：Create PolarDB-X by kbcli:
```
kbcli cluster create pxc --cluster-definition polardbx
```
Opt2: Install polardbx-cluster helm chart, …
> feat: Integrate PolarDB-X into KubeBlocks.

- internal/cli/cmd/kubeblocks/upgrade.go
- internal/cli/cmd/kubeblocks/upgrade_test.go
- fix #5208 
**What cause：**
It caused by the double-check for Kubeblocks upgrade. When the kubeblocks version not change and only upgrade the --set values , we don't need to double check the version.
> fix: kbcli kubeblocks upgrade malformed version

- deploy/mongodb/values.yaml
- internal/controller/rsm/transformer_object_generation.go
- internal/controller/rsm/types.go
- lorry/binding/base.go
- lorry/binding/types.go
current role probe timeout is hard coded with value of 1s, which is not enough for some engines' role probe job.
this pr makes lorry role probe timeout configurable.
> chore: make lorry role probe timeout configurable

- apis/apps/v1alpha1/clusterdefinition_types.go
- config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
- deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
update outdate validation rule when `workloadType` is `Consensus`.
if `workloadType` is `Consensus`,  configuring one of `consensusSpec` or `rsmSpec` should both be ok.
> chore: workload type validation rules in CD

- controllers/apps/configuration/configuration_controller.go
- internal/controller/configuration/pipeline.go
fix: [create pulsar cluster failed and lead to kubeblocks CrashLoopBackOff](#5243)
> fix: SyncEnvConfigmap panic for configuration controller (#5243)

- controllers/apps/configuration/configuration_controller.go
- controllers/apps/configuration/configuration_controller_test.go
fix: [panic in configuration_controller.go](#5269)
> fix: component.BuildComponent painc when configuration.spec.ComponentName donot exist in the cluster.spec.componentSpecs

- controllers/apps/components/utils.go
- controllers/apps/configuration/config_related_helper.go
- internal/cli/cmd/builder/template/k8s_resource.go
- internal/generics/type.go
- internal/testutil/apps/common_util.go
Goland IDE 2023.2.1 and 2023.2.2 code inspector has a bug to infer generic pointer type like PObject and PObjList from Object and ObjectList, reported by those issues:
- https://youtrack.jetbrains.com/issue/GO-15335/Error-when-infer-generic-type-with-pointers
- https://youtrack.jetbrains.com/issue/GO-15306/False-error-when-using-pointer-method
- https://youtrack.jetbrains.com/issue/GO-15285/Incorrect-type-error-calling-a-generic-function-with-generic-interfaces-using-type-constraints
However, we don't know when this bug shall be fixed, to workaround this bug, we pass the pointer type that could be inferred to generic functions in signature explicitly.
> chore: workaround of goland code inspector bug which fails to infer generic pointer type

- internal/cli/cmd/plugin/types.go
the [block-index](https://github.com/apecloud/block-index) rename the dir `plugins` to `cli-plugins`. Therefore, the plugin cmd also need to check the cli-plugins dir.
> feat: cli plugin adapt the change of  block index repository

- internal/cli/util/version.go
> fix: supply the docker error info when playground init locally failed

- controllers/apps/configuration/configuration_controller.go
- controllers/apps/configuration/reconcile_task.go
related issue: https://github.com/apecloud/kubeblocks/issues/5224#issuecomment-1729802461
> chore: improved prompt message for configuration reconcile

- .github/workflows/milestone-set.yaml
- .github/workflows/milestoneclose.yml
1. Milestone is empty when issue/pr open and can be set manually.
2. If close issue/pr milestone is empty, set default milsestone.
3. When milsestone is closed, if issue/pr has a milestone, it will be moved to the next milestone. If not, it will remain empty.
ref: https://github.com/apecloud/apecloud-cd/pull/132/files
> chore: adjust milestone setting rules

- deploy/helm/templates/dataprotection.yaml
- deploy/helm/templates/deployment.yaml
The latest version of GKE has added snapshot validating webhook, which will be intercepted if created using v1beta1 version
> fix: create snapshot failed on GKE

- deploy/postgresql/templates/clusterversion.yaml
- deploy/postgresql/values.yaml
Pgvector v0.5.0 new feature:  HNSW
> chore: update postgresql image pgvector version to v0.5.0

- docs/user_docs/kubeblocks-for-mongodb/cluster-management/scale-for-apecloud-mongodb.md
> docs: fix typo in mongodb example doc

- docs/user_docs/cli/cli.md
- docs/user_docs/cli/kbcli_clusterdefinition_describe.md
- internal/cli/cmd/clusterdefinition/clusterdefinition.go
- internal/cli/cmd/clusterdefinition/describe.go
- internal/cli/types/types.go
> feat: add cd describe to show backup configuration

- apis/dataprotection/v1alpha1/backuppolicy_types.go
- config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
- config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
- config/crd/bases/dataprotection.kubeblocks.io_restores.yaml
- deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
- deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
- deploy/helm/crds/dataprotection.kubeblocks.io_restores.yaml
- internal/dataprotection/restore/builder.go
- internal/dataprotection/restore/manager.go
fix https://github.com/apecloud/kubeblocks/issues/5386
the host is the service dns for leader node, but we backup it on follower node.
> fix: mysql xtrabackup failed and restore failed

- deploy/csi-s3/templates/attacher.yaml
- deploy/csi-s3/templates/csi-s3.yaml
- deploy/csi-s3/templates/provisioner.yaml
- deploy/csi-s3/values.yaml
- deploy/helm/templates/addons/csi-s3-addon.yaml
The kubelet path in huawei cloud is changed to /mnt/paas/kubernetes/kubelet instead of /var/lib/kubelet. This causes csi-s3 stop working in huawei cloud.
This PR makes the kubelet path configurable, and adapts the value for huawei cloud.
> chore: make csi-s3 compatible with the huawei cloud

- deploy/orioledb/config/etcd-serve-config.tpl
- docs/user_docs/cli/kbcli_cluster_create.md
- internal/cli/cluster/helper.go
- internal/cli/cluster/helper_test.go
- internal/cli/cmd/cluster/create.go
- internal/cli/cmd/cluster/create_test.go
- internal/cli/testing/fake.go
- fix #5419 
Now orioledb cluters use the `serviceRefDeclarations` to reference tothe etcd service in order to meet the requirement of being able to use any etcd cluster as a dependency for their Patroni.
In this PR we support `kbcli cluster create --cluster-definition XX` to specify cluster service reference with flag `--service-reference`
Example:
Todo:
`--service-reference` we shuold specify the **serviceRef** name which be declared in cluster-definition. For users, it can be challenging to guess which serviceRefs are defined in a cluster-definition.
We **Next** will support `kbcli cluster list-serviceRef [cd-name] ` to list all  serviceRefs declared in a cluster-definition.
- More info see: https://github.com/apecloud/kubeblocks/pull/5237
> fix: orioledb create fail by `kbcli cluster create --cluster-definition`

- deploy/helm/templates/storageprovider/gcs-s3comp.yaml
Currently, the GCS storage provider is actually using the s3-compatible API instead of GCS's native API. So rename it to "gcs-s3comp" to make it more relevant.
> chore: rename the gcs storage provider to gcs-s3comp

- deploy/qdrant-cluster/templates/cluster.yaml
- deploy/qdrant/templates/clusterdefinition.yaml
Due to the previous npm project build during the cluster initialization process, Qdrant clusters would encounter OOM errors under the default memory settings. I have repackaged the image and conducted tests, moving the build step to the image building process.
> chore: fix qdrant cluster create OOM

- deploy/orioledb/templates/clusterdefinition.yaml
- fix #5489 
Adjust the service port name in cluster-definition of orioledb.
> fix: fix orioledb service port

- internal/controller/rsm/transformer_object_generation.go
- internal/controller/rsm/transformer_objection_generation_test.go
> fix: controller crash on nil service

- controllers/apps/operations/pipeline.go
- pkg/configuration/core/config_util.go
related issue: [[BUG] reconfiguring parameters labels not exist after refactoring the configuration module](#5517)
> fix: reconfiguring parameters labels not exist (#5517)

- apis/apps/v1alpha1/opsrequest_types.go
- config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
- controllers/apps/operations/backup.go
- deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
- pkg/cli/cmd/cluster/update.go
- pkg/dataprotection/utils/backup.go
> feat: opsrequest support more backup params

- deploy/jupyter-notebook/values.yaml
Rebuild Jupyter image and supply the default `docs-QA-assistantor.ipynb` deom in the `/work` directory.
> chore: supply AIGC demo in Jupyter addon

- deploy/jupyter-notebook/templates/deployment.yaml
- deploy/jupyter-notebook/values.yaml
- fix #5576 
In beta2 the jupyter version and some Python pip libraries have been updated. It causes error when run the demo.
And due to the PVC in jupyter-addon, the demo hasn't been mounted onto the deployment.
so i :
1. rebuild the beta2 image from version beta1.
2. add init-container.
> fix: new verision jupyter addon will can't load the demo

- deploy/nyancat/templates/clusterrole.yaml
Nyancat need clusters read privilege to get & list clusters by KubeBlocks clientset.
> chore: add clusters read privilege for nyancat

- docs/user_docs/cli/cli.md
- docs/user_docs/cli/kbcli_cluster_create.md
- docs/user_docs/cli/kbcli_clusterdefinition.md
- pkg/cli/cmd/cluster/create.go
- pkg/cli/cmd/clusterdefinition/clusterdefinition.go
- pkg/cli/cmd/clusterdefinition/list_service_reference.go
- pkg/cli/cmd/clusterdefinition/list_service_reference_test.go
- fix #https://github.com/apecloud/kubeblocks/issues/5475
Now kbcli support creating cluster with using a service reference with another cluster in KubeBlocks.
So we support kbcli cluster list-serviceRef [cd-name] to list all serviceRefs declared in a cluster-definition.
Example:
KBCLI seems to have a display bug with logs. I'm fixing it out.
> feat: kbcli support list-service-reference

- deploy/bytebase/templates/auto-plugin.yaml
- deploy/bytebase/templates/statefulset.yaml
- deploy/bytebase/values.yaml
- deploy/cert-manager/templates/cert-manager.yaml
- deploy/cert-manager/values.yaml
- deploy/csi-s3/manifest.yaml
- deploy/csi-s3/templates/_helpers.tpl
- deploy/csi-s3/templates/attacher.yaml
- deploy/csi-s3/templates/csi-s3.yaml
- deploy/csi-s3/templates/provisioner.yaml
- deploy/csi-s3/values.yaml
- deploy/neon-cluster/templates/vm-compute-node-deploy.yaml
- deploy/neon-cluster/values.yaml
- deploy/pulsar/templates/_helpers.tpl
- deploy/pulsar/templates/clusterdefinition-zookeeper.yaml
- deploy/pulsar/templates/clusterdefinition.yaml
- deploy/pulsar/values.yaml
- fix: #4915 
all of modifications  are tested by: 
`helm template --debug xxx `
for example:  pulsar.yaml
> chore: Separate the registry and repository of apecloud images in helm char

- deploy/orioledb/templates/scripts.yaml
- fix #5485 
Add the new logic for container restarting.
> fix: fix orioledb restart fail due to the invalid permissions

- controllers/apps/operations/stop.go
After stopping the cluster, deleting the configuration file causes reconstruction which can cause the cluster to start failed, due to incorrect configuration.
> fix: will rebuild configuration after stopping cluster

- deploy/risingwave/templates/clusterdefinition.yaml
> fix: risingwave connector crashloopbackoff on gke

- pkg/cli/util/breakingchange/upgradehandlerto0.7.go
- fix #5705
What i do:
Using `breakingChange` fix the incompatible upgrade.  
- Add the `web-ui` container, `web-ui` service port into the qdrant cluster definition 
- Add the `web-ui` container into the qdrant cluster version.
> fix: fix incompatible upgrade for qdrant from 0.6 to 0.7

- cmd/dataprotection/main.go
- controllers/dataprotection/backuprepo_controller.go
- controllers/dataprotection/backuprepo_controller_test.go
- controllers/dataprotection/suite_test.go
- controllers/dataprotection/types.go
- pkg/dataprotection/utils/events.go
- pkg/dataprotection/utils/utils.go
- pkg/testutil/dataprotection/backup_utils.go
Currently, if the user accidentally fills in a wrong configuration, such as an invalid access key, KubeBlocks can only discover this error when executing a backup task.
This PR adds a pre-check for BackupRepo, which can expose such configuration problems in advance. BackupRepo enters the `PreChecking` state as soon as it is created, and a job is started to try to access the storage corresponding to BackupRepo. If the access is successful, the status of BackupRepo is set to `Ready`; otherwise, the status is set to `Failed`, and the logs and events of the job are collected and saved for debugging.
If the remote storage is accessed based on CSI driver, a configuration error will cause the PVC to fail to provision, resulting in the job being always in a running state. To address this problem, …
> feat: pre-check the BackupRepo by running a real job

- pkg/cli/cmd/addon/addon.go
Now `kbcli addon list` outputs so many additional information including the **AUTO-INSTALLABLE-SELECTOR** and **EXTRAS** . Most addons do not have these properties, so I have moved them to `--output wide` to ensure that the `kbcli addon list` command remains concise.
**Notes**:
Furthermore, in the upcoming 0.8 release, there will be a **refactoring** based on the new definition of `addons`, keeping only the ones related to `cd/cv.` The work on kbcli will also align with these changes.
> chore: fix addon list output display

- controllers/dataprotection/backuprepo_controller.go
- docs/user_docs/cli/cli.md
- docs/user_docs/cli/kbcli_backuprepo.md
- docs/user_docs/cli/kbcli_backuprepo_update.md
- docs/user_docs/cli/kbcli_cluster_create_xinference.md
- docs/user_docs/cli/kbcli_login.md
- docs/user_docs/cli/kbcli_logout.md
- pkg/cli/cmd/backuprepo/backuprepo.go
- pkg/cli/cmd/backuprepo/common.go
- pkg/cli/cmd/backuprepo/create.go
- pkg/cli/cmd/backuprepo/describe.go
- pkg/cli/cmd/backuprepo/describe_test.go
- pkg/cli/cmd/backuprepo/list.go
- pkg/cli/cmd/backuprepo/list_test.go
- pkg/cli/cmd/backuprepo/update.go
- pkg/cli/cmd/backuprepo/update_test.go
- pkg/dataprotection/utils/utils.go
* Add update subcommand, which can be used to modify the storage authentication credentials, and also to make a backupRepo the global default repo (or vice versa)
* Enhance describe subcommand, to better show the reason for pre-check failure
* Add unit tests, to improve test coverage
> chore: enhance kbcli backuprepo cmds

- config/rbac/role.yaml
- controllers/workloads/replicatedstatemachine_controller.go
- deploy/helm/config/rbac/role.yaml
> fix: add statefulSet and deployment rbac

- pkg/lorry/engines/foxlake/commands.go
- pkg/lorry/engines/mongodb/commands.go
- pkg/lorry/engines/mysql/commands.go
- pkg/lorry/engines/nebula/commands.go
- pkg/lorry/engines/oceanbase/commands.go
- pkg/lorry/engines/postgres/commands.go
- pkg/lorry/engines/redis/commands.go
- pkg/lorry/engines/util.go
- fix #5855
The password needs to be enclosed in quotation marks because it may contain special characters such as '&'.
Test:
> fix: pg cluster connect fail

- README.md
Our readme file is not lengthy in itself. Additionally, there is a table of contents for the readme available by clicking on the top left corner in GitHub. Therefore, it isn't necessary to add a table of contents within the body of the readme.
> chore: remove the table of contents in the readme

- lorry/binding/base.go
- lorry/binding/utils.go
- lorry/dcs/dcs.go
- lorry/highavailability/ha.go
2023-11-30T10:34:30Z    ERROR   Mysql   send event failed       {"error": "client rate limiter Wait returned an error: context canceled"}
github.com/apecloud/kubeblocks/lorry/binding.sendEvent
/src/lorry/binding/utils.go:325
github.com/apecloud/kubeblocks/lorry/binding.SentProbeEvent
/src/lorry/binding/utils.go:241
github.com/apecloud/kubeblocks/lorry/binding.(*BaseOperations).CheckRoleOps
/src/lorry/binding/base.go:253
github.com/apecloud/kubeblocks/lorry/binding/mysql.(*MysqlOperations).Init.(*BaseOperations).RegisterOperationOnDBReady.StartupCheckWraper.func2
/src/lorry/binding/utils.go:338
github.com/apecloud/kubeblocks/lorry/binding.(*BaseOperations).Invoke
/src/lorry/binding/base.go:194
github.com/apecloud/kubeblocks/lorry/middleware/probe.route …
> fix: send event retry failed

- controllers/extensions/addon_controller_stages.go
- deploy/helm/templates/dataprotection.yaml
- deploy/helm/templates/deployment.yaml
* Add resource for init container of KB and DataProtection deployment
* Add resource for addon job, include initContainer and container
When install KubeBlocks, please set its resource to avoid set a zero resources.
```
helm template kb ./deploy/helm --output-dir temp --set resources.requests.cpu=100m,resources.requests.memory=128Mi,resources.limits.cpu=200m,resources.limits.memory=256Mi
```
```
##
resources: {}
```
> chore: set resource for kb init container and addon job

- go.mod
- go.sum
- pkg/configuration/core/config_patch_test.go
- pkg/controller/component/component_class_types_test.go
- pkg/controller/component/component_class_utils.go
The `github.com/ghodss/yaml` package is no longer actively maintained. There are numerous inquiries about the project's status on its issue tracker: https://github.com/ghodss/yaml/issues. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is currently maintained by Kubernetes SIG.
> chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

- deploy/helm/templates/_addon.tpl
- deploy/helm/templates/_helpers.tpl
- deploy/helm/templates/applications/alertmanager-webhook-adaptor-values.yaml
- deploy/helm/templates/applications/apecloud-otel-collector-values.yaml
- deploy/helm/templates/applications/grafana-values.yaml
- deploy/helm/templates/applications/prometheus-values.yaml
- deploy/helm/templates/applications/snapshot-controller-values.yaml
- deploy/helm/templates/dataprotection.yaml
- deploy/helm/values.yaml
- We provide a quick way to specify the image registry for **all resources** in the KubeBlocks Helm chart. 
Now, when installing KubeBlocks with `helm install kubeblocks`, you can quickly change the image registry for all resources by using `--set image.registry` like`--set image.registry=docker.io`
- here is the `helm template test deploy/helm  --set image.registry=docker.io > manifest.txt ` result
[manifest.txt](https://github.com/apecloud/kubeblocks/files/13612960/manifest.txt)
But there is an issue here: the addon files hardcode version information, making the installation of addons less flexible.
> chore: fix specify all resource image registry

- deploy/postgresql/config/pg12-config-constraint.cue
- deploy/postgresql/config/pg14-config-constraint.cue
https://github.com/apecloud/kubeblocks/issues/6100
add the 'wal_level' information in PG config-constrant
> fix: add the description of wal_level in the pg configconstrant file

- pkg/lorry/engines/opengauss/commands.go
> chore: fix cluster connect Database Env

- controllers/apps/transformer_cluster_deletion.go
> fix: cluster can't be deleted after KB upgraded from 0.6 to 0.7

- deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
> fix: use empty priorityClassName for csi-driver-nfs when in GKE

- pkg/controller/component/synthesize_component.go
fix: [[BUG] monitor collect incorrect metrics/logs for kb-0.8 #6219](https://github.com/apecloud/kubeblocks/issues/6219)
> fix: distinguish the componentdef on different addons (#6219)

- docker/Dockerfile
- docker/Dockerfile-dataprotection
- docker/Dockerfile-dev
- docker/Dockerfile-tools
1. KubeBlocks install ok
2. size is the same as base golang:1.21
> chore: change golang image to 1.21-alpine

- pkg/controller/component/affinity_utils.go
> fix: label selector for pod affinity and topology spread constraint

- pkg/controller/component/rsm_convertor.go
This reverts commit 7e6e0f6b6c159204558408141f33edc591362c9a.
> chore: Revert "fix: set default update strategy for RSM"

- apis/dataprotection/v1alpha1/backup_types.go
- apis/dataprotection/v1alpha1/backuppolicy_types.go
- config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
- config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
- controllers/dataprotection/backup_controller.go
- controllers/dataprotection/backup_controller_test.go
- deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
- deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
- deploy/helm/values.yaml
- pkg/dataprotection/backup/deleter.go
- pkg/dataprotection/backup/request.go
- pkg/dataprotection/backup/utils.go
- pkg/dataprotection/restore/builder.go
- pkg/dataprotection/restore/utils.go
- pkg/dataprotection/types/constant.go
- pkg/dataprotection/utils/backuprepo.go
Kopia has many advanced features such as content de-duplication, data compression, and encryption. If the data in the cluster is not frequently updated, using Kopia to back up data can reduce the amount of data that actually needs to be stored.
This PR introduces Kopia as the format for backup storage. Most of the code changes are done in `datasafed`. Users can enable this feature by setting `backupPolicy.spec.useKopia` to true. When this feature is enabled, the BackupController will inject the appropriate environment variables so that `datasafed` stores the data in the `Kopia Repository`.
Different Backups under the same cluster will store data in the same `Kopia Repository`. The actual path of the `Kopia Repository` on the storage backend is …
> feat: integrate with Kopia for database backup

- cmd/manager/main.go
fix https://github.com/apecloud/kubeblocks/issues/6449
```
opts := zap.Options{
Development: false,
}
opts.BindFlags(flag.CommandLine)
```
should be executed before
```
pflag.CommandLine.AddGoFlagSet(flag.CommandLine)
```
Otherwise, we will lost zap related flags.
> fix: zap flags not be added

- controllers/apps/transformer_component_workload.go
- pkg/lorry/dcs/types.go
- pkg/lorry/engines/mysql/get_replica_role.go
- pkg/lorry/engines/mysql/manager.go
- pkg/lorry/engines/mysql/manager_test.go
- pkg/lorry/engines/mysql/util.go
- pkg/lorry/engines/postgres/officalpostgres/manager.go
- pkg/lorry/highavailability/ha.go
- pkg/lorry/httpserver/server.go
- pkg/lorry/operations/replica/checkrole.go
- pkg/lorry/operations/volume/protect.go
- pkg/lorry/operations/volume/protect_test.go
1. Use a shorter addr, limit the length of addr, for versions below 8.0.17 the limit is 60, new versions limit it to 255. If the length exceeds the limit, the cluster will not be initialized.
2. During failover, if the delay is greater than 10s, the switch will not be executed, it will wait for the primary to recover by itself.
> fix: mysql replication initialization and  failover

- cmd/manager/main.go
fix #6477 
```
ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))
```
should be executed after `pflag.Parse()`, otherwise the value of `--zap-log-level` won't take effect.
> fix: --zap-log-level not take effect

- .github/workflows/cicd-push.yml
fix https://github.com/apecloud/kubeblocks/actions/runs/7582113857/job/20651040139
> chore: skip check zh-cn dir

- pkg/lorry/engines/mysql/get_replica_role.go
- pkg/lorry/engines/mysql/get_replica_role_test.go
- pkg/lorry/engines/mysql/manager.go
- pkg/lorry/engines/mysql/manager_test.go
- pkg/lorry/engines/mysql/semei_sync_test.go
- pkg/lorry/engines/mysql/semi_sync.go
- Disable semi-sync at startup
- Enable semi-source and disable semi-replica when promoting to primary
- Disable semi-source and enable semi-replica when following a primary
- Reset primary semi-source timeout to the maximum when secondary successfully follows
> chore: refine mysql semisync

- controllers/dataprotection/restore_controller.go
> fix: use restore.Spec.ServiceAccountName if not empty

- apis/apps/v1alpha1/configconstraint_types.go
- apis/apps/v1alpha1/type.go
- apis/apps/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
- controllers/apps/configuration/combine_upgrade_policy.go
- controllers/apps/configuration/combine_upgrade_policy_test.go
- controllers/apps/configuration/reconfigure_policy.go
- controllers/apps/configuration/sync_upgrade_policy.go
- deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
- docs/developer_docs/api-reference/cluster.md
- pkg/configuration/core/reconfigure_util.go
- pkg/configuration/core/reconfigure_util_test.go
Bug: [[BUG] support dynamic and static parameters updates for partoni in one reconfiguring](https://github.com/apecloud/kubeblocks/issues/5450)
> fix: dynamic parameters and static parameters are modified together for partoni postgresql, and the dynamic parameters do not take effect (#5450)

- .github/workflows/cicd-push.yml
- .github/workflows/release-helm-chart.yml
- .github/workflows/release-version.yml
1. release ent addons chart when release kubeblocks
2. only check apis doc change when push
3. auto update apis doc changes when release
> chore: release ent addons chart

- apis/apps/v1alpha1/opsrequest_types.go
- apis/apps/v1alpha1/opsrequest_webhook.go
- config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
- controllers/apps/operations/expose.go
- controllers/apps/operations/expose_test.go
- deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
- pkg/lorry/engines/dbmanager_mock.go
> fix: expose with empty componentName

- apis/dataprotection/v1alpha1/backup_types.go
- apis/dataprotection/v1alpha1/backuppolicy_types.go
- apis/dataprotection/v1alpha1/types.go
- config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
- config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
- controllers/dataprotection/backup_controller.go
- controllers/dataprotection/backup_controller_test.go
- controllers/dataprotection/utils.go
- deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
- deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
- deploy/helm/values.yaml
- docs/developer_docs/api-reference/backup.md
- pkg/dataprotection/backup/deleter.go
- pkg/dataprotection/backup/request.go
- pkg/dataprotection/restore/builder.go
- pkg/dataprotection/types/constant.go
- pkg/dataprotection/utils/backuprepo.go
This PR integrates data encryption functionality from datasafed. Backup data is encrypted before being written to storage. Currently, the supported encryption algorithms are `AES-128-CFB`, `AES-192-CFB`, and `AES-256-CFB`. In the future, additional algorithms can be supported based on requirements.
Usage instructions:
1. Create a Secret to store the encryption key:
```bash
kubectl create secret generic backup-encryption \
--from-literal=secretKey='your secret key'
```
2. Patch the backupPolicy to enable encryption. Reference the previously created key here:
```bash
kubectl --type merge patch backuppolicy mysqlcluster-mysql-backup-policy \
-p '{"spec":{"encryptionConfig":{"algorithm":"AES-256-CFB","passPhraseSecretKeyRef":{"name":"backup-encryption","key":"secretKey"}}}}'
```
3. …
> feat: support encryption for backup data

- controllers/apps/operations/reconfigure_util.go
- pkg/configuration/core/config_util.go
1.  [[BUG] camellia cluster config error metadata.labels Invalid value must be no more than 63 characters #6746](https://github.com/apecloud/kubeblocks/issues/6746)
2. [[BUG] ob reconfigure invalid error: metadata.labels: Invalid value: "__easy_memory_reserved_percentage" #6765](https://github.com/apecloud/kubeblocks/issues/6765)
> fix: failed to reconrigure operation (#674)

- controllers/apps/operations/restore.go
> fix: restore cluster failed if exists node port service

- cmd/manager/main.go
- controllers/apps/cluster_controller.go
- controllers/apps/component_controller.go
- deploy/helm/templates/deployment.yaml
- deploy/helm/values.yaml
- pkg/constant/const.go
if the clusters number over than 1000,  RT response is slow. 
for example, it takes 2 minutes or more minutes to start creating pods when creating a cluster.
> chore: add reconcile workers for cluster and component controller.

- controllers/apps/operations/expose.go
> fix: expose role from rsmSpec

- controllers/workloads/replicatedstatemachine_controller.go
> fix: cluster is always in 'DeleteCR' after deleted

- controllers/apps/transformer_component_deletion.go
- controllers/apps/transformer_component_ownership.go
- controllers/workloads/replicatedstatemachine_controller.go
- pkg/controller/rsm2/reconciler_deletion.go
- pkg/controller/rsm2/replica_util.go
> fix: cluster is always in 'Deleting' after volume expansion

- Makefile
- hack/license/header-check.sh
This PR is to fix #6457 @shanshanying Could you please help review this PR? Thx in advance.
> fix: update excluded directories in header-check script

- pkg/controller/rsm/update_plan.go
> fix: Serial UpdateStrategy not working without roles

- apis/dataprotection/v1alpha1/types.go
- controllers/apps/transformer_cluster_backup_policy.go
- deploy/helm/templates/_dataprotection.tpl
- deploy/helm/templates/dataprotection.yaml
- deploy/helm/templates/deployment.yaml
- deploy/helm/values.yaml
- pkg/constant/const.go
As described in #7103, sometimes we would like to reference a pre-defined secret instead of setting `dataProtection.encryptionKey`. This PR allows users to do so.
Assuming there is a pre-defined secret named `dp-encryption-key` and a key `encryptionKey` inside it. For example, a secret created by this command:
```bash
kubectl create secret generic dp-encryption-key \
--from-literal=encryptionKey='S!B\*d$zDsb='
```
And then reference it when installing or upgrading KubeBlocks:
```bash
kbcli kubeblocks install \
--set dataProtection.encryptionKeySecretKeyRef.name="dp-encryption-key" \
--set dataProtection.encryptionKeySecretKeyRef.key="encryptionKey"
```
By default, the `encrytpionKey` is only used for encrypting the connection password, if you want to use it to encrypt backup data as well, …
> feat: support referencing pre-defined secret as encryptionKey

- controllers/dataprotection/backup_controller.go
- controllers/dataprotection/backup_controller_test.go
constrain continuous backup created via backupschedule to limit at most one pitr workload
> fix: check if continuous backup was created via backupschedule

- deploy/helm/templates/dataprotection.yaml
- deploy/helm/templates/deployment.yaml
- deploy/helm/templates/service.yaml
> fix: exclude data-protection pods from kb service

- apis/apps/v1alpha1/cluster_webhook.go
- apis/apps/v1alpha1/cluster_webhook_test.go
> fix: remove the validation for cluster comp spec in webhook

- controllers/apps/transformer_cluster_component.go
When using new API's topology order, cluster reconciliation transformer will be prematurely stopped due to the error produced in clusterComponentTransformer. Thus causing problems like cluster status' `observedGeneration` not updated.
So I think delaying this error will be appropriate.
> chore: cluster reconciliation premature stop

- controllers/apps/transformer_cluster_component.go
fix a duplicated import introduced in #7277
> chore: remove duplicated import

- deploy/helm/templates/dataprotection.yaml
- deploy/helm/templates/deployment.yaml
- deploy/helm/templates/service.yaml
This reverts commit 37a288d6762d2280208fee8106c3e72a73ea4a1f.
fix https://github.com/apecloud/kubeblocks/issues/7250
> Revert "fix: exclude data-protection pods from kb service (#7239)"

- deploy/helm/templates/dataprotection.yaml
- deploy/helm/templates/deployment.yaml
- deploy/helm/values.yaml
- fix #7353 
and here is an example of values to deploy KB with 3 replicas, and specify extraLables, affinity and antiaffinity for KB and DP respectively.
```bash
helm -n kb-system upgrade -i kubeblocks  ./deploy/helm -f values.yaml --create-namespace
```
and the `values.yaml` file contains following values:
```yaml
replicaCount: 3
image:
tag: 0.8.3-beta.19
extraLables:
app.kubernetes.io/component: "kubeblocks"
tolerations:
- key: kb-controller
operator: Equal
value: "true"
effect: NoSchedule
affinity:
nodeAffinity:
preferredDuringSchedulingIgnoredDuringExecution:
- weight: 100
preference:
matchExpressions:
- key: kb-controller
operator: In
values:
- "true"
podAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector:
matchLabels:
app.kubernetes.io/instance: kubeblocks …
```
> fix: add labels to distinguish kb and dataprotection

- pkg/lorry/engines/models/replca_role_types.go
- pkg/lorry/engines/redis/get_replica_role.go
- pkg/lorry/engines/redis/manager.go
- pkg/lorry/operations/replica/checkrole.go
Fix cloud issue 3797.
When the primary oceanbase replica's node is down,  the status of Pod becoms "Terminating".
```
root@yjtest-1:/data/kubeblocks# k get pod | grep maize59
399fa706-maize59-ob-bundle-0-b-archive-log-0                      2/2     Running       0          41m
maize59-ob-bundle-0-0                                             4/4     Running       0          108m
maize59-ob-bundle-1-0                                             4/4     Terminating   0          108m
```
After a while, the new primary is elected, however both Pods're labelled with primary role.
This will affect the rebuilding of the secondary database because currently, the target componentName for rebuilding the secondary database needs to be a non-primary role.
> fix: both replicas in a OceanBase Cluster have the primary role assigned

- controllers/dataprotection/log_collection_controller.go
log collection controller will collect logs and patch the status when the job failed,  this operation may overwrite the later modified status.
> chore: restore action phase is incorrect when the job is failed

- controllers/apps/component_controller_test.go
- controllers/apps/operations/rebuild_instance.go
- pkg/controller/instanceset/reconciler_status.go
- pkg/controllerutil/pod_utils.go
- pkg/dataprotection/action/action_stateful.go
When the pod scheduling fails, due to the self-healing property of k8s, it can be automatically repaired without manual intervention, and showing `pending` status is also reasonable for instance.
> chore: remove scheduling judgments when determining whether pod is Failed

- docs/cli_docs/kubeblocks-for-redis/configuration/configuration.md
There was an error in displaying the Redis cluster configuration in the CLI docs. The parameter "--component" does not exist, but it can be configured successfully with "--components". The corresponding document has been modified.
> docs: fix docs errors

- deploy/helm/templates/deployment.yaml
resolve https://github.com/apecloud/kubeblocks/issues/7545
> fix: default function cause value always be true

- controllers/apps/operations/rebuild_instance.go
when node is down, pod will always deleting due to the kubelet is down. in this case,  users can delete node or force delete pod
> chore: force delete target pod during rebuilding instance when spec.force is true

- controllers/apps/operations/ops_manager.go
- controllers/apps/operations/ops_util_test.go
- controllers/apps/opsrequest_controller.go
- controllers/apps/opsrequest_controller_test.go
- pkg/constant/annotations.go
Sometimes, due to the asynchronous nature of coordination, even if multiple opsRequests are created in sequence, the final execution order may still be inconsistent. To ensure order, add  annotation  `ops.kubeblocks.io/dependent-on-successful-ops ` to solve this problem.
> chore: support to run a opsRequest after the dependent opsRequests are succeed.

- pkg/controller/component/action_utils.go
fix: https://github.com/apecloud/kubeblocks-addons/issues/666
> chore: lifecycleAction jobSpec set default template pod serviceAccountName

- controllers/apps/component_controller_test.go
- controllers/apps/componentdefinition_controller.go
- controllers/apps/componentdefinition_controller_test.go
- pkg/constant/annotations.go
- pkg/testutil/apps/componentdefinition_factory.go
> feat: cmpd immutable check as default

- pkg/controller/component/synthesize_component.go
- pkg/controller/component/type.go
fix enterprise repo bug: 5124 and 5288
Log-related configuration rendering depends on this field enabledLogs.
> fix: mysql/wesql has no slow log (#7823)

- pkg/common/monitor.go
- pkg/common/monitor_test.go
The capture execution process of prometheus is as follows: 
1. Obtain Endpoints and Generate Service List:
```
for ip in addresses
for port in ports; 
services = append(services, ip:port)
```
2. Address Conversion Based on Relabeling Strategy:
```
- source_labels: [__address__, __meta_kubernetes_service_annotation_monitor_kubeblocks_io_port] 
action: replace target_label: __address__ 
regex: (.+?)(?::\d+)?;(\d+) 
replacement: $1:$2 
```
3. Deduplicate Services After Transformation
If the relabeling step fails, it will be bypassed, causing the deduplication logic to be invalid, and as a result, all ports will be scraped.
> chore: adjust port name to number port (#7804)

- docs/api_docs/maintenance/scale/scale-for-specified-instance.md
This PR fixes the error in the document `docs/api_docs/maintenance/scale/scale-for-specified-instance.md`.
The issue is described at https://github.com/apecloud/kubeblocks/issues/7862
> fix: using right doc to offline instance(#7862)

- controllers/apps/componentdefinition_controller.go
Remove the reference to the monitor field in the cmpdHash function, and also fix the staticcheck failure introduced by the https://github.com/apecloud/kubeblocks/pull/7766.
> chore: remove monitor from cmpdHash function

- controllers/apps/transformer_component_workload.go
fix a bug in https://github.com/apecloud/kubeblocks/pull/7743. It is about PodUpdatePolicy field cannot be synchronized from component to instanceSet.
> fix: PodUpdatePolicy field cannot be synchronized from component to instanceSet

- pkg/controller/instanceset/utils.go
- pkg/controller/instanceset/utils_test.go
resolve https://github.com/apecloud/kubeblocks/issues/7893
> fix: avoid concurrency is 0

- docs/user_docs/maintenance/_category_.yaml
All other labels are in "Title case".
> docs: Align case for Maintenance label

- .github/workflows/release-helm-chart.yml
Keep consistent with https://github.com/apecloud/kubeblocks-addons/pull/962
> chore: upgrade release addon workflow version

- controllers/apps/transformer_cluster_service.go
- pkg/kbagent/proto/proto.go
- pkg/kbagent/service/action.go
- pkg/kbagent/service/action_test.go
- pkg/kbagent/service/command.go
- pkg/kbagent/service/command_test.go
- pkg/kbagent/service/probe_test.go
- pkg/kbagent/service/service_test.go
- pkg/kbagent/service/suite_test.go
There are still some bugs in the kb-agent server.
1. When a timeout command is set, sometimes it cannot be started due to the cancellation function being executed in advance.
2. Unable to respond when using non-blocking mode to request the results of an ongoing action multiple times
3. Concurrency problems may occur in the operation of runningActions map, in the second point above.
> chore: incorrect responses of kbagent under different request situations

- deploy/helm/templates/applications/apecloud-otel-collector-addon.yaml
- deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
- deploy/helm/templates/applications/grafana-addon.yaml
- deploy/helm/templates/applications/loki-addon.yaml
* fix https://github.com/apecloud/kubeblocks/issues/8019
Test:
```shell
$ helm template kubeblocks ./helm |kubectl apply -f - --server-side=true --dry-run=server
serviceaccount/kubeblocks serverside-applied (server dry run)
serviceaccount/kubeblocks-addon-installer serverside-applied (server dry run)
serviceaccount/kubeblocks-dataprotection-exec-worker serverside-applied (server dry run)
secret/kubeblocks-secret serverside-applied (server dry run)
configmap/alertmanager-webhook-adaptor-chart-kubeblocks-values serverside-applied (server dry run)
configmap/apecloud-otel-collector-chart-kubeblocks-values serverside-applied (server dry run)
configmap/aws-load-balancer-controller-chart-kubeblocks-values serverside-applied (server dry run)
configmap/csi-hostpath-driver-chart-kubeblocks-values …
```
> chore: fix helm invalid null values

- pkg/controller/component/rsm_convertor.go
- pkg/controller/instanceset/utils.go
bug fix for https://github.com/apecloud/kubeblocks/pull/7978
1. fix the conversion process of the `MemberUpdateStrategy`.
2. fix the logic for checking if `UpdatedReplicas` are ready during a canary upgrade.
> fix: updateStrategy bug

- apis/apps/v1alpha1/backuppolicytemplate_types.go
- config/crd/bases/apps.kubeblocks.io_backuppolicytemplates.yaml
- controllers/apps/transformer_cluster_backup_policy.go
- deploy/helm/crds/apps.kubeblocks.io_backuppolicytemplates.yaml
- docs/developer_docs/api-reference/cluster.md
mongodb addon uses a common componentDefinition with different service version, and bpt not supports to mapping the env value to replace image tag with service version.
> fix: mongo dump backup failed with incorrect version

- pkg/kbagent/service/command.go
- Fix the situation of "**：failed**" caused by exitError and empty []byte obtained in stdErrChan.
- Add exit error code prompt information for easy debugging.
> chore: add exit error code prompt information

- Makefile
- cmd/helmhook/hook/prepare.go
- cmd/helmhook/hook/stop.go
- cmd/helmhook/hook/utils.go
- deploy/helm/templates/dataprotection.yaml
- deploy/helm/templates/deployment.yaml
- deploy/helm/templates/service.yaml
* fix https://github.com/apecloud/kubeblocks/issues/8091
As follow:
* KubeBlocks and DataProtection deployment use different pod labels
* The KubeBlocks Service only select the KubeBlocks pods
* Delete the deployment when upgrade to avoid the error like https://github.com/apecloud/kubeblocks/issues/7250
> fix: exclude dataprotection pods from kb service

- pkg/kbagent/service/command.go
The following images show the order of `req.Parameters` and `os.Environ` in `cmd.Env`, which may cause the env in the action to be overwritten by environment variables with the same name.
> chore: adjust environment variable append order 

- apis/apps/v1alpha1/opsrequest_types.go
- config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
- controllers/apps/operations/rebuild_instance.go
- controllers/apps/operations/rebuild_instance_inplace.go
- controllers/apps/operations/rebuild_instance_test.go
- deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
- docs/developer_docs/api-reference/cluster.md
- pkg/constant/annotations.go
- pkg/controller/instanceset/instance_util.go
- pkg/controller/instanceset/instance_util_test.go
- pkg/controller/instanceset/reconciler_instance_alignment_test.go
- pkg/controller/instanceset/reconciler_status.go
- pkg/controller/instanceset/reconciler_status_test.go
cherry-picked from 87e27f501d552d196f59bf1c9fe6f178baa07a86
> feat: specify node for rebuild instance ops

- apis/apps/v1alpha1/clusterversion_webhook.go
- apis/apps/v1alpha1/clusterversion_webhook_test.go
- deploy/helm/templates/rbac/clusterrole_binding.yaml
> chore: remove CV update validation

- pkg/constant/labels.go
- pkg/controller/instanceset/object_builder.go
(cherry picked from commit b019f2c8c29b43cbeb601ebe0100ff78e98081a6)
> chore: pick update headless svc labels for the prometheus scrape job to release-0.9 (#8088)

- pkg/controller/instanceset/instance_template_util.go
merge the capability from https://github.com/apecloud/kubeblocks/pull/8193 into release-0.9.
> feat: add BuildInstanceName2TemplateMap public api

- controllers/apps/componentdefinition_controller.go
- controllers/apps/configuration/config_util.go
- fix https://github.com/apecloud/kubeblocks/issues/8145
> fix: config-related resource cannot be cleaned up after disable addons

- apis/apps/v1alpha1/clusterdefinition_types.go
- config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
- deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
> chore: set clusterdefinition.componentDefs default to empty list

- apis/extensions/v1alpha1/addon_types_test.go
- apis/extensions/v1alpha1/type.go
- controllers/extensions/addon_controller_test.go
- pkg/testutil/type.go
resolve #7551 
The dependent pkgs defined by KB:
- github.com/apecloud/kubeblocks/apis/apps/v1
- github.com/apecloud/kubeblocks/apis/apps/v1alpha1
- github.com/apecloud/kubeblocks/apis/apps/v1beta1
- github.com/apecloud/kubeblocks/apis/dataprotection/v1alpha1
- github.com/apecloud/kubeblocks/apis/workloads/v1
- github.com/apecloud/kubeblocks/apis/workloads/v1alpha1
- github.com/apecloud/kubeblocks/pkg/constant
- github.com/apecloud/kubeblocks/pkg/viperx
> chore: cleanup the APIs pkg deps and keep them compact

- go.mod
- go.sum
- test/testutils/helm.go
- test/testutils/utils.go
PR #8236 aimed to upgrade github.com/containers/common, but due to a significant version gap, it couldn't be merged directly. This PR removes the dependency on this package.
Closes #8236.
> chore: remove dependency on github.com/containers/common

- cmd/helmhook/hook/crd.go
- pkg/common/env_resolve.go
- pkg/controller/instanceset/instance_util_test.go
- pkg/controller/instanceset/reconciler_instance_alignment.go
- pkg/controller/instanceset/reconciler_update.go
> chore: use generic sets instead of the deprecated one

- controllers/dataprotection/log_collection_controller_test.go
https://github.com/apecloud/kubeblocks/actions/runs/11267044653/job/31335064912?pr=8251
```
[FAILED] Timed out after 10.001s.
The function passed to Eventually failed at /home/runner/work/kubeblocks/kubeblocks/controllers/dataprotection/log_collection_controller_test.go:126 with:
Expected
<string>: there are failed actions, you can obtain the more informations in the status.actions
to be empty
In [It] at: /home/runner/work/kubeblocks/kubeblocks/controllers/dataprotection/log_collection_controller_test.go:127 @ 10/10/24 06:13:46.238
```
> chore: fix a test case in log_collection_controller_test.go

- pkg/controller/scheduling/scheduling_utils.go
- pkg/controller/scheduling/scheduling_utils_test.go
- pkg/testutil/apps/cluster_factory.go
cherry-pick f8cc2d1444790a70558f3fdeb6b049badcceaa1e to 0.9
> fix: endless affinity list when there's a DataPlaneAffinity

- deploy/helm/templates/_dataprotection.tpl
- deploy/helm/values.yaml
As mentioned in #7103, it would be helpful to be able to skip the lookup of an externally-deployed Secret for the dataProtectionEncryptionKey, in order to be able to deploy this helm chart via tools that template it out without access to the cluster (such as argo-cd). 
Defaults to the current behaviour of performing the lookup.
> feat: toggle to disable helm render-time validation of encryptionKeySecretKeyRef

- pkg/controller/plan/tls_utils.go
- pkg/controller/plan/tls_utils_test.go
> fix: check data field for user provided tls

- controllers/apps/clusterdefinition_controller.go
> fix: don't delete config resources while deleting the cluster definition CRs

- pkg/controller/instanceset/object_builder.go
- pkg/controller/instanceset/object_builder_test.go
> fix: port names of the headless service are conflict

- controllers/dataprotection/storageprovider_controller_test.go
- pkg/testutil/apps/common_util.go
https://github.com/apecloud/kubeblocks/actions/runs/11622958513/job/32369246442
```
[FAILED] Unexpected error:
<*errors.StatusError | 0xc0029db0e0>: 
Operation cannot be fulfilled on storageproviders.dataprotection.kubeblocks.io "storageprovider-6jdjq": the object has been modified; please apply your changes to the latest version and try again
{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Operation cannot be fulfilled on storageproviders.dataprotection.kubeblocks.io \"storageprovider-6jdjq\": the object has been modified; please apply your changes to the latest version and try again",
Reason: "Conflict",
Details: {
Name: "storageprovider-6jdjq",
Group: …
```
> chore: fix unstable UT in storageprovider_controller_test.go

- controllers/apps/transformer_cluster_backup_policy.go
align pitr backup retention with cluster retentionPeriod in backup schedule
> fix: align pitr backup retention with cluster retentionPeriod

- controllers/apps/transformer_component_workload.go
- controllers/apps/transformer_component_workload_test.go
> fix: the component controller is not notified when a backup for h-scale becomes ready

- apis/operations/v1alpha1/opsrequest_validation.go
- pkg/constant/ops.go
- pkg/operations/horizontal_scaling.go
- pkg/operations/horizontal_scaling_test.go
- pkg/operations/ops_progress_util_test.go
- pkg/operations/ops_util_test.go
> feat: support validate policy of opsrequest

- controllers/apps/transformer_component_status.go
> chore: ensure the observedGeneration and phase of the component remain consistent

- apis/apps/v1/cluster_types.go
- apis/apps/v1/component_types.go
- config/crd/bases/apps.kubeblocks.io_clusters.yaml
- config/crd/bases/apps.kubeblocks.io_components.yaml
- controllers/apps/transformer_component_service.go
- deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
- deploy/helm/crds/apps.kubeblocks.io_components.yaml
- docs/developer_docs/api-reference/cluster.md
- pkg/controller/component/synthesize_component.go
> chore: reconcile to preserve the default service type

- controllers/apps/cluster_controller_test.go
- pkg/controllerutil/cluster_utils_test.go
- pkg/controllerutil/sharding_utils_test.go
Today I've encountered a very weird [test fail](https://github.com/apecloud/kubeblocks/actions/runs/11773368367/job/32790184670) (also [this](https://github.com/apecloud/kubeblocks/actions/runs/11832473840/job/32969749420) run).
<details><summary>log</summary>
<p>
```bash
• [PANICKED] [0.874 seconds]
Cluster Controller [AfterEach] cluster status test cluster conditions when cluster definition non-exist
[AfterEach] /home/runner/work/kubeblocks/kubeblocks/controllers/apps/cluster_controller_test.go:123
[It] /home/runner/work/kubeblocks/kubeblocks/controllers/apps/cluster_controller_test.go:929
Timeline >>
STEP: clean resources @ 11/11/24 06:36:09.526
STEP: clear resources Cluster @ 11/11/24 06:36:09.526
STEP: clear resources ClusterDefinition @ 11/11/24 06:36:09.529
STEP: clear resources …
```
> chore: fix a flaky test

- pkg/controller/instanceset/instance_util.go
- pkg/controller/instanceset/instance_util_test.go
cherry-picked from commit fe24a3a4d
> chore: update the pod image that does not have a registry and repository specified

- apis/dataprotection/v1alpha1/actionset_types.go
- config/crd/bases/dataprotection.kubeblocks.io_actionsets.yaml
- deploy/helm/crds/dataprotection.kubeblocks.io_actionsets.yaml
- docs/developer_docs/api-reference/backup.md
- pkg/dataprotection/backup/request.go
- pkg/dataprotection/restore/utils.go
- pkg/testutil/dataprotection/utils.go
fix https://github.com/apecloud/kubeblocks/issues/8475
ref https://github.com/apecloud/kubeblocks/pull/8472
> fix: add Selective backupType

- controllers/apps/transformer_cluster_status.go
happened when creating multi components in order
> fix: cluster phase are empty in a long time

- pkg/dataprotection/restore/builder.go
> fix: DP_DB_HOST env is missing

- pkg/controller/component/component_version.go
- pkg/controller/component/component_version_test.go
cherry picked from commit 4ed1cf4ddc6ec59995efa2dcd89e843205c74fff
> chore: prioritize exact match for service version

- apis/apps/v1/componentdefinition_types.go
- config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
- deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
- docs/developer_docs/api-reference/cluster.md
> fix: the decimal value of the default mount mode for TLS secrets

- apis/apps/v1alpha1/opsrequest_webhook.go
- controllers/apps/operations/reconfigure.go
> fix: sharding reconfigure

- controllers/k8score/event_controller_test.go
- pkg/controller/instanceset/pod_role_event_handler.go
> fix: update role label failed when switchover

- pkg/lorry/engines/redis/get_replica_role.go
- pkg/lorry/engines/redis/manager.go
- pkg/lorry/engines/redis/redis.go
> fix: redis get role overtime

- controllers/apps/transformer_cluster_component.go
- controllers/apps/transformer_cluster_component_test.go
- pkg/constant/flag.go
> feat: support to set the pod anti-affinity for a shard

- controllers/apps/cluster_controller_test.go
- controllers/apps/transformer_component_workload.go
configuration controller will annotate the instanceSet.spec.template
> fix: vscale ops is always running when need to rerender configuration

- controllers/apps/transformer_component_workload.go
> fix: check lifecycle actions to avoid NPE when calling actions during scale-in

- pkg/controller/component/workload_utils.go
> fix: instance template's name having dash leads to error. (#8773)

- controllers/apps/transformer_cluster_service.go
> fix: NPE when adding a new service port

- controllers/apps/transformer_cluster_backup_policy.go
- controllers/dataprotection/backup_controller_test.go
- controllers/dataprotection/utils.go
- deploy/helm/templates/rbac/clusterrole.yaml
- pkg/dataprotection/backup/scheduler.go
ref https://github.com/apecloud/kubeblocks/pull/8813
> chore: incremental backup cronJob

- config/rbac/role.yaml
- controllers/apps/component/component_controller.go
- deploy/helm/config/rbac/role.yaml
- deploy/helm/templates/rbac/rbac_manager_role.yaml
- deploy/helm/values.yaml
fixes https://github.com/apecloud/kubeblocks/issues/8847, tested locally.
> fix: add missing rbac

- deploy/helm/templates/storageprovider/s3-compatible.yaml
> chore: add s3-compatible StorageProvider

- docs/user_docs/installation/install-kubeblocks.md
- i18n/zh-cn/user-docs/installation/install-kubeblocks.md
When I was reading the documentation, I was confused about the content related to version acquisition and installation of crds.
The **"vx.y.z"** used here is easily ignored, resulting in instruction execution errors.
This PR updates the KB installation documentation to provide clearer guidance on version selection and installation steps. Main changes include:
- Add explicit version selection options:
- Option A: Get latest stable version with curl command
- Option B: View all versions (including alpha/beta) via GitHub releases or curl
- Provide concrete examples using v0.9.2 to demonstrate proper version usage
These changes aim to:
- Make the installation process more intuitive for new users
- Reduce potential version mismatch issues
- Maintain consistency between English and Chinese …
> chore: update kb install guide

- pkg/controller/plan/restore.go
- pkg/operations/restore.go
- pkg/operations/restore_test.go
1. Fix the issue where the wrong role is selected during the postReady phase when restoring a cluster.
2. Fix the problem of pods remaining in a pending state during cluster restoration, especially if the backed-up cluster had pod anti-affinity policies in place.
> fix: restore mysql failed

- apis/apps/v1/cluster_types.go
- config/crd/bases/apps.kubeblocks.io_clusters.yaml
- deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
> fix: validate the topology as immutable

- apis/apps/v1alpha1/cluster_types.go
- config/crd/bases/apps.kubeblocks.io_clusters.yaml
- deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
Hello, 
When playing with Kubeblock, I wanted to add a custom configMap to my Cluster using `userResourceRefs` it fails when I try to use a mountPoint with 2 directories. 
Right now, the mountPoint option do not allow having a full path in the field with this error
```
spec.componentSpecs[0].userResourceRefs.configMapRefs[0].mountPoint in body should match '^/[a-z]([a-z0-9\-]*[a-z0-9])?$'
```
I'm not sure why it seemed to work [when implementing the feature](https://github.com/apecloud/kubeblocks/pull/5442). 
On my end using a configuration like that it exits with the previous error. 
```
componentSpecs:
- componentDefRef: mysql
....
userResourceRefs:
secretRefs:
name: my-secret-volume
mountPoint: /ops/config
asVolumeFrom: 
- mysql
secret:
SecretName:  my-secret
configMapRefs:
name: …
```
> fix: remove the pattern validation for ResourceMeta.MountPoint

- controllers/apps/cluster/transformer_cluster_sharding_account.go
- controllers/apps/component/transformer_component_account.go
- pkg/common/password.go
- pkg/common/password_test.go
fix #8837 
Problem: Mixed-case password doesn't guarantee having both uppercase and lowercase.
Fix: Introduce EnsureMixedCase() post-processor to guarantee at least one uppercase and one lowercase.
Testing: Verified consistent generation with same seed, plus enforced mixed-case distribution.
> fix: ensure GeneratePassword returns password with mixed cases

- controllers/apps/transformer_cluster_shared_account.go
- controllers/apps/transformer_component_account.go
- pkg/common/password.go
- pkg/common/password_test.go
- pkg/controller/factory/builder.go
- pkg/testutil/apps/cluster_util.go
fix #8837
cherry-pick [commit](https://github.com/apecloud/kubeblocks/commit/972c0d837e5c3280e45c5f46eae2f43bfb850b8c) to release-0.9
> fix: ensure GeneratePassword returns password with mixed cases in release-0.9

- controllers/apps/cluster/transformer_cluster_component.go
- pkg/testutil/apps/cluster_util.go
> fix: the cluster controller panic

- pkg/operations/expose.go
fix. https://github.com/apecloud/kbcli/issues/563
Issue: The errors returned by the expose actions do not update the status of OpsRequest to ‘failed’, and as a result, the OpsRequest is not marked as finished.
Changes: Fixed this by wrapping the errors with intctrlutil.Error(), ensuring the status is updated correctly and the OpsRequest is properly marked as failed when an error occurs.
> chore: fix errors in expose action 

- controllers/apps/component/component_controller_test.go
- controllers/apps/component/transformer_component_deletion.go
- controllers/apps/component/transformer_component_rbac.go
fixes #8941. Specifically, this PR tries to fix a stale read condition described in https://github.com/apecloud/kubeblocks/issues/8941#issuecomment-2700054137
One drawback is rbac resource won't be automactically cleaned up.
> fix: orphan rbac resources instead of deleting

- pkg/controller/instanceset/reconciler_instance_alignment.go
- pkg/controller/instanceset/reconciler_revision_update.go
- pkg/controller/instanceset/reconciler_update.go
- pkg/controller/kubebuilderx/controller.go
- pkg/controller/kubebuilderx/controller_test.go
- pkg/controller/kubebuilderx/doc.go
- pkg/controller/kubebuilderx/reconciler.go
Make it look better in rendered go doc html.
> chore: refine some comments and naming in kubebuilderx

- .github/workflows/release-image.yml
fix https://github.com/apecloud/kubeblocks/issues/9256
> chore: release kubeblocks-tools image not use cache

- cmd/kbagent/main.go
- pkg/controller/lifecycle/kbagent.go
- pkg/kbagent/client/client.go
- pkg/kbagent/client/client_mock.go
- pkg/kbagent/client/http_client.go
cherry picked from commit 5753c230cc4a57c869d959a333de4524fa87897e
> chore: release the connection to kbagent after calling the action

- controllers/apps/component/transformer_component_notifier.go
> fix: notify dependent components after other objects

- pkg/controller/instanceset/reconciler_update.go
- pkg/controller/instanceset/reconciler_update_test.go
In https://github.com/apecloud/kubeblocks/pull/9208, pending pod was not counted as unavailable. 
Suppose maxUnavailable=1, pod=3, and current pod status is pod-0 (new, pending), pod-1 (old, running), pod-2 (old, running). Instanceset controller will delete pod-1 since it considers pod-0 as available.
> fix: minReadySeconds not respected during pod update

- controllers/dataprotection/restore_controller.go
- controllers/dataprotection/restore_controller_test.go
- controllers/dataprotection/volumepopulator_controller.go
- pkg/dataprotection/restore/builder.go
- pkg/dataprotection/restore/manager.go
- pkg/dataprotection/restore/manager_test.go
- pkg/dataprotection/restore/types.go
fix https://github.com/apecloud/kubeblocks/issues/9231
we inject `restore manager` container into restore job pod, the container waits until all restore containers from every restore job have finished by monitoring an annotation signal added by the restore controller after all restore containers finish.
To guarantee that the recovered PVCs/PVs and pods are scheduled correctly, we specify the same scheduling policy for job pods. However, the scheduler might not consider the restore job pod when scheduling other pods if it is completed too quickly, which may lead to incorrect scheduling. This container ensures that all job pods are considered by the scheduler.
> fix: support restore manager sidecar

- go.mod
- pkg/controller/instanceset/reconciler_update.go
- pkg/controller/instanceset/reconciler_update_test.go
- pkg/controller/kubebuilderx/plan_builder.go
- pkg/controller/kubebuilderx/plan_builder_test.go
- pkg/controller/kubebuilderx/reconciler.go
- pkg/controller/kubebuilderx/reconciler_test.go
- pkg/controller/kubebuilderx/suite_test.go
- pkg/controller/model/graph_options.go
- pkg/controller/model/transform_types.go
- pkg/controllerutil/util.go
- pkg/controllerutil/util_test.go
- pkg/dataprotection/backup/utils.go
- pkg/dataprotection/utils/utils.go
- pkg/dataprotection/utils/utils_test.go
fixes https://github.com/apecloud/kubeblocks/issues/8999
since k8s 1.32, a new /resize subresource was introduced to do InPlacePodVerticalScaling
> fix: use /resize subresource in InPlacePodVerticalScaling when supported

- deploy/helm/templates/storageprovider/azureblob.yaml
Currently, only basic authentication with `Account Name` and `Account Key` is supported.
Usage:
```
kbcli backuprepo create --provider azureblob \
--account-name=xxx --account-key=xxx \
--container your-container-name
```
> chore: add azureblob storage provider

- deploy/helm/values.yaml
> chore: bump datasafed version to 0.2.1

- pkg/controller/component/synthesize_component.go
After adding environment variables (env) to the componentSpecs in the cluster, I noticed that the kbagent container in the pod did not contain the env variables I defined. Upon reviewing the source code, I found that the kbagent container is created after the environment variables are merged, and therefore does not utilize the env variables I specified.
> feat: export user-defined environment variables to lifecycle actions

- config/rbac/role.yaml
- controllers/workloads/instanceset_controller.go
- deploy/helm/config/rbac/role.yaml
fixes https://github.com/apecloud/kubeblocks/issues/9542
> fix: missing rbac rule for pod resize

- .github/workflows/cicd-pull-request.yml
> chore: check pr run

- controllers/apps/component/transformer_component_workload_ops.go
> fix: do not select the replicas being scaled as the data source

- controllers/dataprotection/backuprepo_controller.go
- pkg/dataprotection/utils/backuprepo.go
> fix: do not set runAsNonRoot to the init container of datasafed

- controllers/parameters/policy_util.go
- controllers/parameters/policy_util_test.go
- controllers/parameters/reconfigure_policy.go
- controllers/parameters/restart_policy.go
- controllers/parameters/restart_policy_test.go
- controllers/parameters/types.go
1. restart component instead of ITS (by add the annotation)
2. check both progress and component status. 
The paramter change is succ only when PROGRESS equals |pods| and component status is running,
> chore: restart component and check component status 
