apecloud/kubeblocks

docs/user_docs/installation/enable-addons.md
docs/user_docs/installation/install-kubeblocks.md
docs/user_docs/kubeblocks-for-mongodb/_category_.yml
docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
docs/user_docs/kubeblocks-for-mysql/cluster-management/create-and-connect-a-mysql-cluster.md
docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
docs/user_docs/kubeblocks-for-mysql/high-availability/high-availability.md
docs/user_docs/kubeblocks-for-mysql/migration/migration.md
docs/user_docs/kubeblocks-for-postgresql/_category_.yml
docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
docs/user_docs/kubeblocks-for-postgresql/configuration/configuration.md
docs/user_docs/kubeblocks-for-postgresql/high-availability/high-availability.md
docs/user_docs/kubeblocks-for-postgresql/migration/migration_postgresql.md
docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
docs/user_docs/kubeblocks-for-redis/configuration/configuration.md
docs/user_docs/kubeblocks-for-redis/high-availability/high-availability.md
docs/user_docs/kubeblocks-for-vector-database/_category_.yml
docs/user_docs/kubeblocks-for-vector-database/chatgpt-retrieval-plugin-with-kubeblocks.md
docs/user_docs/observability/access-logs.md
docs/user_docs/observability/alert.md
docs/user_docs/observability/monitor-database.md
docs/user_docs/quick-start/try-kubeblocks-on-cloud.md
docs/user_docs/quick-start/try-kubeblocks-on-your-laptop.md

(cherry picked from commit 1cba43ddd950c6e40f80c8a11dd253bbd59a749f)

docs: adjust docs 5.0 (#3597)

---

CODEOWNERS
MAINTAINERS.md
Makefile
docker/docker.mk

chore: tidy up Docker makefile jobs

---

internal/cli/cmd/cli.go
internal/cli/cmd/plugin/types.go
internal/cli/util/util.go
internal/controller/consensusset/transformer_deletion.go
internal/controller/consensusset/transformer_update_strategy.go

feat: cli set plugin bin dir in code issue3582

---

controllers/dataprotection/backup_controller.go

fix: change to correct schema to solve snapshot event loss problem

---

deploy/helm/templates/addons/chaos-mesh-addon.yaml

chore:  pull chaos mesh images from apecloud

---

docs/DEVELOPING.md

- for #3610 
Add the basic info for kbcli

chore: update kbcli doc

---

cmd/probe/README.md
cmd/probe/internal/binding/etcd/etcd.go
cmd/probe/internal/binding/kafka/kafka.go
cmd/probe/internal/binding/mongodb/mongodb.go
cmd/probe/internal/binding/mysql/mysql.go
cmd/probe/internal/binding/postgres/postgres.go
cmd/reloader/README.md

chore: remove internal doc link

---

docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md

fix: a typo in doc

---

docs/user_docs/installation/install-kbcli.md

chore：update kbcli version, add a highlight and fix the script error for https://kubeblocks.io/ doc

---

docs/user_docs/installation/install-kbcli.md
docs/user_docs/installation/uninstall-kbcli-and-kubeblocks.md
docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
docs/user_docs/quick-start/try-kubeblocks-on-your-laptop.md

- fix https://kubeblocks.io/docs/release-0.5/user_docs/installation/install-kbcli
window install script need powershell in administrator

doc: add the powershell administrator hits

---

.github/utils/utils.sh
.github/workflows/pull-request-label-size.yaml

chore: set pr size label

---

cmd/probe/internal/binding/postgres/postgres.go
controllers/apps/systemaccount_controller_test.go

fix: nakedret error

---

.devcontainer/devcontainer.json
docker/docker.mk
internal/controller/builder/cue/backup_job_template.cue
internal/controller/builder/cue/pvc_template.cue
internal/controller/builder/cue/restore_full_backup_job.cue

fix: #3707 
- fix build & push dev-container image
- update dev-container image `docker.io/apecloud/kubeblocks-dev:latest`

fix: make build & push dev-container

---

deploy/helm/values.yaml
deploy/mongodb/values.yaml

this pr is to upgrade agamotto image for mongodb
fix https://github.com/apecloud/kubeblocks/issues/3682

chore: upgrade agamotto image for mongodb

---

cmd/probe/internal/binding/redis/redis.go
deploy/redis/config/redis7-config.tpl
deploy/redis/scripts/redis-sentinel-setup.sh.tpl
deploy/redis/scripts/redis-sentinel-start.sh.tpl
deploy/redis/scripts/redis7-start.sh.tpl
deploy/redis/templates/clusterdefinition.yaml
deploy/redis/templates/scripts.yaml

fix: https://github.com/apecloud/kubeblocks/issues/2157
fix: https://github.com/apecloud/kubeblocks/issues/3681

chore: redis prohibits passwordless access by default

---

.github/workflows/release-sync.yml

- relate :  https://github.com/apecloud/apecloud-cd/pull/1

chore: upgrade apecloud-cd action version

---

controllers/apps/systemaccount_controller.go
controllers/apps/systemaccount_controller_test.go
controllers/apps/systemaccount_util.go
controllers/apps/systemaccount_util_test.go

picked following commits to relase 0.5: 
- bdc3b5255bc6d8cd2136b1fe47b86a510917b7d6
- d3b752c17dc6b2b331cf1017181e59adb84978a7
- 0edb8df8a44d09dbaac905ca18704079c11c4ed0
- 9eefb975b79f180a63e4cf780799704a8c1e2e61
- b572974772fed7e42206590c0daf4fb32c2c35f5  
- 5e89ec658a852f5998ebe170c4c542cbbc18e58e

chore: pick connection-auth-error related fixes to release

---

.github/utils/utils.sh
.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/release-version.yml

1. runs-on ubuntu-latest
2. make test pkgs parallel run

chore: make test parallel run on ubuntu-latest

---

.github/workflows/release-sync.yml

- fix #3787 
- What i do : Add a github.event.action filter

fix: forbidden pre-release trigger winget auto-publish action

---

internal/cli/cloudprovider/k3d.go
internal/cli/cloudprovider/provider.go
internal/cli/cloudprovider/types.go
internal/cli/cmd/playground/base.go

feat: cli playground destroy should check cloud provider version

---

go.mod
go.sum
internal/cli/cmd/playground/init.go
internal/cli/cmd/playground/init_test.go
internal/cli/util/system.go
internal/cli/util/version.go
internal/cli/util/version_test.go
version/version.go

feat: cli playground init on local should check the docker version

---

internal/cli/cmd/alert/add_receiver.go
internal/cli/cmd/alert/add_receiver_test.go
internal/cli/cmd/alert/alter.go
internal/cli/cmd/alert/config_smtpserver.go
internal/cli/cmd/alert/config_smtpserver_test.go
internal/cli/cmd/alert/delete_receiver.go
internal/cli/cmd/alert/delete_receiver_test.go
internal/cli/cmd/alert/list_receivers.go
internal/cli/cmd/alert/list_receivers_test.go
internal/cli/cmd/alert/util.go
internal/cli/cmd/alert/util_test.go

feat: cli alert support config SMTP

---

internal/cli/cmd/class/create.go

feat: kbcli class create support auto completion

---

.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/codeql.yml
README.md

1. new badge
2.  fix #3824 
reference: https://github.com/apecloud/apecloud-cd/pull/3/files

chore: new badge

---

Makefile
deploy/kafka/configs/kafka-server-constraint.cue
internal/configuration/config_manager/builder_test.go
internal/configuration/config_patch_test.go
internal/configuration/type_test.go
internal/controller/builder/cue/headless_service_template.cue
internal/controller/plan/tool_image_builder.go

exclude code generated dir `pkg/client` from `fmt` and `goimports`.

chore: makefile excludes generated clientset

---

.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/e2e-kbcli.yml
.github/workflows/release-helm-chart.yml
.github/workflows/release-image.yml
.github/workflows/release-publish.yml

1. kbcli e2e test on eks workflow after release
reference: https://github.com/apecloud/apecloud-cd/pull/4
2. change helm dep update
reference: https://github.com/apecloud/apecloud-cd/pull/7

chore: kbcli e2e test workflow

---

deploy/mongodb/templates/_helpers.tpl
deploy/mongodb/templates/clusterdefinition.yaml
deploy/mongodb/templates/clusterversion.yaml
deploy/mongodb/templates/sharding-clusterversion.yaml
deploy/mongodb/values.yaml
deploy/postgresql/values.yaml
deploy/redis/templates/_helpers.tpl
deploy/redis/templates/clusterdefinition.yaml
deploy/redis/templates/clusterversion.yaml
deploy/redis/values.yaml

chore: helm chart default use aliyun docker registry

---

docs/user_docs/cli/kbcli_cluster_create.md
internal/cli/cmd/cluster/create.go
internal/cli/cmd/cluster/create_test.go
internal/cli/cmd/cluster/dataprotection.go

feat: support restore cluster via `kbcli cluster create`

---

controllers/dataprotection/backuppolicy_controller.go
controllers/dataprotection/backuppolicy_controller_test.go
controllers/dataprotection/cue/cronjob.cue
controllers/dataprotection/type.go
internal/cli/cmd/cluster/create_test.go
internal/cli/cmd/cluster/dataprotection_test.go

fix: add tolerations for cronjob

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_alert_list-smtpserver.md
internal/cli/cmd/alert/alter.go
internal/cli/cmd/alert/list_smtpserver.go
internal/cli/cmd/alert/list_smtpserver_test.go

feat: cli support to show smtpserver config

---

controllers/dataprotection/backup_controller.go
controllers/dataprotection/backup_controller_test.go
controllers/dataprotection/cue/cronjob.cue
deploy/helm/values.yaml
internal/controller/builder/builder.go
internal/controller/builder/cue/volumesnapshotclass.cue
internal/controllerutil/volumesnapshot.go

- add auto create volumesnapshotclass, improve the success rate of backups.
ref: #3843

chore: auto create volumesnapshotclass

---

deploy/helm/templates/addons/alertmanager-webhook-adaptor-addon.yaml
deploy/helm/templates/addons/apecloud-mysql-addon.yaml
deploy/helm/templates/addons/aws-loadbalancer-controller-addon.yaml
deploy/helm/templates/addons/csi-driver-addon.yaml
deploy/helm/templates/addons/csi-hostpath-driver-addon.yaml
deploy/helm/templates/addons/csi-s3-addon.yaml
deploy/helm/templates/addons/grafana-addon.yaml
deploy/helm/templates/addons/migration-addon.yaml
deploy/helm/templates/addons/milvus-addon.yaml
deploy/helm/templates/addons/mongodb-addon.yaml
deploy/helm/templates/addons/nyancat-addon.yaml
deploy/helm/templates/addons/postgresql-addon.yaml
deploy/helm/templates/addons/prometheus-addon.yaml
deploy/helm/templates/addons/qdrant-addon.yaml
deploy/helm/templates/addons/redis-addon.yaml
deploy/helm/templates/addons/snapshot-controller-addon.yaml
deploy/helm/templates/addons/weaviate-addon.yaml
deploy/helm/values.yaml

(cherry picked from commit 515f6ef57bf13f85b8ffcba04538f65d01bfdb20)

chore: have Addon's chartLocationURL attribute setup as '.Values.addonChartLocationBase' template value (#3899)

---

controllers/apps/configuration/config_util.go
controllers/apps/configuration/reconfigurerequest_controller.go
go.mod
go.sum
internal/cli/cmd/plugin/types.go
internal/cli/cmd/plugin/utils.go
internal/controllerutil/volumesnapshot.go

feat: cli plugin adopt the block index repository

---

docs/user_docs/cli/kbcli_bench_sysbench.md
docs/user_docs/cli/kbcli_bench_sysbench_cleanup.md
docs/user_docs/cli/kbcli_bench_sysbench_prepare.md
docs/user_docs/cli/kbcli_bench_sysbench_run.md
go.mod
go.sum
internal/cli/cmd/bench/bench_test.go
internal/cli/cmd/bench/sysbench.go
internal/cli/cmd/bench/template/bench_sysbench_template.cue

feat: sysbench support set more paramters

---

controllers/dataprotection/backuppolicy_controller.go

(cherry picked from commit 06e0cc77335d094e3a87b7d31d7ab242e613073a)

fix: set failed when volumesnapshot config error (#3816)

---

deploy/helm/templates/addons/agamotto-addon.yaml
deploy/helm/templates/addons/alertmanager-webhook-adaptor-addon.yaml
deploy/helm/templates/addons/apecloud-mysql-addon.yaml
deploy/helm/templates/addons/aws-loadbalancer-controller-addon.yaml
deploy/helm/templates/addons/chaos-mesh-addon.yaml
deploy/helm/templates/addons/csi-driver-addon.yaml
deploy/helm/templates/addons/csi-hostpath-driver-addon.yaml
deploy/helm/templates/addons/csi-s3-addon.yaml
deploy/helm/templates/addons/grafana-addon.yaml
deploy/helm/templates/addons/loki-addon.yaml
deploy/helm/templates/addons/migration-addon.yaml
deploy/helm/templates/addons/milvus-addon.yaml
deploy/helm/templates/addons/mongodb-addon.yaml
deploy/helm/templates/addons/nyancat-addon.yaml
deploy/helm/templates/addons/opensearch-addon.yaml
deploy/helm/templates/addons/postgresql-addon.yaml
deploy/helm/templates/addons/prometheus-addon.yaml
deploy/helm/templates/addons/qdrant-addon.yaml
deploy/helm/templates/addons/redis-addon.yaml
deploy/helm/templates/addons/snapshot-controller-addon.yaml
deploy/helm/templates/addons/weaviate-addon.yaml
deploy/helm/templates/deployment.yaml
deploy/helm/values.yaml

* resolve #3911
cherry-pick 3f917042d257aba034b4a834c9c9b7a8d44ab190

feat: addon support to set private registry

---

.github/workflows/release-image.yml
.github/workflows/release-publish.yml

parallel upload release assert

chore: optimize release kbcli

---

apis/dataprotection/v1alpha1/backup_types.go

fix https://github.com/apecloud/kubeblocks/issues/3938

fix: pitr recoverable time is incorrect

---

deploy/apecloud-mysql/config/mysql8-config.tpl

* resolve #3896
cherry-pick a5f12039cfb66cca51b9dcd2273415bc0b1d3121 from release-0.5

chore: disable performance schema for smaller class

---

.github/utils/utils.sh
.github/workflows/release-delete.yml
.github/workflows/release-helm-chart.yml
.github/workflows/release-image.yml
.github/workflows/release-publish.yml

1. delete actions cache
2. delete release schedule
reference:https://github.com/apecloud/apecloud-cd/pull/9/files

chore: delete release schedule

---

deploy/helm/templates/addons/nebula-addon.yaml

feat: add addon for nebula.

---

apis/dataprotection/v1alpha1/backup_types.go
apis/dataprotection/v1alpha1/backup_types_test.go
deploy/mongodb/templates/backuptool_pitr.yaml

fix https://github.com/apecloud/kubeblocks/issues/3977

fix: recoverable time incorrect

---

.goreleaser.yaml

* resolve #3970
*  resolve #3974

fix: fix default install version for kubeblocks

---

internal/cli/cmd/cli.go
internal/cli/cmd/cluster/create.go
internal/cli/cmd/cluster/create_test.go
internal/cli/cmd/cluster/suite_test.go
internal/cli/cmd/kubeblocks/install.go
internal/cli/cmd/kubeblocks/upgrade.go
internal/cli/cmd/kubeblocks/util.go
internal/cli/cmd/kubeblocks/util_test.go
internal/cli/types/config.go
internal/cli/types/types.go
internal/cli/util/util.go

* resolve #3900 
* support environment variable `HELM_REPO_URL` to set default helm repo url
* support config key `helm_repo_url` for config file to set default helm repo url

feat: support to set helm repo url by config or environment

---

controllers/dataprotection/backup_controller_test.go
controllers/dataprotection/utils.go
internal/controller/plan/restore.go

fix https://github.com/apecloud/kubeblocks/issues/4000

fix: job name too long for label

---

controllers/apps/operations/switchover_util.go
deploy/apecloud-mysql/templates/clusterdefinition.yaml
deploy/apecloud-mysql/templates/scripts.yaml
deploy/mongodb/templates/clusterdefinition.yaml
deploy/mongodb/templates/clusterversion.yaml
deploy/mongodb/templates/scriptstemplate.yaml

feat: support mongodb switchover and apecloud-mysql switchover without candidate

---

.github/workflows/release-delete.yml

1. adjust delete schedule cron and delete alpha/beta release older than 30 days
2. delete chart parallel
reference: https://github.com/apecloud/apecloud-cd/pull/10/files

chore: change release delete cron

---

deploy/helm/templates/grafana/configmap-dashboards.yaml
deploy/helm/values.yaml
internal/cli/cmd/dashboard/dashboard.go
internal/cli/cmd/kubeblocks/config_test.go
internal/cli/cmd/kubeblocks/install.go
internal/cli/cmd/kubeblocks/install_test.go
internal/cli/cmd/kubeblocks/uninstall.go
internal/cli/cmd/kubeblocks/upgrade.go
internal/cli/cmd/playground/init.go

chore: the monitoring components need to be disabled when installing Kubeblocks

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_bench.md
docs/user_docs/cli/kbcli_bench_pgbench.md
docs/user_docs/cli/kbcli_bench_pgbench_cleanup.md
docs/user_docs/cli/kbcli_bench_pgbench_prepare.md
docs/user_docs/cli/kbcli_bench_pgbench_run.md
docs/user_docs/cli/kbcli_bench_sysbench.md
docs/user_docs/cli/kbcli_bench_sysbench_cleanup.md
docs/user_docs/cli/kbcli_bench_sysbench_run.md
internal/cli/cmd/bench/bench.go
internal/cli/cmd/bench/bench_test.go
internal/cli/cmd/bench/pgbench.go
internal/cli/cmd/bench/sysbench.go
internal/cli/cmd/bench/util.go

prepare data: `kbcli bench pgbench prepare test-pg --database postgres --user postgres --password p6xbxcg9 --scale 100`
run pgbench: `kbcli bench pgbench run test-pg --database postgres --user postgres --password p6xbxcg9`
cleanup data: `kbcli bench pgbench cleanup test-pg --database postgres --user postgres --password p6xbxcg9`

feat: cli bench support pgbench

---

.gitignore
internal/cli/cmd/cluster/create.go

fix: cli create mysql cluster with more components

---

deploy/prometheus/templates/clusterdefinition.yaml

fix: fixed conflicting values true and false

---

internal/controller/model/parallel_transformer.go
internal/controller/model/parallel_transformer_test.go

fix: parallel_transformer concurrent map writes

---

internal/cli/cmd/addon/addon.go
internal/constant/const.go

- #3889
What i do:
Add ~~two~~ one column for ~~"VERSION"~~ and "PROVIDER" and adjust the order

feat: kbcli support show addon version and provider

---

.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/release-helm-chart.yml

fix: add tdengine-cluster to dep_repo helm chart in github workflow

---

.github/utils/utils.sh
.github/workflows/cicd-pull-request.yml
.gitignore
Makefile

chore: exclude `zz_generated.deepcopy.go` from test coverage

---

internal/cli/cmd/cluster/dataprotection.go
internal/cli/cmd/cluster/dataprotection_test.go

fix https://github.com/apecloud/kubeblocks/issues/3858

fix: can not start the cluster which restored from a backup and source cluster is stopped

---

controllers/dataprotection/backup_controller.go
controllers/dataprotection/backup_controller_test.go
controllers/dataprotection/utils.go

- Automatically delete failed jobs to improve backup success rate.
part of #3843

fix: automatically cleanup fails job if logfile backup is New

---

deploy/mongodb/scripts/replicaset-post-start.tpl

fix https://github.com/apecloud/kubeblocks/issues/4067

fix: mongodb cluster sometimes restore failed

---

controllers/dataprotection/utils.go
internal/controller/plan/restore.go

fix: snapshot failed

---

.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/release-helm-chart.yml

1. update all helm chart dep
2. fix #4101 
reference：https://github.com/apecloud/apecloud-cd/pull/13

chore: update all helm chart dep

---

deploy/apecloud-mysql/templates/backuppolicytemplate.yaml
deploy/apecloud-mysql/templates/backuptool-pitr.yaml
deploy/apecloud-mysql/templates/backuptool.yaml
deploy/apecloud-mysql/templates/scripts.yaml

- add manifests backuplog start stop time
- add wal-g for apecloud mysql PITR
fix: #1562

feat: add apecloud mysql PITR function

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_bench.md
docs/user_docs/cli/kbcli_bench_delete.md
docs/user_docs/cli/kbcli_bench_list.md
docs/user_docs/cli/kbcli_bench_pgbench.md
go.mod
go.sum
internal/cli/cmd/bench/bench.go
internal/cli/cmd/bench/bench_test.go
internal/cli/cmd/bench/pgbench.go
internal/cli/cmd/bench/sysbench.go
internal/cli/types/types.go

feat: implement bench based on kubebench

---

deploy/prometheus/config/server/rulesFiles/redis_alert_rules.yml

chore: modify redis alert rules

---

apis/dataprotection/v1alpha1/backuppolicy_types.go
config/crd/bases/dataprotection.kubeblocks.io_backuppolicies.yaml
deploy/helm/crds/dataprotection.kubeblocks.io_backuppolicies.yaml
docs/user_docs/api-reference/backup.md
docs/user_docs/api-reference/cluster.md

chore: remote unsupported character from API doc

---

docs/user_docs/cli/kbcli_bench_pgbench.md
docs/user_docs/cli/kbcli_bench_sysbench.md
internal/cli/cmd/bench/bench.go
internal/cli/cmd/bench/bench_test.go
internal/cli/cmd/bench/pgbench.go
internal/cli/cmd/bench/sysbench.go
internal/cli/util/util.go

chore: bench support auto generate name

---

internal/controller/builder/builder.go

https://github.com/apecloud/kubeblocks/issues/4264

fix: Keep env in order to avoid make sts restart

---

internal/cli/cmd/bench/pgbench.go
internal/cli/cmd/bench/sysbench.go
internal/cli/types/types.go

chore: change kubebench group

---

apis/apps/v1alpha1/cluster_types.go
apis/apps/v1alpha1/opsrequest_webhook.go
controllers/apps/cluster_controller_test.go
controllers/apps/components/stateful_set.go
controllers/apps/components/utils.go
controllers/apps/components/utils_test.go
controllers/apps/components/workload_controller.go
controllers/apps/operations/switchover.go
controllers/apps/operations/switchover_util.go

(cherry picked from commit ec9710719be08f8328b5334884654f7a465be8af)

chore: code tidy up, refactor duplicated codes

---

apis/apps/v1alpha1/cluster_types.go

* fix https://github.com/apecloud/kubeblocks/issues/4277

fix: set empty default storage class

---

deploy/helm/templates/addons/kafka-addon.yaml
deploy/kafka/Chart.yaml

add add-on ( kafka-addon.yaml ) with auto-install=true

fix: kafka add add-on yaml

---

deploy/apecloud-mysql-cluster/templates/_helpers.tpl

chore: set smaller cpu cores for apecloud-mysql proxy

---

.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/release-helm-chart.yml

reference：https://github.com/apecloud/apecloud-cd/pull/28/files

chore: rm default prefix aliyun registry

---

controllers/apps/operations/reconfigure.go
controllers/apps/operations/reconfigure_util.go
controllers/apps/operations/reconfigure_util_test.go
internal/controller/plan/envfrom_utils.go
internal/controller/plan/envfrom_utils_test.go
internal/controller/plan/prepare.go
internal/controller/plan/prepare_test.go
internal/testutil/k8s/k8sclient_util.go
test/testdata/config/envfrom-constraint.yaml

1. When the configuration is changed, need to synchronize the changes to the envFrom configmap
2. refine code related envFrom
3. add ut

chore: fixed configuration changes maybe not take effect, add ut for envfrom

---

deploy/csi-s3/values.yaml
deploy/helm/templates/addons/csi-s3-addon.yaml
deploy/helm/templates/backuprepo.yaml
deploy/helm/templates/storageprovider/minio.yaml
deploy/helm/templates/storageprovider/oss.yaml
deploy/helm/templates/storageprovider/s3.yaml
deploy/helm/values.yaml

fix https://github.com/apecloud/kubeblocks/issues/4011

chore: create default BackupRepo during installation

---

deploy/pulsar/templates/configconstraints.yaml
internal/configuration/config_manager/config_handler.go
internal/configuration/config_manager/config_handler_test.go

old status progress(up) vs new status progress(down)

chore: improved reconfiguring status progress (#4344)

---

internal/cli/cluster/helper_test.go
internal/cli/cmd/cluster/cluster_test.go
internal/cli/cmd/cluster/create.go
internal/cli/cmd/cluster/update_test.go
internal/cli/cmd/kubeblocks/kubeblocks_objects_test.go
internal/cli/testing/fake.go
internal/cli/types/types.go
internal/cli/util/util.go
internal/cli/util/util_test.go

- fix #4335 
What i do:
1. check **DEFAULT_STORAGE_CLASS** in kubeblocks manager ConfigMap, if the flied has value we will take it as the default SC
2. fix UTs

fix: create cluster check KubeBlocks manager ConfigMap default storage class

---

deploy/postgresql/templates/scripts.yaml
deploy/redis/templates/scripts.yaml

fix: revert redis and postgresql start script retry times

---

controllers/dataprotection/backup_controller.go
controllers/dataprotection/backup_controller_test.go
controllers/dataprotection/utils.go

fix https://github.com/apecloud/kubeblocks/issues/4349

fix: adjust the search order of backup PVCs

---

internal/cli/cmd/kubeblocks/data/kubeblocks_base_preflight.yaml
internal/cli/cmd/kubeblocks/preflight.go
internal/cli/cmd/kubeblocks/preflight_test.go
internal/preflight/analyzer/analyze_result.go
internal/preflight/analyzer/analyze_result_test.go
internal/preflight/analyzer/kb_storage_class.go
internal/preflight/analyzer/kb_storage_class_test.go
internal/preflight/analyzer/kb_taint.go
internal/preflight/collect.go

fix: preflight failed when metric unready 

---

controllers/apps/operations/reconfigure_util.go
internal/cli/cluster/cluster.go
internal/cli/util/util.go
internal/cli/util/util_test.go

fix: incorrect component images

---

deploy/helm/templates/addons/vmagent-addon.yaml

add the yaml file of vmagent addon

feat: add vmagent addon

---

internal/cli/cmd/cluster/cluster_test.go
internal/cli/cmd/cluster/create.go

- fix: #4386
What i do:
Add more check for configmap when DEFAULT_STORAGE_CLASS is not existed with ut.

fix: create cluster when DEFAULT_STORAGE_CLASS not exist

---

internal/controller/plan/envfrom_utils.go
internal/controller/plan/envfrom_utils_test.go
internal/controller/plan/prepare_test.go

1. reduce the number of configmaps
2. rename the env-related configmap to "-envfrom"

chore: merge multi envfrom-related configmaps into one configmap

---

deploy/postgresql/templates/scripts.yaml
deploy/redis/scripts/redis7-start.sh.tpl
deploy/redis/templates/clusterdefinition.yaml
deploy/redis/templates/scripts.yaml

fix: downwardAPI volumes update blocked by redis post start script

---

deploy/helm/templates/addons/migration-addon.yaml
deploy/kafka/templates/clusterdefinition.yaml

https://github.com/apecloud/kubeblocks/issues/4348

fix: change kafka startup-probe setting

---

controllers/apps/systemaccount_controller.go
controllers/apps/systemaccount_controller_test.go

- fix #4432  
When a cluster is deleted when some jobs for system account are still running, such jobs won't be terminated or deleted immediated.  They are protected by a finalizer which will be removed when JOB is completed or failed (until hitting backoff limit).  Such running jobs are wasting resources and should be deleted proactively on cluster deletion.

fix: delete all jobs right after cluster being deleted

---

deploy/helm/templates/addons/tutorial-mysql-addon.yaml
deploy/oracle-mysql-cluster/.helmignore
deploy/oracle-mysql-cluster/Chart.yaml
deploy/oracle-mysql-cluster/templates/cluster.yaml
deploy/oracle-mysql-cluster/templates/rbac.yaml
deploy/oracle-mysql-cluster/templates/validate.yaml
deploy/oracle-mysql-cluster/values.schema.json
deploy/oracle-mysql-cluster/values.yaml
deploy/oracle-mysql/.helmignore
deploy/oracle-mysql/Chart.yaml
deploy/oracle-mysql/templates/_helpers.tpl
deploy/oracle-mysql/templates/clusterdefinition.yaml
deploy/oracle-mysql/templates/clusterversion.yaml
deploy/oracle-mysql/values.yaml

- fix #4467    
This PR is the first part of our addon tutorial, to create an addon for oracle mysql, and tutorial doc will be updated in line with each PR.

feat: create a mysql addon

---

deploy/helm/templates/_helpers.tpl
deploy/helm/templates/addons/apecloud-otel-collector-addon.yaml
deploy/helm/templates/addons/apecloud-otel-collector-values.yaml
deploy/helm/templates/addons/kafka-addon.yaml

fix: failed to enable kafka addon

---

controllers/apps/components/replication_set_utils.go
deploy/redis/config/redis7-config.tpl
deploy/redis/scripts/redis-sentinel-setup.sh.tpl
deploy/redis/scripts/redis-sentinel-start.sh.tpl
deploy/redis/scripts/redis7-start.sh.tpl
deploy/redis/templates/scripts.yaml

fix: update handleReplicationSetRoleChangeEvent and compatible redis upgrade from v0.5

---

controllers/dataprotection/backuppolicy_controller_test.go

* fix https://github.com/apecloud/kubeblocks/issues/4490

fix: unstable data protection test case

---

internal/preflight/analyzer/access.go

- fix: #4503 
What i do: fix the invalid hard-code path in windows

fix: kb install in windows fail due to preflight

---

docs/user_docs/resource-scheduling/resource-scheduling.md
docs/user_docs/user-management/manage_user_accounts.md

Fix typos in affinity and user accounts docs.

docs: fix typos

---

deploy/redis/scripts/redis7-start.sh.tpl

fix: redis hscale create replication relationship failed when redis-server is not ready

---

internal/sqlchannel/engine/mongodb.go
internal/sqlchannel/engine/redis.go

fix: kbcli cluster connect show example error 4403

---

controllers/apps/components/replication_set.go

fix: replicationSet handleRoleChange with abnormal primary number

---

go.mod

fix: fix login ci bug

---

.github/.codecov.yml

1. ignore codecov/project or codecov/patch error

chore: add codecov.yml

---

apis/apps/v1alpha1/clusterdefinition_types.go
apis/apps/v1alpha1/clusterdefinition_webhook.go
apis/apps/v1alpha1/clusterdefinition_webhook_test.go
config/crd/bases/apps.kubeblocks.io_clusterdefinitions.yaml
controllers/apps/systemaccount_util.go
deploy/apecloud-mysql/config/mysql-scale-vtgate-config-constraint.cue
deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
deploy/apecloud-mysql/config/mysql8-config-constraint.cue
deploy/helm/crds/apps.kubeblocks.io_clusterdefinitions.yaml
docs/user_docs/api-reference/cluster.md
internal/controller/builder/cue/rbac_template.cue

this is a subtask of API Compability.

chore: modify field statements.update attributed 

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_bench.md
docs/user_docs/cli/kbcli_bench_tpcc.md
go.mod
go.sum
internal/cli/cmd/bench/bench.go
internal/cli/cmd/bench/tpcc.go
internal/cli/types/types.go

feat: add tpcc for kbcli bench

---

deploy/helm/templates/addons/mysql-addon.yaml

chore: improve mysql addon chart location url

---

deploy/apecloud-mysql/templates/clusterdefinition.yaml
deploy/apecloud-mysql/templates/clusterversion.yaml

chore: remove image setting from apecloud-mysql cluster definition

---

internal/cli/cmd/kubeblocks/upgrade.go

* fix https://github.com/apecloud/kubeblocks/issues/4580

chore: scale KubeBlocks replicas to 0 before upgrade

---

deploy/apecloud-mysql/Chart.yaml
deploy/helm/Chart.yaml
deploy/mysql-cluster/Chart.yaml
deploy/mysql/Chart.yaml
deploy/oracle-mysql-cluster/Chart.yaml
deploy/oracle-mysql/Chart.yaml
deploy/postgresql/Chart.yaml
deploy/tdengine-cluster/Chart.yaml

upload helm charts to artifact hub.
```
error getting logo image https://github.com/apecloud/kubeblocks/raw/main/img/logo.png: unexpected status code received: 404 (package: apecloud-mysql-cluster version: 0.6.0-alpha.29)
error getting logo image https://github.com/apecloud/kubeblocks/raw/main/img/logo.png: unexpected status code received: 404 (package: postgresql version: 0.5.1)
error getting logo image https://github.com/apecloud/kubeblocks/raw/main/img/logo.png: unexpected status code received: 404 (package: postgresql version: 0.5.2)
error getting logo image https://github.com/apecloud/kubeblocks/raw/main/img/logo.png: unexpected status code received: 404 (package: postgresql version: 0.5.3)
error getting logo image https://github.com/apecloud/kubeblocks/raw/main/img/logo.png: …
```

chore: update helm charts logo url

---

README.md

chore: add artifact hub badge

---

deploy/postgresql/config/pg12-config.tpl
deploy/postgresql/config/pg14-config.tpl
internal/cli/cmd/builder/template/util.go
internal/controller/plan/builtin_functions.go
internal/controller/plan/config_template.go
internal/controller/plan/config_template_test.go
internal/controllerutil/pod_utils.go
internal/controllerutil/pod_utils_test.go

(cherry picked from commit 9f453809d86b0250b6eac9d75bfa52f47ec82429)

chore: Optimizing wal log parameters for small-size instances, e.g: Sealos instances

---

deploy/apecloud-mysql/config/mysql8-config.tpl

(cherry picked from commit f12dc99f4f46d163a4fd4b0b5c565a447081aef0)

chore: dynamic render the value of innodb_redo_log_capacity 

---

docs/user_docs/observability/monitor-database.md

update `granfana` to `grafana` at line 44.

chore: monitor-database.md spelling mistake

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_bench_pgbench.md
docs/user_docs/cli/kbcli_bench_sysbench.md
docs/user_docs/cli/kbcli_bench_tpcc.md
docs/user_docs/cli/kbcli_bench_tpch.md
docs/user_docs/cli/kbcli_bench_ycsb.md
internal/cli/cmd/bench/bench.go
internal/cli/cmd/bench/bench_test.go
internal/cli/cmd/bench/pgbench.go
internal/cli/cmd/bench/sysbench.go
internal/cli/cmd/bench/tpcc.go
internal/cli/cmd/bench/tpch.go
internal/cli/cmd/bench/ycsb.go
internal/cli/types/types.go

feat: bench add tpch

---

deploy/postgresql/scripts/setup.sh

fix: backward compatibility upgrade postgresql from v0.5.1 to v0.6.0

---

internal/cli/cmd/cli.go

fix: fix bin/kbcli for no any parameters

---

apis/apps/v1alpha1/clusterdefinition_webhook.go
apis/apps/v1alpha1/clusterdefinition_webhook_test.go
deploy/kafka/configs/kafka-server-constraint.cue
deploy/pulsar/config/broker-config-constraint.cue
deploy/pulsar/config/proxy-config-constraint.cue
internal/controller/component/component_fieldref_util.go

- fix #4782 
Add webhook validation to avoid headless svc ref to a stateless component.

fix: add validation for componentRef

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_bench_describe.md
docs/user_docs/cli/kbcli_builder_migrate-scripts.md
internal/cli/cmd/bench/bench.go
internal/cli/printer/describe.go

feat: bench add describe

---

controllers/apps/transform_utils.go
controllers/apps/transformer_cluster_deletion.go

To be compatible with clusters created by helm

fix: select ClusterRoleBinding w/o ManagedBy label at deletion

---

deploy/apecloud-mysql/config/mysql-scale-vttablet-config-constraint.cue
deploy/apecloud-mysql/config/mysql-scale-vttablet-config.tpl
deploy/apecloud-mysql/scripts/vttablet.sh

fix https://github.com/apecloud/kubeblocks/issues/4824

feat: wesql scale support connection pool size config

---

test/e2e/testdata/smoketest/postgresql/07_cv.yaml
test/e2e/testdata/smoketest/redis/08_cv.yaml
test/e2e/testdata/smoketest/wesql/07_cv.yaml

all images of all components are required in a CV.

fix: smoketest upgrade image required error

---

docs/user_docs/cli/kbcli_bench_list.md
internal/cli/cmd/bench/bench.go

feat: bench list add --all-namespaces

---

deploy/apecloud-mysql/templates/clusterdefinition.yaml

fix: stop exposing internal port of wesql-scale

---

.github/workflows/e2e-kbcli.yml

workflow ref: https://github.com/apecloud/apecloud-cd/pull/53/files
terraform ref: https://github.com/apecloud/cloud-provider/commit/3e3f4a8e7d5a12f3349569475b09363b302af52f

chore: support e2e test on gke

---

README.md

docs: readme link 404

---

deploy/helm/templates/addons/starrocks-addon.yaml
deploy/starrocks/Chart.yaml
deploy/starrocks/templates/_helpers.tpl
deploy/starrocks/templates/clusterdefinition.yaml
deploy/starrocks/templates/clusterversion.yaml
deploy/starrocks/templates/configmap.yaml
deploy/starrocks/values.yaml

feat: support starrocks

---

.github/workflows/e2e-kbcli.yml

ref: https://github.com/apecloud/apecloud-cd/pull/60/files

chore: select test type for e2e

---

deploy/greptimedb-cluster/values.schema.json

refactor: add values.schema.json to validate helm values for GreptimeDB

---

deploy/starrocks-cluster/.helmignore
deploy/starrocks-cluster/Chart.yaml
deploy/starrocks-cluster/templates/_helpers.tpl
deploy/starrocks-cluster/templates/cluster.yaml
deploy/starrocks-cluster/values.yaml

chore: add starrocks-cluster chart

---

.github/workflows/e2e-smoke.yml

resolve #4843 
ref: https://github.com/apecloud/apecloud-cd/pull/63/files

chore: add e2e smoke test workflow

---

.github/workflows/e2e-fault.yml

resolve #4938
ref: https://github.com/apecloud/apecloud-cd/pull/73/files

chore: add e2e fault test workflow

---

deploy/greptimedb/templates/clusterdefinition.yaml

fix: remove security context of etcd component

---

deploy/apecloud-mysql/templates/_helpers.tpl
deploy/apecloud-mysql/templates/clusterdefinition.yaml
deploy/apecloud-mysql/values.yaml

(cherry picked from commit 651fc0883ea88f1d75e8d3c7192bcc1247b6c51f)

chore: add options --set logCollector.enabled for apecloud-mysql addon

---

deploy/helm/templates/addons/bytebase-addon.yaml
deploy/helm/templates/addons/jupyter-notebook-addon.yaml
deploy/helm/templates/addons/orioledb-addon.yaml

fix: fix some hard-code addonChartURL

---

controllers/apps/transformer_cluster_status.go
internal/configuration/openapi/cue_gen_openapi.go
internal/sqlchannel/engine/postgresql.go

chore: rephrase pg conn example

---

internal/cli/cmd/kubeblocks/data/ack_preflight.yaml
internal/cli/cmd/kubeblocks/data/eks_preflight.yaml
internal/cli/cmd/kubeblocks/data/gke_preflight.yaml
internal/cli/cmd/kubeblocks/data/kubeblocks_base_preflight.yaml
internal/cli/cmd/kubeblocks/data/tke_preflight.yaml

fix: Refine error message of k8s version check

---

deploy/cert-manager/templates/NOTES.txt
deploy/helm/templates/addons/cert-manager-addon.yaml

fix: add cert-manager addon yaml

---

.github/workflows/e2e-kbcli.yml
.github/workflows/e2e-smoke.yml

ref: https://github.com/apecloud/apecloud-cd/pull/75/files

chore: add more e2e test type

---

controllers/apps/servicedescriptor_controller_test.go
internal/controller/plan/config_template.go
internal/controller/plan/config_template_utils.go
internal/controller/plan/config_template_utils_test.go
internal/controller/plan/service_descriptor_utils.go

(cherry picked from commit 09113a58776576fd8fd46edbcb1eb21e41caa7f0)

chore: service reference config template render support cross namespace

---

deploy/foxlake/Chart.yaml

fix helm package error
ref：https://github.com/apecloud/kubeblocks/actions/runs/6172404899/job/16752614358?pr=5054

chore: fix helm package error

---

deploy/pulsar-cluster/templates/cluster-with-zookeeper-service-reference.yaml
deploy/pulsar-cluster/templates/cluster-zookeeper-separate.yaml
deploy/pulsar-cluster/values.yaml
deploy/pulsar/config/bookies-env.tpl
deploy/pulsar/config/bookies-recovery-env.tpl
deploy/pulsar/config/broker-env.tpl
deploy/pulsar/templates/clusterdefinition-zookeeper.yaml
deploy/pulsar/templates/clusterdefinition.yaml

feat: support pulsar reference zookeeper by serviceRefDeclaration

---

cmd/lorry/main.go
go.mod
go.sum
lorry/binding/utils.go
lorry/highavailability/ha.go

1. set `DefaultConfigPath` to `/config/lorry/components`
2. set default logger
3. fix a type conversion error

fix: fatal errors after dapr removed

---

.github/workflows/e2e-performance.yml

resolve #5017 
ref: https://github.com/apecloud/apecloud-cd/pull/85/files

chore: support performance test

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli.md
docs/user_docs/cli/kbcli_backup.md
docs/user_docs/cli/kbcli_backup_create.md
docs/user_docs/cli/kbcli_backup_delete.md
docs/user_docs/cli/kbcli_backup_describe.md
docs/user_docs/cli/kbcli_backup_list.md
docs/user_docs/cli/kbcli_cluster_register.md
internal/cli/cmd/backup/backup.go
internal/cli/cmd/backup/create.go
internal/cli/cmd/backup/delete.go
internal/cli/cmd/backup/describe.go
internal/cli/cmd/backup/list.go
internal/cli/cmd/bench/bench.go
internal/cli/cmd/cli.go
internal/cli/cmd/cluster/dataprotection.go
internal/cli/cmd/cluster/dataprotection_test.go
internal/cli/util/completion.go

feat: kbcli support backup subcommnad

---

.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/release-delete.yml
.github/workflows/release-helm-chart.yml
.github/workflows/release-image.yml

relsove #5166 new aliyun registry url: infracreate-registry.cn-zhangjiakou.cr.aliyuncs.com
ref: https://github.com/apecloud/apecloud-cd/pull/87/files

chore: support aliyun new registry

---

apis/dataprotection/v1alpha1/backup_types.go

fix: the stoptime can be nil

---

.github/workflows/e2e-kbcli.yml
.github/workflows/release-delete.yml
.github/workflows/release-helm-chart.yml
deploy/mongodb-sharding-cluster/Chart.yaml
deploy/vllm/Chart.yaml

resolve: #5180 
ref: https://github.com/apecloud/apecloud-cd/pull/93/files

chore: distinguish jihulab url

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_backuprepo_describe.md
docs/user_docs/cli/kbcli_backuprepo_list.md
docs/user_docs/cli/kbcli_cluster_register.md
go.mod
internal/cli/cmd/backuprepo/backuprepo.go
internal/cli/cmd/backuprepo/describe.go
internal/cli/cmd/backuprepo/list.go

feat: backuprepo add list and describe cmd

---

deploy/oracle-mysql/templates/clusterversion.yaml

fix: update oracle mysql cv

---

internal/preflight/analyzer/kb_storage_class.go
internal/preflight/analyzer/kb_taint.go
internal/preflight/collect.go

fix: expose error info correctly when preflight

---

controllers/apps/configuration/configuration_controller.go
internal/cli/cmd/report/report.go
internal/controller/plan/prepare.go

fix: kbcli report with sc and pvc

---

internal/constant/const.go
internal/controller/component/probe_utils.go
internal/controller/component/probe_utils_test.go
internal/controller/rsm/transformer_object_generation.go
internal/controller/rsm/types.go
lorry/binding/base.go

fix: recover missing lorry env

---

internal/gotemplate/functional_test.go
internal/gotemplate/tpl_engine.go
internal/gotemplate/tpl_engine_test.go

feat: [TplEngine support customized gotemplate syntax](#5210 )

feat: tplengine support customized syntax (#5210)

---

controllers/apps/cluster_controller_test.go

fix: [FAIL] Cluster Controller test cluster Failed/Abnormal phase

---

deploy/polardbx/templates/clusterDefintion.yaml

- to #5258 
This PR modify PolarDB-X clusterDefinition to use ReplicatedStateMachine(RSM).

fix: Upgrade consensusSpec to rsmSpec for PolarDB-X.

---

.github/workflows/release-helm-chart.yml

resolve #5262 
ref: https://github.com/apecloud/apecloud-cd/pull/115/files

chore: split jihulab chart url to addons and applications

---

.github/workflows/release-delete.yml

ref: 
https://github.com/apecloud/apecloud-cd/pull/121/files
https://github.com/apecloud/helm-charts/pull/12/files

chore: update helm chart index

---

internal/cli/cmd/bench/bench.go
internal/cli/cmd/bench/pgbench.go
internal/cli/cmd/bench/sysbench.go
internal/cli/cmd/bench/ycsb.go

fix: the error message retunred

---

.github/workflows/e2e-performance.yml
.github/workflows/milestone-set.yaml
.github/workflows/pull-request-label-size.yaml

chore: auto set issue and pr milestone

---

.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/release-image.yml
docker/Dockerfile
docker/Dockerfile-dataprotection
docker/Dockerfile-tools

chore: COPY go. mod instead of bind

---

docs/user_docs/cli/cli.md
docs/user_docs/cli/kbcli_cluster.md
docs/user_docs/cli/kbcli_cluster_describe-backup-policy.md
internal/cli/cmd/cluster/cluster.go
internal/cli/cmd/cluster/dataprotection.go
internal/cli/cmd/cluster/dataprotection_test.go

feat: cli support describe backuppolicy

---

controllers/apps/operations/volume_expansion_test.go
controllers/apps/operations/volume_expansion_updater.go

fix https://github.com/apecloud/kubeblocks/issues/5339

fix: volume expansion opsrequest will be probabilistic failure on GKE/EKS

---

internal/cli/cluster/cluster.go
internal/cli/cluster/types.go
internal/cli/cmd/cluster/describe.go
internal/cli/cmd/cluster/describe_test.go
internal/cli/testing/fake.go
internal/cli/types/types.go

feat: cluster describe  use new backup crd

---

deploy/mongodb/templates/actionset-datafile.yaml
deploy/mongodb/templates/actionset-dump.yaml
deploy/qdrant/scripts/qdrant-restore.sh
deploy/qdrant/templates/actionset-datafile.yaml

fix: fix the restore script for qdrant

---

.github/workflows/cicd-pull-request.yml
.github/workflows/release-version.yml
Makefile

fix https://github.com/apecloud/kubeblocks/actions/runs/6532026613/job/17734437069?pr=5394

chore: upgrade golangci lint version

---

.github/workflows/e2e-kbcli.yml

fix https://github.com/apecloud/kubeblocks/issues/5496

chore: add kbcli workflow test type

---

deploy/csi-hostpath-driver/templates/statefulset.yaml
deploy/csi-hostpath-driver/values.yaml

chore: fix csi-hostpath-driver enable error

---

.github/localflows/cicd-local.yml
.github/localflows/github-action-locally.sh
.github/workflows/cherry-pick.yml
.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/codeql.yml
.github/workflows/e2e-fault.yml
.github/workflows/e2e-kbcli.yml
.github/workflows/e2e-performance.yml
.github/workflows/e2e-smoke.yml
.github/workflows/issues-move.yml
.github/workflows/merge-e2e-smoke.yml
.github/workflows/milestoneclose.yml
.github/workflows/package-version.yml
.github/workflows/pull-request-check.yml
.github/workflows/pull-request-user-interaction.yaml
.github/workflows/release-create.yml
.github/workflows/release-helm-chart.yml
.github/workflows/release-image.yml
.github/workflows/release-notes.yaml
.github/workflows/release-publish.yml
.github/workflows/release-sync.yml
.github/workflows/release-version.yml
.github/workflows/trigger-release.yml

1. fix setup kubectl error
2. upgrade actions/checkout version

chore: fix setup kubectl error

---

deploy/greptimedb/templates/clusterdefinition.yaml
deploy/nebula/templates/clusterdefinition.yaml
deploy/polardbx/templates/clusterDefintion.yaml

fix: update greptimedb and polardb-x port

---

.github/workflows/e2e-kbcli.yml

chore: add ggml test type

---

.github/utils/utils.sh
.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/release-version.yml

chore: get test pkgs from gh vars

---

.github/utils/utils.sh

fix https://github.com/apecloud/kubeblocks/actions/runs/6583939322/job/17887717007?pr=5556

chore: delete echo msg

---

pkg/cli/cmd/bench/bench_test.go
pkg/cli/cmd/bench/pgbench.go
pkg/cli/cmd/bench/sysbench.go
pkg/cli/cmd/bench/tpcc.go
pkg/cli/cmd/bench/tpch.go
pkg/cli/cmd/bench/ycsb.go

fix: failed create bench wihtout cluster name

---

controllers/dataprotection/restore_controller_test.go

chore: fix unstable test of restore controller

---

.github/workflows/e2e-kbcli.yml

resolve #5568
ref: https://github.com/apecloud/apecloud-cd/pull/145/files

chore: support e2e test on k3s

---

controllers/apps/cluster_controller.go
controllers/apps/cluster_plan_builder.go
controllers/workloads/replicatedstatemachine_controller.go
pkg/controller/rsm/plan_builder.go

chore: make 'Operation cannot be fulfilled on...' msg debug level

---

deploy/oracle-mysql/templates/actionset-xtrabackup.yaml

* fix #5590
```
backup-default-omysql-wzugiu-20231023194627   omysql-wzugiu-mysql-compdef-backup-policy   xtrabackup   my-repo   Completed   79231183     26s        2023-10-23T11:46:27Z   2023-10-23T11:46:53Z
```

fix: fix oracle-mysql backup actionSet

---

controllers/apps/components/hscale_volume_populator.go
controllers/dataprotection/backup_controller.go
controllers/dataprotection/backup_controller_test.go
controllers/dataprotection/backupschedule_controller_test.go
controllers/dataprotection/gc_controller_test.go
controllers/dataprotection/restore_controller_test.go
pkg/controllerutil/volumesnapshot.go
pkg/dataprotection/action/action_create_vs.go
pkg/dataprotection/backup/request_test.go
pkg/dataprotection/restore/manager_test.go
pkg/dataprotection/utils/utils.go
pkg/testutil/apps/native_object_util.go
pkg/testutil/apps/pv_factoy.go
pkg/testutil/dataprotection/backup_utils.go
pkg/testutil/type.go

Repair checklist:
1. fix volume snapshot failed if no default backup repo
2. fix volume snapshot if storageClass's provisioner not equals to driver name

fix: create snapshot failed if storageClass's provisioner not equals to driver name

---

deploy/helm/templates/addons/polardbx-addon.yaml

chore: add polardbx addon file

---

apis/dataprotection/v1alpha1/backup_types.go
config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
controllers/apps/component_controller_test.go
controllers/apps/transformer_backup_policy_tpl.go
controllers/dataprotection/backup_controller.go
deploy/apecloud-mysql/templates/actionset.yaml
deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
deploy/postgresql/dataprotection/pg-basebackup-restore.sh
pkg/cli/cmd/kubeblocks/install.go
pkg/cli/cmd/kubeblocks/upgrade.go
pkg/cli/util/breakingchange/constant.go
pkg/cli/util/breakingchange/upgradehandlerto0.7.go
pkg/cli/util/breakingchange/upgrader.go
pkg/cli/util/helm/helm.go
pkg/dataprotection/backup/deleter.go
pkg/dataprotection/restore/manager.go

data protection exists breaking changes, we should handle it during upgrading.
fix https://github.com/apecloud/kubeblocks/issues/5390

feat: support handle breaking changes during upgrading kubeblocks

---

cmd/manager/main.go
pkg/cli/types/types.go
pkg/cli/util/breakingchange/upgradehandlerto0.7.go
pkg/controller/rsm/transformer_deletion.go
pkg/controller/rsm/transformer_status.go

fix: workload upgrading from 0.5&0.6 to 0.7

---

deploy/apecloud-mysql/templates/clusterdefinition.yaml
deploy/kafka/templates/clusterdefinition.yaml
deploy/qdrant/templates/clusterdefinition.yaml

chore: add service port for oteld

---

deploy/mariadb-cluster/Chart.yaml

chore: change mariadb cluster chart name

---

controllers/apps/operations/reconfigure_pipeline.go
controllers/apps/operations/reconfigure_pipeline_test.go
controllers/apps/operations/reconfigure_util.go
pkg/controllerutil/util.go

fix: [[BUG] reconfigure painc when updating file](https://github.com/apecloud/kubeblocks/issues/5675)

fix: reconfigure painc when updating file (#5675)

---

apis/workloads/v1alpha1/replicatedstatemachine_types.go
config/crd/bases/workloads.kubeblocks.io_replicatedstatemachines.yaml
controllers/apps/components/component.go
deploy/helm/crds/workloads.kubeblocks.io_replicatedstatemachines.yaml
deploy/mongodb/templates/clusterdefinition.yaml
pkg/cli/util/breakingchange/upgradehandlerto0.7.go
pkg/controller/builder/builder_replicated_state_machine.go
pkg/controller/builder/builder_replicated_state_machine_test.go
pkg/controller/rsm/transformer_deletion.go
pkg/controller/rsm/transformer_deletion_test.go
pkg/controller/rsm/transformer_init.go
pkg/controller/rsm/transformer_init_test.go
pkg/controller/rsm/transformer_object_generation.go
pkg/controller/rsm/utils.go

fix #5677 
fix #5678 
fix #5683

fix: wrong cluster phase after upgrading to 0.7

---

deploy/zookeeper/templates/clusterdefinition.yaml

fix zookeeper cluster conn credentials endpoint missing port
Close #5680

fix: zookeeper cluster conn credentials endpoint missing port

---

deploy/redis-cluster/templates/_helpers.tpl
deploy/redis-cluster/templates/cluster.yaml
deploy/redis-cluster/values.yaml
deploy/redis/scripts/redis-proxy-setup.sh
deploy/redis/templates/_helpers.tpl
deploy/redis/templates/clusterdefinition.yaml
deploy/redis/templates/clusterversion.yaml
deploy/redis/values.yaml

feat: add proxy addon for redis

---

deploy/mongodb/templates/_helpers.tpl
deploy/mongodb/templates/clusterversion.yaml
deploy/mongodb/values.yaml
deploy/postgresql/templates/_helpers.tpl
deploy/postgresql/templates/clusterversion.yaml
deploy/postgresql/values.yaml

* resolve #5704
```
helm template mongo ./deploy/mongodb --output-dir ../manifests --set "enabledClusterVersions={mongodb-4.0,mongodb-4.2}"
```

chore: add enabledClusterVersions for mongodb and postgresql

---

controllers/apps/cluster_controller.go
pkg/controller/configuration/pipeline.go

fix: cluster phase keeps in Updating after reconfiguration done

---

controllers/apps/configuration/config_annotation.go
pkg/controllerutil/config_util.go

fix: [[BUG] the configuration status is incorrect occasionally](https://github.com/apecloud/kubeblocks/issues/5716 )

fix: the configuration status is incorrect occasionally (#5716)

---

pkg/controller/rsm/transformer_object_generation.go

fix: get lorry image from the same env

---

deploy/apecloud-mysql/scripts/vttablet.sh

fix https://github.com/apecloud/kubeblocks/issues/5735

fix: remove_config_params_for_wescale

---

deploy/openldap-cluster/templates/cluster.yaml
deploy/openldap/templates/clusterdefinition.yaml

fix: update volumeMounts name

---

deploy/polardbx/templates/clusterDefintion.yaml

fix: PolarDB-X component gms and dn restart not working

---

controllers/apps/operations/stop.go

fix: wrong ToClusterPhase setup in stop ops

---

deploy/official-postgresql/templates/clusterversion.yaml

feat: add official pg with zhparser extension

---

deploy/greptimedb/templates/clusterdefinition.yaml

fix: add initContainers to grant volume permissions for greptimedb

---

.github/workflows/release-delete.yml
.github/workflows/release-helm-chart.yml

ref: https://github.com/apecloud/apecloud-cd/pull/187/files

chore: change get addon repo

---

.github/workflows/cicd-pull-request.yml
.github/workflows/release-version.yml

fix: https://github.com/apecloud/kubeblocks/actions/runs/6779916663/job/18428920717?pr=5787

chore: skip test remove dir

---

go.mod
go.sum

fix https://github.com/apecloud/kubeblocks/security/dependabot/33

chore: fix security issue 33

---

apis/apps/v1alpha1/type.go
controllers/apps/transformer_cluster_deletion.go
pkg/controller/rsm/plan_builder.go
pkg/controller/rsm/transformer_deletion.go
pkg/controller/rsm/transformer_deletion_test.go
pkg/controller/rsm/utils.go
pkg/controller/rsm/utils_test.go

fix: rsm and cluster controller delete same cm

---

.github/workflows/package-version.yml
.github/workflows/release-create.yml
.github/workflows/release-delete.yml
.github/workflows/release-helm-chart.yml
.github/workflows/release-image.yml
.github/workflows/release-publish.yml
.github/workflows/release-version.yml

1. create kbcli and addons repo tag before releasing
2. call the workflow of sending feishu information from repo apecloud-cd
3. call the workflow of releasing kbcli from repo kbcli

chore: adjust release workflow

---

cmd/manager/main.go

fix: component controller event recorder panic

---

controllers/apps/systemaccount_util.go

chore: inject zero resource limit for account jobs

---

apis/apps/v1alpha1/cluster_types.go
apis/apps/v1alpha1/componentdefinition_types.go
apis/apps/v1alpha1/componentdefinition_webhook_test.go
apis/apps/v1alpha1/opsrequest_webhook.go
apis/apps/v1alpha1/opsrequest_webhook_test.go
config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
controllers/apps/component_utils.go
controllers/apps/component_utils_test.go
controllers/apps/operations/switchover.go
controllers/apps/operations/switchover_test.go
controllers/apps/operations/switchover_util.go
controllers/apps/operations/switchover_util_test.go
deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
pkg/constant/const.go
pkg/controller/component/synthesize_component.go
pkg/controller/component/type.go

refactor: switchover opsRequest  implements with componentDefinition LifeCycleAction

---

.github/workflows/cicd-push.yml

chore: fix pcregrep file is too long for the internal buffer

---

.github/workflows/release-image.yml

trigger workflow: https://github.com/apecloud/kubeblocks/actions/workflows/release-image.yml

chore: release kubeblocks dev

---

pkg/lorry/engines/foxlake/commands.go
pkg/lorry/engines/mongodb/commands.go
pkg/lorry/engines/mysql/commands.go
pkg/lorry/engines/opengauss/commands.go
pkg/lorry/engines/opengauss/commands_test.go
pkg/lorry/engines/opengauss/suite_test.go
pkg/lorry/engines/postgres/commands.go

feat: support opengauss cluster connect

---

README.md

Update the Slack link in README.

docs: update slack link

---

deploy/helm/templates/addons/influxdb-addon.yaml

add influxdb addon yaml for influxdb.

chore: add influxdb addon

---

deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
deploy/helm/templates/storageprovider/ftp.yaml
deploy/helm/templates/storageprovider/nfs.yaml
deploy/helm/values.yaml

feat: add ftp and nfs as backup storage

---

deploy/redis-cluster/values.schema.json

-  Adapt for `kbcli create redis` subcommand

chore: fix redis-cluster sentinel values schema json

---

.github/workflows/release-helm-chart.yml

fix https://github.com/apecloud/kubeblocks/actions/runs/7177684904/job/19544576469

chore: release addons charts after kubeblocks

---

apis/apps/v1alpha1/type.go
config/crd/bases/dataprotection.kubeblocks.io_backups.yaml
controllers/apps/component_controller_test.go
deploy/helm/crds/dataprotection.kubeblocks.io_backups.yaml
pkg/controller/component/vars.go

fix: disable KB_COMP_REPLICAS envvar to prevent pods from being restarted at h-scale

---

deploy/oceanbase-cluster/templates/_helpers.tpl
deploy/oceanbase-cluster/templates/cluster.yaml
deploy/oceanbase-cluster/values.schema.json
deploy/oceanbase-cluster/values.yaml
deploy/oceanbase/scripts/bootstrap.sh
deploy/oceanbase/scripts/entrypoint.sh
deploy/oceanbase/templates/clusterdefinition.yaml
deploy/oceanbase/templates/clusterversion.yaml

check details in: 
- https://github.com/apecloud/kubeblocks-addons/pull/95
- https://github.com/apecloud/kubeblocks-addons/pull/96

chore: refind ob with hostnetwork and host path SC to restart in-place

---

pkg/lorry/engines/foxlake/commands.go

fix: foxlake connect command

---

deploy/orioledb/config/etcd-serve-config.tpl

fix: orioledb etcd host error

---

controllers/apps/configuration/reconfigure_controller.go
go.mod

fix: remove AppNameLabelKey label in reconfiguration to fix reconfigure does not take effect

---

pkg/cli/cmd/cli.go

fix: remove config output to log

---

deploy/greptimedb/Chart.yaml
deploy/greptimedb/templates/clusterdefinition.yaml
deploy/greptimedb/templates/serviceaccount.yaml

- picked from https://github.com/apecloud/kubeblocks-addons/pull/107

chore: remove SA

---

controllers/apps/transformer_cluster_component_status.go
controllers/apps/transformer_component_workload.go

fix: issues regarding the upgrade from 0.7 to 0.8

---

controllers/apps/component_controller_test.go
controllers/apps/transformer_component_workload.go

fix: switchover before member leaving

---

deploy/helm/templates/storageprovider/oss.yaml

fix: invalid template in storageprovider/oss.yaml

---

controllers/apps/operations/ops_progress_util.go
pkg/controller/builder/builder_pod.go
pkg/controller/rsm/transformer_pod_generation.go
pkg/controller/rsm/transformer_status.go

fix: render pod template to pod when build pod

---

apis/apps/v1alpha1/componentdefinition_types.go
config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
go.mod
pkg/controller/component/component_post_provision.go
pkg/controller/component/component_post_provision_test.go

(cherry picked from commit be7c624e2619e10b3eb9b09c5cc188e9edf799c5)

chore: expand built-in envs in postProvision action

---

go.mod
pkg/controller/component/synthesize_component.go
pkg/controller/component/type.go

fix: backward compatible with TLS configuration render

---

controllers/apps/cluster_controller.go
controllers/apps/component_controller.go

fix: watch the Configuration object in component controller

---

controllers/apps/tls_utils_test.go
controllers/apps/transformer_component_tls.go
pkg/configuration/core/type.go

fixes https://github.com/apecloud/kubeblocks/issues/6110

fix: re-render config after tls config changed

---

pkg/dataprotection/backup/scheduler.go

* fix https://github.com/apecloud/kubeblocks/issues/6210

fix: cronjob schedule is overrided

---

controllers/apps/component_controller.go

fix: watch but not owned configuration object

---

controllers/apps/component_controller.go
controllers/apps/transformer_component_status.go

fix: watch but not own existed workload objects

---

cmd/manager/main.go
controllers/apps/configuration/policy_util.go
pkg/configuration/config_manager/builder.go
pkg/configuration/config_manager/handler_util.go
pkg/constant/const.go
pkg/controller/configuration/config_utils.go

feat:  [[Features] config-manager support host network #6235](https://github.com/apecloud/kubeblocks/issues/6235)

feat: config-manager support host network (#6235)

---

pkg/lorry/engines/oceanbase/commands.go

- relate: https://github.com/apecloud/kbcli/issues/136
obcluster-host:
obcluster-podnet:

chore: support ob dynamic port by ENV

---

pkg/controller/component/synthesize_component.go
pkg/controller/component/type.go

fix: https://github.com/apecloud/kubeblocks/issues/6283

fix: delete StatefulSetWorkload in SynthesizedComponent

---

pkg/lorry/engines/models/engine_types.go
pkg/lorry/engines/oracle/commands.go
pkg/lorry/engines/oracle/commands_test.go
pkg/lorry/engines/oracle/suite_test.go
pkg/lorry/engines/register/managers.go

chore: support oracle connect

---

deploy/helm/values.yaml

This version of datasafed supports compression.

chore: update datasafed to 0.0.6

---

controllers/apps/component_controller_test.go
controllers/apps/transformer_cluster_status.go

fix: the status of cluster is Abnormal at creating

---

pkg/controller/component/rsm_convertor.go

fix: set default update strategy for RSM

---

controllers/apps/transformer_cluster_service.go
controllers/apps/transformer_component_service.go
controllers/apps/transformer_component_workload.go

fix: pass the existed component service to RSM

---

pkg/controller/rsm/transformer_object_generation.go

fix: sts annotations were lost when merging

---

controllers/apps/transformer_component_rbac.go
pkg/constant/pattern.go
pkg/controller/component/component.go
pkg/controller/component/component_definition_convertor.go
pkg/controller/component/component_definition_convertor_test.go
pkg/controller/component/rsm_convertor.go
pkg/controller/factory/builder_test.go

fix: keep compatible for update strategy, SA name and access mode

---

pkg/controller/component/component_definition_convertor.go

fix: serial update strategy for replication workloads

---

controllers/apps/component_controller_test.go
controllers/apps/transformer_component_account_provision.go

fix:  component account provision skip initAccount

---

.github/workflows/release-helm-chart.yml
docker/custom-scripts/fetch-all-helm-charts.sh

1. auto update github helm-charts when release chart
2. release chart image fetch github helm-charts
3. upload jihulab charts parallel

chore: fix upload jihu chart rate limit

---

pkg/controller/component/component_definition_convertor.go

fix: set update strategy for RSM workloads

---

controllers/apps/transformer_cluster_deletion.go

fix: delete statefulset when deleting clusters

---

docs/release_notes/v0.8.0/v0.8.0.md

Tidy up release notes English expression.

doc: Update v0.8.0.md

---

controllers/apps/operations/reconfigure_util.go
pkg/configuration/core/config.go
pkg/configuration/core/config_util.go
pkg/unstructured/xml_config.go
pkg/unstructured/xml_config_test.go

feat: support hbase/hdfs configuration files.

chore: support array field update (#5852)

---

controllers/apps/configuration/policy_util.go
controllers/apps/transformer_component_status.go
pkg/controller/rsm/transformer_status.go
pkg/controller/rsm/utils.go
pkg/controllerutil/stateful_set_utils.go
pkg/controllerutil/stateful_set_utils_test.go

to be compatible with k8s prior to 1.22

chore: check availableReplicas of sts only if minReadySeconds is set

---

docs/user_docs/backup-and-restore/backup/backup-repo.md
docs/user_docs/handle-an-exception/full-disk-lock.md
docs/user_docs/kubeblocks-for-mysql/proxy/apecloud-mysql-proxy.md
docs/user_docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kubeblocks.md
i18n/zh-cn/user-docs/backup-and-restore/backup/backup-repo.md
i18n/zh-cn/user-docs/handle-an-exception/full-disk-lock.md
i18n/zh-cn/user-docs/kubeblocks-for-mysql/proxy/apecloud-mysql-proxy.md
i18n/zh-cn/user-docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kb.md

Adjust the version description in 0.8.0 docs.

docs: update 0.8 docs

---

config/lorry/components/binding_apecloud_postgresql.yaml
pkg/constant/const.go
pkg/lorry/engines/postgres/apecloudpostgres/manager.go
pkg/lorry/engines/postgres/apecloudpostgres/manager_test.go
pkg/lorry/engines/postgres/config.go
pkg/lorry/engines/postgres/config_test.go
pkg/lorry/highavailability/util.go

related to: https://github.com/apecloud/kubeblocks-addons/issues/116

feat: lorry support apecloud pg

---

.github/workflows/release-sync.yml

chore: Split operator and addon for Separate Caching

---

deploy/helm/templates/storageprovider/gcs-s3comp.yaml

fix https://github.com/apecloud/apecloud/issues/2230

fix: fix datasafed config for GCS

---

go.mod
pkg/dataprotection/backup/utils.go
pkg/dataprotection/backup/utils_test.go
pkg/dataprotection/utils/utils.go
pkg/dataprotection/utils/utils_test.go

* fix https://github.com/apecloud/kubeblocks/issues/6544

fix: do not set CRON_TZ for cronJob schedule if kubernetes version less than 1.22

---

controllers/dataprotection/backuprepo_controller.go

fix: add tolerations to backuprepo precheck pods

---

controllers/apps/operations/expose.go

fix: remove duplicated ports on exposing

---

.github/workflows/e2e-kbcli-k3s.yml

chore: fix ci options parse error

---

controllers/apps/transform_utils.go
controllers/apps/transform_utils_test.go

chore: ignore policy/v1 discovery error at cluster deletion

---

config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
controllers/apps/transformer_cluster_api_normalization.go
deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
pkg/constant/labels.go

chore: inherit cluster labels filter kubeblocks reserved label

---

.github/workflows/e2e-fault.yml
.github/workflows/e2e-kbcli.yml
.github/workflows/e2e-smoke.yml
.github/workflows/package-version.yml
.github/workflows/release-version.yml

1. e2e support test on aks
2. trigger release ent addons chart

chore: e2e support test on aks

---

apis/apps/v1alpha1/configconstraint_types.go
apis/apps/v1alpha1/type.go
apis/apps/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
config/crd/bases/apps.kubeblocks.io_opsrequests.yaml
controllers/apps/configuration/combine_upgrade_policy.go
controllers/apps/configuration/combine_upgrade_policy_test.go
controllers/apps/configuration/reconfigure_policy.go
controllers/apps/configuration/sync_upgrade_policy.go
deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
deploy/helm/crds/apps.kubeblocks.io_opsrequests.yaml
docs/developer_docs/api-reference/cluster.md
pkg/configuration/core/constraint.go

(cherry picked from commit 562149abbb29eef7756382f3aeec3ae1ecaac843)

feat: support dynamic reload selected parameters policy (#6741) (#6742)

---

controllers/apps/component_utils.go
pkg/controller/component/lorry_utils.go

fix: mogdb role probe

---

deploy/helm/templates/storageprovider/cos.yaml
deploy/helm/templates/storageprovider/obs.yaml
deploy/helm/templates/storageprovider/oss.yaml

fix: make StorageProviders respect the custom endpoint setting

---

apis/dataprotection/v1alpha1/backuprepo_types.go
config/crd/bases/dataprotection.kubeblocks.io_backuprepos.yaml
controllers/dataprotection/backup_controller.go
controllers/dataprotection/backup_controller_test.go
controllers/dataprotection/backuprepo_controller.go
deploy/helm/crds/dataprotection.kubeblocks.io_backuprepos.yaml
docs/developer_docs/api-reference/backup.md
pkg/dataprotection/backup/request.go
pkg/dataprotection/backup/utils.go

feat: BackupRepo supports specifying prefix of storage path

---

deploy/helm/templates/storageprovider/cos.yaml
deploy/helm/templates/storageprovider/gcs-s3comp.yaml
deploy/helm/templates/storageprovider/minio.yaml
deploy/helm/templates/storageprovider/obs.yaml
deploy/helm/templates/storageprovider/oss.yaml
deploy/helm/templates/storageprovider/s3.yaml

feat: add "insecure" option for S3 storage providers

---

controllers/apps/configuration/combine_upgrade_policy_test.go
controllers/apps/configuration/config_reconcile_wrapper.go
controllers/apps/configuration/parallel_upgrade_policy_test.go
controllers/apps/configuration/policy_util.go
controllers/apps/configuration/policy_util_test.go
controllers/apps/configuration/reconfigure_controller.go
controllers/apps/configuration/reconfigure_policy.go
controllers/apps/configuration/rolling_upgrade_policy_test.go
controllers/apps/configuration/simple_policy_test.go
controllers/apps/configuration/sync_upgrade_policy_test.go
controllers/workloads/replicatedstatemachine_controller.go
pkg/controllerutil/rsm_utils.go

fix: remove dependency of Reconfigure on StatefulSet

---

controllers/dataprotection/backuprepo_controller.go

fix: set securityContext.runAsUser for backupRepo pre-check job

---

.github/workflows/issues-move.yml

chore: fix release issue move error

---

controllers/apps/transformer_cluster_load_resources.go
controllers/apps/transformer_cluster_load_resources_test.go

fix: compatible with clusters that have all definitions set

---

.github/workflows/cicd-push.yml

resolve https://github.com/apecloud/kubeblocks/issues/6976

chore: ci check license header

---

controllers/apps/transformer_cluster_deletion.go
controllers/apps/transformer_component_deletion.go
pkg/controller/model/transform_utils.go

fix: cluster is always in 'Deleting' after upgrade from 0.8.2 to 0.9

---

controllers/apps/transformer_component_service.go
pkg/constant/const.go
pkg/controller/rsm2/instance_util.go

cherry-pick from commit ef8f1430d242df1a29aaefc212c4fe9fe90f3509

chore: pod-service supports non-sequential pod ordinals

---

pkg/controller/component/service_descriptor_utils.go
pkg/controller/component/service_descriptor_utils_test.go

fix: allow service-ref not defined in legacy API

---

pkg/controller/rsm2/in_place_update_util.go
pkg/controller/rsm2/in_place_update_util_test.go
pkg/controller/rsm2/instance_util_test.go

fix: reconfigure not working

---

pkg/controller/rsm2/reconciler_update.go
pkg/controller/rsm2/reconciler_update_test.go

fix: do update in reverse ordinal order

---

pkg/lorry/client/httpclient_test.go
pkg/lorry/dcs/types.go
pkg/lorry/highavailability/ha.go
pkg/lorry/operations/replica/leave.go

fix: https://github.com/apecloud/kubeblocks/issues/7063

fix: delete leave member in ha loop

---

pkg/controller/instanceset/instance_util.go
pkg/controller/instanceset/instance_util_test.go
pkg/controller/instanceset/suite_test.go

fix: resources merging failed

---

controllers/apps/transformer_component_hostnetwork.go

fix: nil pointer when allocating host-ports

---

controllers/k8score/event_controller_test.go
pkg/controller/rsm/pod_role_event_handler.go
pkg/controller/rsm/pod_role_event_handler_test.go

fix: instance template role label update failed

---

cmd/dataprotection/main.go
controllers/dataprotection/backup_controller.go
controllers/dataprotection/backuprepo_controller.go
controllers/dataprotection/backupschedule_controller.go
controllers/dataprotection/restore_controller.go
controllers/dataprotection/utils.go
controllers/dataprotection/utils_test.go
controllers/dataprotection/volumepopulator_controller.go
controllers/storage/storageprovider_controller.go
deploy/helm/templates/dataprotection.yaml
pkg/controller/multicluster/options.go
pkg/controllerutil/controller_common.go
pkg/dataprotection/utils/utils.go

chore: adapt StorageProvider and BackupRepo to support multi-cluster mode

---

.github/workflows/cicd-pull-request.yml
.github/workflows/pull-request-label-approve.yaml
.github/workflows/pull-request-review.yaml

chore: optimize PR approve trigger make test

---

pkg/controller/instanceset/instance_util.go
pkg/controller/instanceset/instance_util_test.go
pkg/controller/instanceset/reconciler_instance_alignment.go
pkg/controller/instanceset/reconciler_instance_alignment_test.go
pkg/controller/instanceset/reconciler_update.go
pkg/controller/instanceset/reconciler_update_test.go

fix: restart in wrong order

---

config/rbac/role.yaml
controllers/apps/component_controller.go
deploy/helm/config/rbac/role.yaml

fix: no permissions for crd list&watch

---

cmd/manager/main.go
controllers/apps/cluster_status_event_handler.go
controllers/apps/component_controller_test.go
controllers/apps/configuration/rolling_upgrade_policy_test.go
controllers/apps/opsrequest_controller_test.go
controllers/apps/transformer_cluster_deletion.go
controllers/k8score/event_controller_test.go
controllers/k8score/event_handler.go
deploy/helm/values.yaml
pkg/configuration/core/type.go
pkg/constant/const.go
pkg/constant/pattern.go
pkg/controller/factory/builder.go
pkg/controller/factory/builder_test.go
pkg/controller/instanceset/object_builder.go
pkg/controller/instanceset/pod_role_event_handler.go
pkg/controller/instanceset/pod_role_event_handler_test.go
pkg/controller/instanceset/reconciler_status.go
pkg/controller/instanceset/revision_util_test.go
pkg/controller/instanceset/types.go
pkg/controller/instanceset/update_plan.go
pkg/controller/instanceset/utils.go
pkg/controller/instanceset/utils_test.go
pkg/controller/plan/restore.go

(cherry picked from commit 7daf78a1e43450e38f40be6948e4af6bb13e5456)

chore: rename param rsm/sts to its (#7139)

---

.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml
.github/workflows/codeql.yml
.github/workflows/release-version.yml

chore: fix workflow apt-get update error

---

deploy/helm/templates/admission/webhookconfiguration.yaml

fix: rename rsm webhooks to instanceset webhooks

---

pkg/controller/component/vars.go
pkg/controller/component/vars_test.go

cherry picked from commit 5543ebb62e4dbc74a586a072af423dd53b6949f2

chore: should report error when resolving partial required objects

---

controllers/extensions/addon_controller.go
controllers/extensions/addon_controller_stages.go
controllers/extensions/addon_controller_test.go
controllers/extensions/const.go

fix #7007 by modify spec of addon when enabling

fix: make provider and version of addon consistent (#7007)

---

.gitignore

If run `make manifests` or `make test`, will generate some temp files in `hack/github.com/`, if run `git status` will show these temp files are added and then are deleted as follows:
```
git status
On branch support/git-ignore-client-gen-temp-directory
Your branch is up to date with 'origin/support/git-ignore-client-gen-temp-directory'.
Changes to be committed:
(use "git restore --staged <file>..." to unstage)
new file:   hack/github.com/apecloud/kubeblocks/pkg/client/clientset/versioned/clientset.go
new file:   hack/github.com/apecloud/kubeblocks/pkg/client/clientset/versioned/fake/clientset_generated.go
new file:   hack/github.com/apecloud/kubeblocks/pkg/client/clientset/versioned/fake/doc.go
new file:   hack/github.com/apecloud/kubeblocks/pkg/client/clientset/versioned/fake/register.go …
```

chore: git ignore client-sdk-gen generated temp directory

---

pkg/controller/instanceset/object_builder.go
pkg/controller/instanceset/object_builder_test.go

fix: replicas env error after h-scale

---

controllers/apps/transformer_component_account_provision.go

fix: provision system accounts for legacy definitions

---

controllers/extensions/addon_controller_stages.go
controllers/extensions/addon_controller_test.go
controllers/extensions/const.go
pkg/constant/const.go

fix #7114  : Fixed null pointer error bug and added addon checks to support Kubernetes versions prior to 1.25.

fix: Fixed null pointer error bug and added addon checks to support Kubernetes versions prior to 1.25.

---

pkg/controller/component/lorry_utils.go

fix: add lorry ports to hostnetwork

---

pkg/controller/instanceset/in_place_update_util.go

fix: pod update forever when resources.requests is nil

---

controllers/apps/transformer_component_workload_upgrade.go
pkg/controller/instanceset/utils.go
pkg/controller/kubebuilderx/plan_builder_test.go

fix: configmap 'xxx-rsm-env' not found

---

pkg/controller/component/service_reference.go

fix: nil ptr on empty service descriptor

---

deploy/helm/templates/dataprotection.yaml
deploy/helm/templates/deployment.yaml
deploy/helm/values.yaml

cherry-picked from https://github.com/apecloud/kubeblocks/pull/7352

chore: add labels to distinguish kb and dataprotection (#7352)

---

pkg/controller/instanceset/instance_util.go
pkg/controller/instanceset/instance_util_test.go
pkg/controller/instanceset/reconciler_instance_alignment.go
pkg/controller/instanceset/reconciler_instance_alignment_test.go

fix: make pvc creation idempotent

---

controllers/dataprotection/backup_controller.go

fix: missing svc related feature gates in backup

---

controllers/apps/transformer_cluster_backup_policy.go

fix: panic error

---

i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/create-and-connect-to-a-redis-cluster.md

Redis Cluster no mysql Cluster中文母语错了竟然

chore: Update create-and-connect-to-a-redis-cluster.md

---

controllers/apps/componentversion_controller.go
controllers/apps/componentversion_controller_test.go

fixes #7414, not sure if this is a right fix. @leon-inf please take a look

fix: cluster creation error when serviceVersion is not set in ComponentDefinition

---

apis/apps/v1alpha1/servicedescriptor_types.go
apis/apps/v1alpha1/servicedescriptor_webhook.go
apis/apps/v1alpha1/servicedescriptor_webhook_test.go
apis/apps/v1alpha1/type.go
apis/apps/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
config/crd/bases/apps.kubeblocks.io_components.yaml
config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
controllers/apps/servicedescriptor_controller.go
deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
deploy/helm/crds/apps.kubeblocks.io_components.yaml
deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
docs/developer_docs/api-reference/cluster.md
pkg/constant/const.go
pkg/controller/builder/builder_service_descriptor.go
pkg/controller/builder/builder_service_descriptor_test.go
pkg/controller/component/service_descriptor_utils.go
pkg/controller/component/service_descriptor_utils_test.go
pkg/controller/component/service_reference.go
pkg/controller/component/service_reference_test.go
pkg/controller/component/vars.go
pkg/controller/component/vars_test.go
pkg/testutil/apps/servicedescriptor_factory.go

cherry-picked from commit c347ee1ce383dc65041338ed5ae47d52a028ec6e

chore: host field for service-ref

---

controllers/apps/operations/custom.go
controllers/apps/operations/custom/utils.go
controllers/apps/operations/expose.go
controllers/apps/operations/switchover.go
controllers/apps/operations/upgrade.go
pkg/controller/component/component.go
pkg/controller/component/service_descriptor_utils_test.go
pkg/controller/component/vars.go
pkg/controller/component/vars_test.go

cherry picked from commit d5e022afebde99be30e78d9fa5191a6756bf0e25

chore: using the actual service name to resolve service objects (#7468)

---

controllers/apps/cluster_controller.go
controllers/apps/transformer_cluster_component.go
controllers/apps/transformer_cluster_component_test.go
controllers/apps/transformer_cluster_deletion.go
controllers/apps/transformer_cluster_deletion_test.go
controllers/apps/transformer_cluster_halt.go
controllers/apps/transformer_cluster_load_resources.go

chore: delete components ordered at cluster deletion

---

controllers/apps/transformer_component_workload_upgrade.go

fix: using Orphan PropagationPolicy when deleting the RSM objects

---

controllers/apps/operations/reconfigure_pipeline.go

The reason why FileFormatConfig is invalid may be caused by the upgrade. The check has been added.
related issue: #7524

fix: doMerge panic error (#7530)

---

apis/apps/v1alpha1/componentdefinition_types.go
config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
controllers/apps/componentdefinition_controller.go
controllers/apps/componentdefinition_controller_test.go
deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
docs/developer_docs/api-reference/cluster.md
pkg/controller/builder/builder_component_definition.go
pkg/controller/component/lorry_utils.go
pkg/controller/component/rsm_convertor.go

(cherry picked from commit a430a6800eadf9fd8454792b92e537a469b91e34)

chore: support multiple init system accounts

---

apis/apps/v1alpha1/cluster_types.go
apis/apps/v1alpha1/component_types.go
apis/apps/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/apps.kubeblocks.io_clusters.yaml
config/crd/bases/apps.kubeblocks.io_components.yaml
controllers/apps/transformer_cluster_component.go
deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
deploy/helm/crds/apps.kubeblocks.io_components.yaml
docs/developer_docs/api-reference/cluster.md
pkg/controller/builder/builder_component.go
pkg/controller/component/component.go
pkg/controller/component/component_test.go
pkg/controller/component/synthesize_component.go
pkg/controller/component/synthesize_component_test.go
pkg/controller/component/type.go
pkg/controller/factory/builder.go
pkg/testutil/apps/constant.go

feat: support user-defined annotations, env and volumes

---

docs/user_docs/kubeblocks-for-mysql/configuration/configuration.md
i18n/zh-cn/user-docs/kubeblocks-for-mysql/configuration/configuration.md

fix https://github.com/apecloud/kubeblocks/issues/7552 , user command kbcli cluster explain-config parameter

docs: KubeBlocks for MySQL Configure cluster parameters 

---

pkg/controller/instanceset/in_place_update_util.go
pkg/controller/instanceset/in_place_update_util_test.go

fix: test InPlacePodVerticalScaling all the time

---

go.mod
pkg/configuration/config_manager/builder.go
pkg/configuration/config_manager/handler_util.go
pkg/controller/configuration/config_utils.go
pkg/controller/configuration/tool_image_builder_test.go
pkg/controller/factory/builder.go
pkg/controller/factory/builder_test.go

This reverts commit 8912260ccf1121be18692e6bf0a40488a05d57a9.

chore: Revert remove dependence on characterType (#7500)

---

config/samples/extensions_v1alpha1_addon.yaml
deploy/helm/templates/_helpers.tpl
deploy/helm/templates/applications/chaos-mesh-addon.yaml
deploy/helm/values.yaml
pkg/controller/component/lorry_utils.go
pkg/controller/instanceset/revision_util_test.go
test/e2e/testdata/config/postgresql_cv.yaml
test/testdata/backup/actionset.yaml

chore: switch aliyun image registry infracreate to apecloud

---

controllers/apps/transformer_component_workload.go

fix: volume expansion failed with offline instances

---

deploy/helm/values.yaml

chore: do not override grafna value with clear text passwd

---

controllers/apps/transformer_component_workload_upgrade.go
pkg/controller/instanceset/instance_util.go

fix: upgrade `rsm-env` object

---

controllers/apps/transformer_component_workload_upgrade.go
pkg/controller/instanceset/instance_util.go

(cherry picked from commit b765afe638974a3c36a9bfd94b3eb5d25ee5fefe)

fix: upgrade `rsm-env` object (#7676)

---

pkg/lorry/engines/redis/commands.go

fix redis cannot display password

fix: redis display password

---

pkg/controller/instanceset/instance_template_util.go

resolve https://github.com/apecloud/kubeblocks/issues/7706

feat: add instance template public api

---

pkg/controller/component/definition_convertor.go
pkg/controller/component/synthesize_component.go
pkg/controller/component/utils.go

This reverts commit ff5d42df4f210ecd5f9c753e1719823ff87be6a9.

chore: revert "compatible with a special usage of cmpd host-network #7647)"

---

docs/01 - build.md

fix #7570，add examples and guidance in developer documentation.

docs: supplement content of developer documentation

---

.github/workflows/release-helm-chart.yml
pkg/controller/instanceset/instance_template_util.go

fix https://github.com/apecloud/kubeblocks/actions/runs/9776704923/job/26989821104

chore: fix header license check FAIL

---

controllers/apps/transformer_component_rbac.go

fix:  automatically create a ServiceAccount by default if any lifecycle actions are present

---

apis/apps/v1alpha1/scheduling_policy.go
apis/workloads/v1alpha1/instanceset_types.go
config/crd/bases/apps.kubeblocks.io_servicedescriptors.yaml
deploy/helm/crds/apps.kubeblocks.io_servicedescriptors.yaml
pkg/controller/instanceset/instance_template_util.go
pkg/controller/instanceset/instance_util_test.go

chore: fix lint error

---

apis/apps/v1alpha1/cluster_types.go
apis/apps/v1alpha1/component_types.go
apis/apps/v1alpha1/zz_generated.deepcopy.go
apis/workloads/v1alpha1/instanceset_types.go
config/crd/bases/apps.kubeblocks.io_clusters.yaml
config/crd/bases/apps.kubeblocks.io_components.yaml
config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
deploy/helm/crds/apps.kubeblocks.io_components.yaml
deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
pkg/controller/builder/builder_component.go
pkg/controller/builder/builder_instance_set.go
pkg/controller/builder/builder_instance_set_test.go
pkg/controller/component/component.go
pkg/controller/component/its_convertor.go
pkg/controller/component/synthesize_component.go
pkg/controller/component/type.go
pkg/controller/instanceset/reconciler_update.go
pkg/controller/instanceset/reconciler_update_test.go
pkg/controller/instanceset/types.go

resolve https://github.com/apecloud/kubeblocks/issues/7712

feat: Support user-specified podUpdatePolicy

---

pkg/controller/component/synthesize_component.go
pkg/controller/component/type.go

(cherry picked from commit 7e409262b7bf7e1738d6e63a498acf7410b64aa0)

chore: pick mysql/wesql has no slow log 

---

pkg/controller/plan/tls_utils.go

fix: use ca gen cert file insteat of selfsign ca

---

controllers/apps/transformer_cluster_component.go

fix a bug in https://github.com/apecloud/kubeblocks/pull/7743

fix: podUpdatePolicy update issue

---

pkg/controller/component/synthesize_component.go

fix: avoid override original static env

---

cmd/manager/main.go
deploy/helm/templates/deployment.yaml
deploy/helm/values.yaml
pkg/constant/config.go
pkg/constant/flag.go
pkg/controller/factory/builder.go

feat: support FeatureGateComponentReplicasAnnotation feature gate

---

controllers/dataprotection/utils.go

fix https://github.com/apecloud/kubeblocks/issues/7072

fix: use len function to check targetPods slice

---

config/rbac/role.yaml
controllers/extensions/addon_controller.go
deploy/helm/config/rbac/role.yaml

fix: generate rbac permissions to list deployments

---

.github/workflows/cicd-pull-request.yml
.github/workflows/cicd-push.yml

Check is split into parallel to improve efficiency.
Before：
After：

chore: split push check and test

---

controllers/apps/operations/ops_manager.go

fix: Rectify the Issue with 'timeoutSecond' Parameter functioning wrong… 

---

apis/apps/v1alpha1/cluster_types.go
config/crd/bases/apps.kubeblocks.io_clusters.yaml
deploy/helm/crds/apps.kubeblocks.io_clusters.yaml

add validation for PodUpdatePolicy

feat: add validation for PodUpdatePolicy

---

i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/_category_.yml
i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/kubeblocks-for-apecloud-mysql.md

Fixed the errors in the sidebar label of ApeCloud MySQL.

docs: fix cn doc errors

---

controllers/apps/transformer_cluster_service.go

fix: simply fix panic when service ports changed

---

deploy/helm/templates/_addon.tpl
deploy/helm/templates/applications/alertmanager-webhook-adaptor-addon.yaml
deploy/helm/templates/applications/apecloud-otel-collector-addon.yaml
deploy/helm/templates/applications/aws-loadbalancer-controller-addon.yaml
deploy/helm/templates/applications/csi-driver-addon.yaml
deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
deploy/helm/templates/applications/csi-hostpath-driver-addon.yaml
deploy/helm/templates/applications/grafana-addon.yaml
deploy/helm/templates/applications/loki-addon.yaml
deploy/helm/templates/applications/prometheus-addon.yaml
deploy/helm/templates/applications/snapshot-controller-addon.yaml
deploy/helm/templates/applications/vmagent-addon.yaml

fix https://kubeblocks.slack.com/archives/C050K0LPR70/p1724227335152709
```
Addon.extensions.kubeblocks.io "mysql" is invalid: [spec.helm.installOptions: Invalid value: "null": spec.helm.installOptions in body must be of type object: "null", <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]
```

chore: fix null addon.spec.helm.installValues value

---

controllers/apps/transformer_component_account_provision.go

chore: provision accounts with the role selector in Action

---

deploy/helm/templates/applications/apecloud-otel-collector-addon.yaml
deploy/helm/templates/applications/csi-driver-nfs-addon.yaml
deploy/helm/templates/applications/grafana-addon.yaml
deploy/helm/templates/applications/loki-addon.yaml

(cherry picked from commit f8b783ed6eb2e5fd260b08398c8e99207b2229f3)

chore: fix helm invalid null values (#8020)

---

cmd/manager/main.go
deploy/helm/templates/deployment.yaml
deploy/helm/values.yaml
pkg/constant/flag.go
pkg/controller/instanceset/object_builder.go
pkg/controller/instanceset/reconciler_assistant_object.go

make `$(component.name)-rsm-env` ConfigMap removable.

feat: support NoRSMEnv feature gate

---

cmd/manager/main.go
deploy/helm/templates/deployment.yaml
deploy/helm/values.yaml
pkg/constant/flag.go
pkg/controller/instanceset/object_builder.go
pkg/controller/instanceset/reconciler_assistant_object.go

(cherry picked from commit 5fe4b49d34bf9625eb1fb7d58975e4e85a005aaf)

feat: support NoRSMEnv feature gate (#8059)

---

go.mod
go.sum
pkg/controller/instanceset/instance_util.go
pkg/controller/instanceset/instance_util_test.go
pkg/controller/instanceset/reconciler_update.go
pkg/controller/instanceset/revision_util.go
pkg/lru/cache.go

(cherry picked from commit 80d091a3628794287d9c0a81bdda7bd731ba609e)

chore: P10K optimizations (#8045)

---

controllers/apps/component_controller_test.go
controllers/apps/transformer_component_workload.go
pkg/lorry/client/client.go
pkg/lorry/client/client_mock.go
pkg/lorry/client/httpclient_test.go
pkg/lorry/client/interface.go
pkg/lorry/operations/replica/leave.go

This PR is based on @newborn22's original implementation (https://github.com/apecloud/kubeblocks/pull/7892) aimed to be merged to 0.9 branch.

fix: support leave member by using any pods

---

Makefile
cmd/helmhook/hook/prepare.go
cmd/helmhook/hook/stop.go
cmd/helmhook/hook/utils.go
deploy/helm/templates/dataprotection.yaml
deploy/helm/templates/deployment.yaml
deploy/helm/templates/service.yaml

cherry pick 4f7467301212b10d53cd53bfdcb9ac6a7c18d52e

chore: exclude dataproctection pods from kb services

---

pkg/controller/scheduling/scheduling_utils.go
pkg/controller/scheduling/scheduling_utils_test.go
pkg/testutil/apps/cluster_factory.go

a quick fix for #8105, but doesn't solve the real problem IMO

fix: endless affinity list when there's a DataPlaneAffinity

---

cmd/dataprotection/main.go

fix: error "no kind is registered for the type v1.Cluster in scheme"

---

apis/apps/v1alpha1/opsrequest_webhook.go

chore: skip validate restore in webhook

---

apis/apps/v1alpha1/clusterversion_webhook.go

- to https://github.com/apecloud/kubeblocks/issues/8137

chore: remove CV create validation

---

pkg/controller/instanceset/instance_template_util.go

A supplement to https://github.com/apecloud/kubeblocks/issues/7706

feat: add BuildInstanceName2TemplateMap public api

---

docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md

change posrgresql to postgresql

docs:  fix a typo in user docs

---

go.mod
go.sum
pkg/controller/instanceset/in_place_update_util.go

fix: InPlacePodVerticalScaling not used

---

controllers/apps/transformer_component_account.go
controllers/dataprotection/backup_controller.go
controllers/dataprotection/backup_controller_test.go
controllers/dataprotection/utils.go
pkg/constant/const.go
pkg/controller/factory/builder.go
pkg/dataprotection/restore/utils.go
pkg/testutil/dataprotection/backup_utils.go

cherry pick #7703 to release-0.9

chore: support backup and restore SystemAccounts 

---

pkg/controller/component/service_reference.go
pkg/controller/component/service_reference_test.go
pkg/controller/component/vars.go
pkg/controller/component/workload_utils.go

chore: service-ref supports to refer services from different namespace

---

controllers/apps/cluster_controller_test.go
controllers/apps/component_controller_test.go
controllers/apps/transformer_component_tls_test.go
pkg/testutil/apps/cluster_util.go
pkg/testutil/apps/component_util.go

fix: flaky test cases in component_controller_test.go

---

docs/user_docs/upgrade/faq.md
docs/user_docs/upgrade/upgrade-with-helm/upgrade-kubeblocks-to-0.9.1.md

(cherry picked from commit a44fa53a7a0ba363fbce4ab8a05059387627a539)

docs: sync upgrade guide

---

apis/apps/v1alpha1/cluster_conversion.go

fix: cluster conversion NPE

---

apis/apps/v1/cluster_types.go
config/crd/bases/apps.kubeblocks.io_clusters.yaml
deploy/helm/crds/apps.kubeblocks.io_clusters.yaml

chore: update cluster print colums

---

go.mod
pkg/controller/instanceset/in_place_update_util.go
pkg/controller/instanceset/instance_util.go
pkg/controller/instanceset/instance_util_test.go
pkg/controller/instanceset/reconciler_update.go
pkg/controller/instanceset/reconciler_update_test.go

feat: support image rolling update

---

pkg/controller/instanceset/in_place_update_util.go

(cherry picked from commit 42b9d0dc8c614837f1b9a720bf7bbd88ccc67d87)

chore: keep role label when doing image in-place update (#8406)

---

pkg/controller/configuration/operator_test.go
pkg/controller/configuration/tool_image_builder.go

(cherry picked from commit 67a0f6f35ee097ed3f2025068e14f6ac063fbbae)

chore: pick build config-manager container NPE (#8335)

---

controllers/apps/transformer_component_tls.go
controllers/apps/transformer_component_tls_test.go
pkg/controller/plan/tls_utils.go
pkg/controller/plan/tls_utils_test.go

refactor: extract CharacterType from TLS configuration 

---

controllers/apps/component_controller.go
controllers/apps/transformer_component_workload.go
controllers/apps/transformer_component_workload_test.go
controllers/apps/utils.go
pkg/constant/annotations.go
pkg/testutil/apps/kb_agent_util.go
pkg/testutil/k8s/pod_util.go

fix https://github.com/apecloud/kubeblocks/issues/7874

feat: support memberjoin action

---

pkg/controller/instanceset/instance_util.go
pkg/controller/instanceset/instance_util_test.go

chore: update the pod image that does not have a registry and repository specified

---

controllers/apps/transformer_cluster_deletion.go

chore: should not execute other transformers when the cluster is deleted

---

controllers/dataprotection/backuprepo_controller.go
controllers/dataprotection/backuprepo_controller_test.go

fix: BackupRepo render template with default values

---

controllers/dataprotection/backuprepo_controller.go
controllers/dataprotection/backuprepo_controller_test.go

(cherry picked from commit 02514b385254c00281bd723618db3fd42313e556)

fix: BackupRepo render template with default values (#8523) (pick to release-0.9)

---

docs/user_docs/installation/install-kubeblocks.md
docs/user_docs/overview/supported-addons.md
i18n/zh-cn/user-docs/installation/install-kubeblocks.md

(cherry picked from commit 860adbafcfa8c7a60da1a6d294177f100e3819ac)

docs: sync installation and overview docs from the main branch

---

cmd/manager/main.go
controllers/trace/informer_manager.go

fix: no kind xxx is registered

---

docs/developer_docs/integration/environment-variables-and-placeholders.md
docs/developer_docs/integration/multi-component.md
docs/user_docs/connect_database/connect-database-in-production-environment.md
docs/user_docs/installation/install-addons.md
i18n/zh-cn/developer-docs/integration/environment-variables-and-placeholders.md
i18n/zh-cn/developer-docs/integration/multi-component.md
i18n/zh-cn/user-docs/connect-databases/connect-to-database-in-production-environment.md
i18n/zh-cn/user-docs/installation/install-addons.md

(cherry picked from commit 7c4cdd45fc80cd43d756a8b52124d62411127afa)

docs: fix format bugs

---

apis/apps/v1/component_types.go

fix: empty labels and annotations in the component API

---

controllers/apps/transformer_component_workload.go

fix: nilptr for memberjoin

---

docs/user_docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
docs/user_docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
docs/user_docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
docs/user_docs/kubeblocks-for-milvus/manage-milvus.md
docs/user_docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
docs/user_docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
docs/user_docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kubeblocks.md
docs/user_docs/kubeblocks-for-qdrant/manage-qdrant.md
docs/user_docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
docs/user_docs/kubeblocks-for-redis/cluster-management/create-and-connect-a-redis-cluster.md
docs/user_docs/kubeblocks-for-starrocks/manage-starrocks.md
docs/user_docs/observability/monitor-database.md
i18n/zh-cn/user-docs/kubeblocks-for-apecloud-mysql/cluster-management/create-and-connect-an-apecloud-mysql-cluster.md
i18n/zh-cn/user-docs/kubeblocks-for-elasticsearch/manage-elasticsearch.md
i18n/zh-cn/user-docs/kubeblocks-for-kafka/cluster-management/create-a-kafka-cluster.md
i18n/zh-cn/user-docs/kubeblocks-for-milvus/manage-milvus.md
i18n/zh-cn/user-docs/kubeblocks-for-mongodb/cluster-management/create-and-connect-to-a-mongodb-cluster.md
i18n/zh-cn/user-docs/kubeblocks-for-postgresql/cluster-management/create-and-connect-a-postgresql-cluster.md
i18n/zh-cn/user-docs/kubeblocks-for-pulsar/cluster-management/create-pulsar-cluster-on-kb.md
i18n/zh-cn/user-docs/kubeblocks-for-qdrant/manage-qdrant.md
i18n/zh-cn/user-docs/kubeblocks-for-rabbitmq/manage-rabbitmq.md
i18n/zh-cn/user-docs/kubeblocks-for-redis/cluster-management/create-and-connect-to-a-redis-cluster.md
i18n/zh-cn/user-docs/kubeblocks-for-starrocks/manage-starrocks.md
i18n/zh-cn/user-docs/observability/monitor-database.md

1. Updated kbcli cluster create cli command examples
2. Updated create cluster yaml examples using cmpd method
3. Added ApeCloud MySQL, MySQL, PostgreSQL, Redis examples for creating PodMonitor

docs: update cluster create cli command, yaml examples and monitoring docs

---

pkg/lorry/engines/redis/manager.go
pkg/lorry/engines/redis/manager_test.go

fix: lorry support redis 5.x

---

pkg/operations/expose.go

fix https://github.com/apecloud/apecloud/issues/9134

fix: expose svc for sharding

---

controllers/apps/cluster/transformer_cluster_backup_policy.go
controllers/dataprotection/backup_controller_test.go
controllers/dataprotection/utils.go
deploy/helm/templates/rbac/clusterrole.yaml
pkg/dataprotection/backup/scheduler.go

fix https://github.com/apecloud/kubeblocks/issues/8817
1. incremental backup cronJob only creates incremental backup when  completed full backups are found.
2. disables other incremental backup schedule in the transformer.
3. fix scheduled incremental backup and add some tests.

fix: incremetal backup cronJob

---

pkg/controller/factory/builder.go

chore: apply labels and annotations from the user to the its object

---

docs/user_docs/handle-an-exception/full-disk-lock.md
docs/user_docs/installation/install-kbcli.md
docs/user_docs/maintenance/backup-and-restore/backup/backup-repo.md
i18n/zh-cn/user-docs/handle-an-exception/full-disk-lock.md
i18n/zh-cn/user-docs/installation/install-kbcli.md
i18n/zh-cn/user-docs/maintenance/backup-and-restore/backup/backup-repo.md

1. Added how to specify a version when installing kbcli on Linux.
2. Added how to upgrade kbcli.
3. Added the troubleshooting part for backup repo.
4. Added steps for enabling/disabling full disk lock.

docs: fix bugs in kbcli, full disk lock and backuprepo docs in release-0.9

---

pkg/dataprotection/backup/scheduler.go

fix: enable pitr failed for postgresql

---

deploy/helm/templates/configmap.yaml

picked from 1ede668ee79c779738e6a22e3c76c4eba05a4e1c

chore: helm values for registry config (#8716)

---

pkg/lorry/engines/redis/get_replica_role.go
pkg/lorry/engines/redis/redis.go

fix: redis sentinel get role

---

controllers/apps/component/transformer_component_workload.go

fix: should no change the reclaim policy of PV to Delete

---

cmd/lorry/main.go
pkg/lorry/engines/redis/get_replica_role.go
pkg/lorry/engines/redis/manager.go
pkg/lorry/engines/redis/redis.go

fix: redis getrole from sentinel

---

controllers/dataprotection/storageprovider_controller.go
controllers/dataprotection/storageprovider_controller_test.go
controllers/storage/storageprovider_controller.go
controllers/storage/storageprovider_controller_test.go

Related to https://github.com/apecloud/kubeblocks/issues/9016.

fix: don't add finalizer for StorageProvider (to release-0.9)

---

controllers/apps/cluster/transformer_cluster_component_status.go

fix: invalid sharding phase of Abnormal

---

cmd/manager/main.go
controllers/parameters/parameter_controller.go
controllers/parameters/parameter_util.go
controllers/parameters/suite_test.go
pkg/controllerutil/util.go

fix: the parameters CR are not deleted

---

pkg/controller/instanceset/utils.go
pkg/controller/plan/restore.go
pkg/dataprotection/restore/manager.go
pkg/dataprotection/restore/manager_test.go

fix: add InstanceSet related labels to restored PVCs

---

controllers/apps/operations/reconfigure.go
controllers/apps/operations/reconfigure_test.go

fix: reconfigure ops phase is incorrect

---

controllers/apps/cluster/transformer_cluster_sharding_account.go
controllers/apps/component/transformer_component_account.go
controllers/apps/util/utils.go
controllers/apps/util/utils_test.go
pkg/constant/backup.go
pkg/controller/factory/builder.go
pkg/dataprotection/restore/utils.go

ref https://github.com/apecloud/kubeblocks/pull/7703

chore: restore accounts from backup cr

---

controllers/apps/component/transformer_component_notifier.go

- fix https://github.com/apecloud/kubeblocks/issues/9077

chore: skip notifying the dependent components being updated

---

controllers/dataprotection/backup_controller_test.go
controllers/dataprotection/restore_controller_test.go

ref https://github.com/apecloud/kubeblocks/pull/9072

chore: backup retention period test failure in release-0.9

---

controllers/parameters/policy_util.go
controllers/parameters/policy_util_test.go

fix: the static parameter reconfigure did not take effect

---

pkg/controller/component/synthesize_component.go

fix: build sa without role probe

---

controllers/apps/component/transformer_component_service.go
pkg/controller/component/workload_utils.go

fix: pod services for the instance template

---

controllers/apps/transformer_cluster_api_normalization.go
controllers/apps/transformer_cluster_backup_policy.go
controllers/apps/transformer_cluster_component.go
controllers/apps/transformer_cluster_component_status.go
controllers/apps/transformer_cluster_credential.go
controllers/apps/transformer_cluster_placement.go
controllers/apps/transformer_cluster_service.go
controllers/apps/transformer_cluster_shared_account.go

fix: cluster deleting should take the termination policy into account

---

pkg/controller/instanceset/instance_util.go
pkg/controller/instanceset/reconciler_update.go
pkg/controller/instanceset/reconciler_update_test.go

fixes https://github.com/apecloud/kubeblocks/issues/9070

chore: allow updating pending pod in instanceset

---

pkg/controller/plan/tls_utils.go
pkg/controller/plan/tls_utils_test.go

pick #8200 
resolve https://github.com/apecloud/kubeblocks/issues/8199

fix: user provided tls 09

---

apis/apps/v1/componentdefinition_types.go
config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
pkg/controller/factory/builder.go

chore: declare the default value of the pod management policy

---

controllers/extensions/addon_controller_stages.go
deploy/helm/templates/deployment.yaml
deploy/helm/values.yaml
pkg/constant/viper_config.go

Support to set addon charts image pull policy.

chore: support set addon charts image pull policy

---

controllers/parameters/config_related_helper.go

fix: remove component annotation checking for configs

---

controllers/apps/component/transformer_component_rbac.go

fix: conflicting Secret management in SA

---

controllers/apps/cluster/transformer_cluster_component.go
controllers/apps/cluster/transformer_cluster_component_test.go

chore: allow the component to be updated when the predecessor does not exist

---

pkg/controller/component/synthesize_component.go

* fix https://github.com/apecloud/kubeblocks/issues/9279

fix: build sa with specific lifecycle

---

controllers/extensions/addon_controller_stages.go
deploy/helm/templates/deployment.yaml
pkg/constant/const.go

(cherry picked from commit 235a4af5f362dbfb757f223678f02e7ef83fc38c)

chore: support set addon charts image pull policy (#9224)

---

controllers/apps/component/transformer_component_vars.go
controllers/apps/component/transformer_component_vars_test.go
controllers/apps/component/transformer_component_workload_ops.go

close https://github.com/apecloud/kubeblocks/issues/9269

chore: remove deleted env vars from the env CM

---

pkg/controller/instanceset/instance_template_util.go
pkg/controller/instanceset/instance_util.go
pkg/controller/instanceset/instance_util_test.go
pkg/controller/instanceset/reconciler_revision_update.go

chore: zero replicas of the instance template

---

controllers/apps/util/utils.go
controllers/apps/util/utils_test.go

merge back changes in https://github.com/apecloud/kubeblocks/pull/9252 to main

fix: use first backup source when restoring systemaccount

---

pkg/controller/component/component_lifecycle_action_utils.go

fixes https://github.com/apecloud/apecloud/issues/11341

fix: don't apply pod anti-affinity and TopologySpreadConstraints for action job

---

pkg/configuration/openapi/flatten.go
pkg/controller/configuration/parameter_utils.go

e.g clickhouse user profile parameters
```
#ProfilesParameter: {
[string]: #ClickhouseUserParameter
// ignore other configure
}
#ClickhouseUserParameter: {
...
}
```

chore: support unstructured parameter reconfigure, such as map defined in CUE

---

controllers/apps/componentversion_controller.go

fix: validate the service version before use it

---

apis/apps/v1/componentdefinition_types.go
apis/workloads/v1/instanceset_types.go
config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
config/crd/bases/workloads.kubeblocks.io_instancesets.yaml
controllers/apps/component/transformer_component_workload.go
deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
deploy/helm/crds/workloads.kubeblocks.io_instancesets.yaml
docs/developer_docs/api-reference/cluster.md
pkg/controller/builder/builder_instance_set.go
pkg/controller/factory/builder.go
pkg/controller/instanceset/reconciler_assistant_object.go

chore: disable the default headless service

---

controllers/apps/cluster/cluster_controller.go
controllers/apps/cluster/transformer_cluster_deletion.go
controllers/apps/cluster/transformer_cluster_deletion_test.go
controllers/apps/cluster/transformer_cluster_termination_policy.go
controllers/apps/component/transformer_component_deletion.go

fix: update the termination policy of cmp when the cluster is deleting

---

controllers/dataprotection/backup_controller.go
controllers/dataprotection/backup_controller_test.go
controllers/dataprotection/utils.go

* inherit encrytion config from parent backup
* validate parent backup's encrytion config

chore: inherit encrytion config from parent backup

---

controllers/workloads/instanceset_controller.go
pkg/dataprotection/restore/manager_test.go

close https://github.com/apecloud/kubeblocks/issues/9450

chore: updates from PVC are lost

---

pkg/constant/annotations.go
pkg/dataprotection/restore/manager.go
pkg/dataprotection/restore/manager_test.go

This reverts commit 29e9bbd6221908a3240d99891daef40468944bda.

chore: Revert "feat: add an option to merge full and pitr restore job (#9404)"

---

apis/apps/v1/types.go
config/crd/bases/apps.kubeblocks.io_clusters.yaml
config/crd/bases/apps.kubeblocks.io_componentdefinitions.yaml
config/crd/bases/apps.kubeblocks.io_components.yaml
controllers/apps/cluster/transformer_cluster_sharding_account.go
controllers/apps/component/transformer_component_account.go
deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
deploy/helm/crds/apps.kubeblocks.io_componentdefinitions.yaml
deploy/helm/crds/apps.kubeblocks.io_components.yaml
docs/developer_docs/api-reference/cluster.md
pkg/common/password.go
pkg/common/password_test.go

fix https://github.com/apecloud/kubeblocks/issues/9458

feat: specify allowed symbols in password generation

---

pkg/constant/annotations.go
pkg/dataprotection/restore/manager.go
pkg/dataprotection/restore/manager_test.go

chore: support merging full ptir job in release-0.9

---

cmd/reloader/template/main.go
pkg/configuration/config_manager/reload_util.go
pkg/configuration/core/config_util.go
pkg/configuration/core/config_util_test.go
pkg/configuration/core/type.go
pkg/controller/configuration/patch_merger.go
pkg/controller/configuration/template_merger.go
pkg/controller/configuration/template_merger_test.go
pkg/controller/configuration/value_transformer.go
pkg/unstructured/viper_wrap.go

(cherry picked from commit 265a6c2a83273d1ebe6ccd5780f244fa01070949)

fix: pick the format difference between number/boo/float and string for json (#9488)

---

go.mod
pkg/controller/instanceset/reconciler_update.go
pkg/controller/instanceset/reconciler_update_test.go
pkg/controller/kubebuilderx/plan_builder.go
pkg/controller/kubebuilderx/plan_builder_test.go
pkg/controller/kubebuilderx/reconciler.go
pkg/controller/kubebuilderx/reconciler_test.go
pkg/controller/kubebuilderx/suite_test.go
pkg/controller/model/graph_options.go
pkg/controller/model/transform_types.go
pkg/controllerutil/util.go
pkg/controllerutil/util_test.go
pkg/dataprotection/backup/utils.go
pkg/dataprotection/utils/utils.go
pkg/dataprotection/utils/utils_test.go

(cherry picked from commit e788102f0271d847edd55968d6ef3e0d76aaf89e)

fix: use /resize subresource in InPlacePodVerticalScaling when supported (#9349)

---

apis/apps/v1beta1/type.go
config/crd/bases/apps.kubeblocks.io_configconstraints.yaml
deploy/helm/crds/apps.kubeblocks.io_configconstraints.yaml
docs/developer_docs/api-reference/cluster.md
pkg/unstructured/properties.go
pkg/unstructured/properties_test.go

(cherry picked from commit ae7016a2c87e14149268b4c96b5cd4f81d8bc0b8)

chore: add new properties formatter for nebula addon (#9528)

---

deploy/helm/templates/storageprovider/oss.yaml

fix: ignore BucketAlreadyExists errors for OSS

---

pkg/dataprotection/restore/builder.go
pkg/dataprotection/restore/manager.go
pkg/dataprotection/restore/manager_test.go

…InstanceTemplate and ordinals
resolves #9564

fix: Restore job's label did not respect InstanceTemplate and ordinals

---

controllers/extensions/addon_controller_stages.go
controllers/extensions/const.go
deploy/helm/templates/_helpers.tpl
deploy/helm/templates/deployment.yaml
deploy/helm/templates/rbac/clusterrole_binding.yaml
deploy/helm/templates/serviceaccount.yaml
deploy/helm/values.yaml

(cherry picked from commit 13d89ebba79140773110c0749785db14050d0757)

chore: addon controller use kb sa for kb09

---

pkg/controller/configuration/value_transformer.go
pkg/dataprotection/restore/builder.go
pkg/unstructured/viper_wrap_test.go

related pr: https://github.com/apecloud/kubeblocks/pull/9565#issuecomment-3126018852

chore: support parameter value transformer for toml formatter

---

apis/operations/v1alpha1/opsrequest_validation.go
pkg/controller/instanceset/instance_util.go
pkg/controller/instanceset/instance_util_test.go
pkg/operations/volume_expansion.go
pkg/operations/volume_expansion_test.go

fix: volume expansion failed when all pods using InstanceTemplate[pick-1.0]

---

.github/workflows/cicd-pull-request.yml

fix ref https://github.com/apecloud/kubeblocks/actions/runs/16591830142/job/46929143901

chore: fix check run error

---

apis/apps/v1/cluster_types.go
config/crd/bases/apps.kubeblocks.io_clusters.yaml
controllers/apps/cluster/transformer_cluster_component_status.go
controllers/apps/cluster/transformer_cluster_status.go
deploy/helm/crds/apps.kubeblocks.io_clusters.yaml
docs/developer_docs/api-reference/cluster.md

chore: ensure the consistency of updating cluster status

---

controllers/dataprotection/backuprepo_controller.go
pkg/dataprotection/utils/backuprepo.go

chore: run BackupRepo precheck job with non-root user

---

pkg/controller/instanceset/in_place_update_util.go

fix: pod update policy for the stopping ITS

---

controllers/apps/cluster/transformer_cluster_component.go

cherry picked from commit 5f4737aab7cb17de3729b3d7b6c6e8534e196607

chore: fill in the actual component name for the sharding scheduling policy
